### PR TITLE
add: config option for 8T span resevoir

### PR DESCRIPTION
**Pull request by brnhensley**
Added info about an undocumented configuration option to set the amount of infinite tracing spans the agent will hold in memory before dropping them. [Other agents suggest setting this to 100k](https://docs.newrelic.com/docs/distributed-tracing/troubleshooting/missing-trace-data/#spans), so that's the number I used in this doc.

- https://github.com/newrelic/node-newrelic/blob/9be213963938ba9bbfac251ba594952a964631bc/lib/config/default.js#L1103-L1124

I'd like to include a maximum value and the time period for these queues (it might be 60 seconds or 5 seconds (12 times a minute), different agents send on different periods).

Maximum value seems to not be a regular number, but a payload size so I'm not sure I can add one. I'm requesting that the node team look this over to confirm my changes.

### CODE REVIEW

**Comment by rhetoric101** [comment]
@brnhensley let us know when you get confirmation from the Node team.

**Comment by nbaenam** [comment]
Hi @brnhensley, I'm going to move moved this PR to our draft category. When you're ready to publish, reach out to the Docs team and we'll get it merged!

**Comment by brnhensley** [comment]
@rhetoric101 node team told me more about how this works and I've updated my note. This is ready for review from your team now.

**Comment by brnhensley** [comment]
I added an unrelated commit here since the PR is still open, to avoid making more for small things

**Review by bradleycamacho — APPROVED** [review]

**Pull request merged**
