### PR TITLE
Use nav yaml to generate all index page content

### PR DESCRIPTION
**Pull request by roadlittledawn**
## Description

Uses nav yaml file data to generate content on all auto generated index pages (similar to `/table-of-contents` pages).

If we attached the correct nav yaml data for an index page, but we only want to show just the section of the nav that matches where we are in the URL path, we look through the nav object and pull out the object where the `url` matches the slug of the page we're on.

If an index page path is used in a nav yaml file where the top level path differs from the beginning of its path, we try to find the nav yaml file that matches it and use that.

If an `.mdx` file or a file directory are not referenced in any nav yaml file, we cannot attach a nav menu to them, so the left nav is empty when viewing them. Examples include:
- https://docs.newerlic.com/docs/plugins
- https://docs.newrelic.com/docs/plugins/plugin-developer-resources/develop-plugins/checklist-developing-plugins/

If a file directory with content exists, but is not referenced in any nav YAML file, we fall back to the old behavior of creating auto index page and populating that with the file system data via `generateHtml()`.

## Docs
Style guide doc updated for this: https://github.com/newrelic/docs-website/pull/2260/files#diff-43de305ddfb201cf81b0cee4a20f4e700d6f154847bbbd6eddb91be29d6ef51e

## Related issues / PRs
Closes https://github.com/newrelic/docs-website/issues/2007

Follow up issue to create auto index pages for all nav paths: https://github.com/newrelic/docs-website/issues/2340

## Screenshots

[AWS integration list index page](https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/)

Screen Shot 2021-05-18 at 12 28 25

[NR1 pricing and billing page](https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-pricing-billing/new-relic-one-pricing-billing/)

Screen Shot 2021-05-18 at 13 12 11

## Reviewer notes
- We may be able to refactor to combine `indexPage` and `tableOfContents` templates, but a lot of the old functionality is in place as a fallback in case a file directory with content exists, but is not present anywhere in the nav.
- If  a path exists in a nav YAML file that `gatsby-plugin-auto-index-pages` did not create a page for, it currently cannot get an index page. Upon digging in a bit, I'm a [little leery of supporting that](https://github.com/newrelic/docs-website/pull/2260#issuecomment-843640205).

### CODE REVIEW

**Comment by roadlittledawn** [comment]
build failed due to `/docs/mobile-apps` being an index page used in `new-relic-in-practice.yml` with a top level path that uses `/docs/using-new-relic`. there isn't a nav yaml that uses a top level path of `/docs/mobile-apps`, there's only a file directory for that. and i imagine there will likely be several instances like this where the top level URL path of a given index page references a file directory that doesn't match 1:1 with a nav yaml file.

not sure i currently see a way to distinguish between:
- an index page menu item that actually belongs to a nav yaml menu that doesn't share the same top level path that when viewed shows the nav menu that's referencing it 
VS
- an index page menu item that actually belongs to another nav yaml menu that when viewed, shows  its "true" nav menu

**Comment by roadlittledawn** [comment]
re: trying to avoid the need to add paths for all sections in nav yaml files. it's ideal to have those path values in the nav yaml because:
- i found many instances where within a given section the URL paths don't match the top level nav path (ex. linking to an index page in another top level nav), so nav menus would be incomplete in many cases if all we can do is try to match with a menu item's `url` value including the `location.pathname`.
- nav item URL paths must point to an actual folder path. the `gatsby-plugin-auto-index-pages` looks at the file directories when determining if it should create a page and if so sets the URL path based on the file directory path.

**Comment by roadlittledawn** [comment]
turns out the work i had locally to address creating pages for nav paths not found in `.mdx` or `.md` file paths worked, but didn't quite work while running local dev server.

looking at [how many such paths there](https://gist.github.com/roadlittledawn/ff98fbc36632ee18ed740a23f48c429e) are in this branch's nav YAML files, there's 156 paths. but on a quick inspection, many paths already have pages created via other `gatsby-node.js` code. examples:
- /attribute-dictionary
- /nru
- /docs/release-notes/agent-release-notes/java-release-notes/current

not yet quite sure how we check to ensure a page already exists at a given path. and also not quite sure we really want any ol' path added to a YAML file to drive page creation.

**Review by zuluecho9 — APPROVED** [review]
I check this out locally and also Austin Schaefer reviewed it, and we say go for it.

**Review by aswanson-nr — APPROVED** [review]
:shipit:

**Review by zstix — APPROVED** [review]
This looks great, nice work!

**Comment by roadlittledawn** [comment]
merging without review this time. only change was to resolve merge conflict on one line in a yaml file.

**Pull request merged**
