### PR TITLE
chore: add stakeholders to translation prs as reviewers

### PR DESCRIPTION
**Pull request by nr-kkenney**
## Summary

Add Julien (stakeholder) as reviewer on translation PRs

Resolves: #3853

### CODE REVIEW

**Review by clarkmcadoo — APPROVED** [review]

**Comment by clarkmcadoo** [comment]
@nr-kkenney, I think we talked about this for about 4 seconds, but adding a group for something like this in the future might be useful just to manage it via github instead of code changes.  What do you think?

**Comment by nr-kkenney** [comment]
@clarkmcadoo i asked on the main ticket, but what is a group? i think I've only seen `teams` as a way to collect individual people, and I'm not 100% on making a new team for our org. But I'll double check.

**Comment by clarkmcadoo** [comment]
Yeah, that's probably it.  Idk, we'd probably need another ticket for it cuz we'd have to figure out who to put on that team, then actually do it.

**Comment by clarkmcadoo** [comment]
`https://github.com/orgs/newrelic/new-team` makes a new team, but lets talk about this a little bit more before we do anything, it was just an idea.

**Pull request merged**
