### PR TITLE
docs: Adds instructions for installing the .NET agent on AWS Elastic Beanstalk

### PR DESCRIPTION
**Pull request by tippmar-nr**
Adds instructions for installing the .NET agent on AWS Elastic Beanstalk.

### CODE REVIEW

**Comment by tippmar-nr** [comment]
@jeff-colucci  I need some help getting this new page to show up on the left nav correctly. I added it to `apm.yml` but there must be more to it, as the left nav doesn't render correctly when I open the new page I added. The new page link appears in the left nav, but then the whole left nav collapses when I open the page. 
image
image

**Comment by tippmar-nr** [comment]
@jeff-colucci I think I fixed it -- the path in `apm.yml` was incorrect. Waiting for the next preview build to verify. 

Also waiting on some feedback from members of my team before I mark this PR as ready for review.

**Comment by jeff-colucci** [comment]
Looks like you fixed it, if it's still broken let me know and I'll take a look and get it taken care of. I don't want you to have to worry about the little technical issues like this. Just let me know when it's ready for a review and I'll hop right on it!

**Review by jeff-colucci — APPROVED** [review]
Looks great to me!

**Pull request merged**
