### PR TITLE
feat(Service Level Management): Include timeslice data examples

### PR DESCRIPTION
**Pull request by jdvr**
Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?

Create example for timeslice data usage in the Service Level Management product.

* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.

* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Comment by akristen** [comment]
Hi @jdvr! I see this is a draft PR. When you're ready for this to publish to the docs site, reach out to our hero. We'll review the final copy and get this merged for you. Thanks!

**Comment by rhetoric101** [comment]
I am not sure why this is failing because there are no errors listed in verify-mdx. I will temporarily close and reopen to see if that fixes it.

**Review by rhetoric101 — COMMENTED** [review]
@jdvr thanks for adding this new section! I noticed that many of the NRQL examples use colons following the operators. I don't think this is valid syntax. I made some suggestions below, but I see that even outside your contributions, this syntax is prevalent.

**Comment by jdvr** [comment]
> @jdvr thanks for adding this new section! I noticed that many of the NRQL examples use colons following the operators. I don't think this is valid syntax. I made some suggestions below, but I see that even outside your contributions, this syntax is prevalent.

@rhetoric101 nice catch!

I have updated the whole document!

**Review by rhetoric101 — APPROVED** [review]
@jdvr Thanks for adding this new section and fixing the queries!

**Pull request merged**
