### PR TITLE
Remove non-o11y features

### PR DESCRIPTION
**Pull request by planteater**
Most of the non-observability features are being removed from CodeStream. This is an initial somewhat inelegant pass at the docs to remove references to those features. A fairly substantive overhaul of the CodeStream docs will take place in the next three or four weeks as part of the unified identity project, and that will be a more thoughtful reorganization effort.

### CODE REVIEW

**Comment by planteater** [comment]
@homelessbirds - Any chance you could help me with this build failure? I'm guessing it's related to the images in the teams-administration.mdx file. The initial preview didn't seem to include the updated images, which were added as png. I then deleted the corresponding webp files, thinking that this would force the new pngs to get converted to webp. But maybe that caused problem?

**Comment by homelessbirds** [comment]
@planteater can you upload the images again as webp files? If that doesn't work we can try a few more things!

**Comment by planteater** [comment]
@homelessbirds - I was able to find a tool for converting png to webp, and just pushed those two new images. Hopefully that does the trick!

**Review by akristen — APPROVED** [review]
Thanks for working on this! Excited to get this merged after all its finicky behavior. 😉

**Pull request merged**
