### PR TITLE
Make OpenTelemetry more visible (2nd PR)

### PR DESCRIPTION
**Pull request by rhetoric101**
This is a successor to the original PR #7175 to make OpenTelemetry more visible/accessible on the site. This PR does two things:

* Adds "OpenTelemetry" to the left navigation pane of the home page.
* Adds a new collapser for OpenTelemetry and other open source tools to the primary installation doc.
* Adds a link to the new Kubernetes/OpenTelemetry doc from the collector page (a previous oversight)

### CODE REVIEW

**Comment by rhetoric101** [comment]
Closing temporarily to see if reopening it will trigger a successful license check.

**Comment by LizBaker** [comment]
gatsby froze on the uploading step

**Review by paperclypse — APPROVED** [review]
Looks good. I left a couple of comments for you on CodeStream, @rhetoric101.

**Review by paperclypse — APPROVED** [review]
Looks good!

**Pull request merged**
