### PR TITLE
AlloyDB documentation

### PR DESCRIPTION
**Pull request by jordigarcl**
Adding documentation for GCP AlloyDB integration

Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Comment by jordigarcl** [comment]
Hi @x8a ! This is ready for review :)

**Review by x8a — DISMISSED** [review]
Thanks for the new doc!

**Comment by jordigarcl** [comment]
Thanks! What is the process for merging ? :)

**Comment by x8a** [comment]
Once the checks pass, I'll merge it 💃🏻.

**Comment by jordigarcl** [comment]
Thanks! 😉

**Comment by jordigarcl** [comment]
Build is failing - do you think it has something to do with the additions in this PR? 🤔

**Comment by x8a** [comment]
I'm trying to see what's wrong but the files seem to be fine. I talked to the engineers of our site and we're investigating.

I'll keep you posted 🙌🏻!

**Review by x8a — APPROVED** [review]

**Pull request merged**
