### PR TITLE
DOC-7901 Alerts & AI nav reorganization

### PR DESCRIPTION
**Pull request by paperclypse**
We don't need an engineering review on this one.

### CODE REVIEW

**Comment by barbnewrelic** [comment]
@paperclypse  I was going to review this for you, but it's still in draft state. Intentional? Also, now it looks like it has some merge conflicts. If you think this PR really is ready for review, let me know and I'll take a look. Although you are much better at resolving merge conflicts than I am. :-)

**Review by barbnewrelic — COMMENTED** [review]
This looks ok to me, but don't you have to move the files in the translation taxonomy too?

**Review by barbnewrelic — APPROVED** [review]
Just one question about the translation taxonomy, then go ahead and merge.

**Comment by paperclypse** [comment]
@barbnewrelic I'll check on this, but I think that the translated nav files are auto-updated...

**Comment by paperclypse** [comment]
Waiting on final SME approval

**Pull request merged**
