### PR TITLE
Fix bytecountestimate typo

### PR DESCRIPTION
**Pull request by neilfordyce**
The function is bytecountestimate not bytescountestimate

### CODE REVIEW

**Review by x8a — APPROVED** [review]
Thanks for catching this!

**Comment by x8a** [comment]
Hi, @neilfordyce! Could you sign the CLA? We need all contributors to do so before we can merge their PRs.

Thanks a lot for helping us make the docs awesome!

**Comment by x8a** [comment]
Friendly reminder, that we need you to sign the CLA before we can merge your PR, @neilfordyce 🙌🏻.

**Comment by neilfordyce** [comment]
@x8a sorted, thanks for the reminder!  Completely missed that first time around

**Pull request merged**
