### PR TITLE
fix: update option from bar to area chart for units

### PR DESCRIPTION
**Pull request by thezackm**
small fix to update the scope of the "units customization" to include area charts, not bar charts (which are not time series and don't have this option).

### CODE REVIEW

**Comment by zuluecho9** [comment]
thanks @thezackm

**Review by zuluecho9 — APPROVED** [review]

**Comment by miguelsancheznewrelic** [comment]
@thezackm , thanks!
I would also correct "and stacked charts", which they mean "stacked bar charts".
At the end of the day, our area chart and stacked bar charts are both stacked.

**Comment by miguelsancheznewrelic** [comment]
> @thezackm , thanks! I would also correct "and stacked charts", which they mean "stacked bar charts". At the end of the day, our area chart and stacked bar charts are both stacked.

cc @zuluecho9

**Comment by thezackm** [comment]
thanks @miguelsancheznewrelic - added PR #10950 to address this

cc: @zuluecho9

**Pull request merged**
