### PR TITLE
Clarify lack of PRW support for FedRAMP-compliant metrics endpoint

### PR DESCRIPTION
**Pull request by jgals**
The Prometheus remote write integration should not be used with the FedRAMP-compliant metrics endpoint at this time.

@jsgithub1 and @bsummer, please review. I'm hoping to make this edge case more noticeable for customers and support.

FYI @jonahaapala

Here's what that change looks like for me rendered locally (to save you all from having to run `yarn`, `yarn start`, etc.):

jgals:METRICS-608

### CODE REVIEW

**Review by jonahaapala — DISMISSED** [review]
LGTM

**Comment by austin-schaefer** [comment]
Hi @jgals , looks like this PR is still marked as "draft". Is this ready to be reviewed and merged?

**Comment by jgals** [comment]
Not yet, @austin-schaefer, I'm waiting on a related ticket to be marked as done first. I'll check-in with that team.

**Comment by jgals** [comment]
The associate change to the handling of PRW traffic bound for our gov metric endpoint will be deployed soon.

**Review by bradleycamacho — APPROVED** [review]

**Pull request merged**
