### PR TITLE
Oma qf bb khickey

### PR DESCRIPTION
**Pull request by barbnewrelic**
This reproduces the OMA quality foundation doc which we were unable to build successfully in the previous branch.

### CODE REVIEW

**Comment by barbnewrelic** [comment]
Dear reviewer: This is an OMA doc (currently doesn't have a related Jira), so please just look for any obvious typos and that the screenshots render successfully. Don't worry about structural edit or content edit. That will be handled later. I will be OOO until next week, so if you have other questions, please go to the oma-docs slack. Thanks!

**Comment by barbnewrelic** [comment]
Dear OMA and Docs teams: I've moved this back to DRAFT simply so that it does not get merged until the OMA team signs off. I've asked them to edit and/or approve directly in this PR. Once you get the OK from them, please do the basic review that I mentioned earlier. I do NOT need to be the person to merge to main. Thanks so much for keeping this pr in process while I am OOO!

**Review by khickey-newrelic — APPROVED** [review]

**Comment by khickey-newrelic** [comment]
Looks good - thank you

**Comment by barbnewrelic** [comment]
@bradleycamacho  I don't think you need to review this. The OMA team has already reviewed it, and I have also reviewed it. Can we please just go ahead and merge so it gets included in today's release? Thanks!

**Comment by bradleycamacho** [comment]
@barbnewrelic Yeah go ahead!

**Pull request merged**
