### PR TITLE
Hold on merging: Update the kubernete supported version.

### PR DESCRIPTION
**Pull request by vuqtran88**
Bump the kubernete supported version to 1.25

### CODE REVIEW

**Review by jeff-colucci — APPROVED** [review]
Made a slight styling tweak, looks good otherwise!

**Comment by vuqtran88** [comment]
Hi @jeff-colucci, thanks for reviewing. I want to hold this off from merging until we release our code.

**Comment by jeff-colucci** [comment]
> Hi @jeff-colucci, thanks for reviewing. I want to hold this off from merging until we release our code.

No problem! I will put this in the hold on merging section of our board until you are ready. If it is today you can just let me know when it's good to go, if it is in the future just let the doc hero know whenever you are ready to merge and we will get it put in for you. Thank you!

**Comment by vuqtran88** [comment]
Thanks @jeff-colucci , it will be today and I will surely let you know.

**Comment by jeff-colucci** [comment]
Work was done as part of [this story](https://github.com/newrelic/docs-website/pull/10627) so we'll close this ticket.

**Pull request closed without merging**
