### PR TITLE
NR-58210-Prometheus-OpenMetrics-documentation-update

### PR DESCRIPTION
**Pull request by pkosanam**
JIRA Ticket: https://issues.newrelic.com/browse/NR-58210

Description: We have seen that Prometheus OpenMetrics can also be installed and used directly on a linux machine too. Hence I have contributed to this page. As I am not a professional technical writer, request you to kindly review my changes.

Thank you. 🙂

Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Review by x8a — APPROVED** [review]
Thanks so much for adding this info!

**Review by x8a — APPROVED** [review]

**Comment by x8a** [comment]
Hi, @roobre! Is there any update on this? Thanks!

**Comment by roobre** [comment]
I think at this point whether to graduate this feature to public availability or not is a decision for @mangulonr to make.

From my side I don't think we should merge this in the current state.

**Comment by mangulonr** [comment]
Hi 

We are not officially supporting nri-prometheus in On Host environments. 
This has been already discussed with Growth team last week.

Until we don't make a decision we should not proceed with this PR.

**Comment by x8a** [comment]
Closing this PR as per @mangulonr request.

**Pull request closed without merging**
