### PR TITLE
Update nodejs-agent-configuration.mdx

### PR DESCRIPTION
**Pull request by tytyhibye**
per the Node Agent repo, browser monitoring is set to false by default.

Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Comment by akristen** [comment]
Hi @tytyhibye! Can you sign the CLA so we can get this merged? Thanks!

**Review by akristen — APPROVED** [review]
Looks good!

**Comment by brnhensley** [comment]
Hye @tytyhibye would you also update the despription text:

> Generate JavaScript headers for browser instrumentation. Although this defaults to true, the agent doesn't inject the browser JS code unless you have [enabled browser monitoring](https://docs.newrelic.com/docs/browser/new-relic-browser/installation-configuration/adding-apps-new-relic-browser/). Even if you have enabled it and [added the browser timing header](https://docs.newrelic.com/docs/agents/nodejs-agent/supported-features/page-load-timing-nodejs/#procedures), you can [disable browser monitoring for your app](https://docs.newrelic.com/docs/agents/nodejs-agent/supported-features/page-load-timing-nodejs/#disabling) by setting this to false.


Feel free to use this, I was going to add it to your PR, but I'm not savvy enough to push to this PR:

> Generate JavaScript headers for browser instrumentation. Even when set to `true`, the agent doesn't inject the browser JS code unless you have [enabled browser monitoring](https://docs.newrelic.com/docs/browser/new-relic-browser/installation-configuration/adding-apps-new-relic-browser/). Even if you have enabled it and [added the browser timing header](https://docs.newrelic.com/docs/agents/nodejs-agent/supported-features/page-load-timing-nodejs/#procedures), you can [disable browser monitoring for your app](https://docs.newrelic.com/docs/agents/nodejs-agent/supported-features/page-load-timing-nodejs/#disabling) by setting this to `false`.

cut/paste md version
```md
Generate JavaScript headers for browser instrumentation. Even when set to `true`, the agent doesn't inject the browser JS code unless you have [enabled browser monitoring](https://docs.newrelic.com/docs/browser/new-relic-browser/installation-configuration/adding-apps-new-relic-browser/). Even if you have enabled it and [added the browser timing header](https://docs.newrelic.com/docs/agents/nodejs-agent/supported-features/page-load-timing-nodejs/#procedures), you can [disable browser monitoring for your app](https://docs.newrelic.com/docs/agents/nodejs-agent/supported-features/page-load-timing-nodejs/#disabling) by setting this to `false`.
```

**Comment by brnhensley** [comment]
ha, I was seconds too late I'll make a new PR

**Comment by brnhensley** [comment]
https://github.com/newrelic/docs-website/pull/13955

**Pull request merged**
