### PR TITLE
Just messing around on a high-wire

### PR DESCRIPTION
**Pull request by paperclypse**
No big deal :)

Hey @bradleycamacho, does this get us closer to the docs you love?

### CODE REVIEW

**Review by bradleycamacho — DISMISSED** [review]

**Comment by bradleycamacho** [comment]
Look out Gatsby docs, we're coming for you! Approved.

**Comment by jpvajda** [comment]
Is this a legit PR? seems "maybe" 🤔

**Comment by mmfred** [comment]
For a short term improvement, if we can revise this intro to define NR just by adding a few phrases, that's a quick win. So you could move that initial line back up, and then use the chunkier middle paragraph to introduce New Relic with more definition.
I'd love to avoid using the terms TDP and FSO in that intro to what New Relic is paragraph, and focus on the things that are mentioned in the subtitles for those products. Like, use some of the descriptions for TDP: Ingest, visualize, and alert on all your telemetry data in one place. and similarly, a phrase or two from the descriptions from FSO and Agile etc. on the landing page.

**Comment by paperclypse** [comment]
@jpvajda It's not _not_ legit :)

**Comment by paperclypse** [comment]
What do you think about my last commit, @mmfred? Closer to what you're thinking?

**Comment by mmfred** [comment]
yes! so much better! I believe that @Broseberg said we need to have this at the top, next to the three clickable boxes: If you're new, follow these three steps to create an account and get going. (It's free!) 

And if so, this can just go right below it. So the order, using the current numbers, would be:
p4
p1
p2
p3

**Comment by paperclypse** [comment]
As fun as it is to make changes to the landing page, we probably need to think through them a little more :)

**Pull request closed without merging**
