### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by brnhensley**
There was a stray `[` in the text that I removed.

Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Comment by barbnewrelic** [comment]
@brnhensley Thanks for editing this doc! After you click the link in your PR to sign the Contributor License Agreement, we will be able to proceed with reviewing and publishing. (Required for all contributors, including New Relic.)

**Comment by brnhensley** [comment]
Thanks @barbnewrelic, I did that step for my previous PR but I didn't realize I had to do that for every PR. Should be good now.

**Comment by barbnewrelic** [comment]
@brnhensley  Well that is odd, it shouldn't have made you sign it again! If this continues, I'll notify our deveng team. Thanks again for editing our docs!

**Review by barbnewrelic — APPROVED** [review]
Looks fine in Gatsby build. Thanks again!

**Pull request merged**
