### PR TITLE
Added Automatic OHI Logging

### PR DESCRIPTION
**Pull request by lchapman4**
Added a section in the docs for a new option for users where they can automatically send OHI logs to NR by simply renaming an .example file. The mysql-log.yml.example file is already in the nri-mysql repo.

Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Review by bradleycamacho — APPROVED** [review]
Made a small change to make a docs link a relative link. I'll merge in as soon as the checks finish, thanks!

**Comment by lchapman4** [comment]
Hey @bradleycamacho curious what happened to my commit here. I had a doc link for the last step for the mysql-integration.mdx file but it looks like it didn't make it out to the site. commit here: [src/content/docs/infrastructure/host-integrations/host-integrations-list/mySQL/mysql-integration.mdx](https://github.com/newrelic/docs-website/pull/6294/commits/1e787d5adcb24e17bd9a701550d56a937fedcee0)

**Comment by bradleycamacho** [comment]
@lchapman4 weird! Let me hunt this down and get back to you.

**Comment by bradleycamacho** [comment]
@lchapman4 looks like someone made an edit where they just ported that step over from the linked doc directly into the doc you edited!

**Pull request merged**
