### PR TITLE
Update no-data-metric-streams.mdx

### PR DESCRIPTION
**Pull request by sraju05**
Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Comment by rhetoric101** [comment]
@sraju05 thanks for fixing this typo! Before I can merge your change, could you sign our CLA that gives us permission to use your change?

**Comment by sraju05** [comment]
Hi,

How do I sign it?

Thanks,
Santosh

**Comment by rhetoric101** [comment]
@sraju05 try clicking on that icon further up in the PR. That should load a consent form:

image

**Review by rhetoric101 — APPROVED** [review]
@sraju05 thanks again for fixing this error!

**Pull request merged**
