### PR TITLE
Python DT Release Documentation

### PR DESCRIPTION
**Pull request by TimPansino**
**Note:** Hold this from deploying until Python gets final approval to release this.

Co-authored-by: Uma Annamalai <umaannamalai@users.noreply.github.com>
Co-authored-by: lrafeei <lrafeei@users.noreply.github.com>

### Give us some context

* Add python 7.0.0.164 release documentation
* Update python DT and reservoir documentation

### Are you making a change to site code?

No

### CODE REVIEW

**Comment by urbiz-nr** [comment]
Hello @TimPansino! Thanks for updating our docs! Do you have a release date for this?

**Comment by TimPansino** [comment]
@urbiz-nr We're hoping to release this today, need to coordinate with product to make sure it's good to go.

**Comment by TimPansino** [comment]
@urbiz-nr After further discussion we're going to have to hold this release, I'll reopen this PR when it's ready.

**Comment by dbarnesbrownNR** [comment]
Hi @TimPansino, I'm covering our day shift on the GH board today, so just to check that I understand you, you need nothing further on this PR and will reopen/open a new one when you are ready with your content and product release is confirmed? Thanks!

**Comment by TimPansino** [comment]
@dbarnesbrownNR That's correct.

**Pull request closed without merging**
