### PR TITLE
docs: reorganize overloads/params table

### PR DESCRIPTION
**Pull request by brnhensley**
This PR is a test of a redesign based on a conversation with Robert Siebens, because I'm not able to preview the table changes locally I need to see the Gatsby build to find any mistakes. 

The original table of params was kind difficult to read. I separated the table for each of the 4 overloads (technically could be 6, because the `IDictionary`s could be string/string or string/object but it didn't feel helpful to do that). I also separated `NoticeError(Exception, IDictionary)` and `NoticeError(Exception)`, the IDictionary is optional, but it was harder to read this way, also the `bool $is_expected` param in the later examples is an optional param and we separated that out for readability, so it felt consistent to do it this way. Ultimately the doc is more verbose but I believe it is easier to read.

- added the key/value type options for IDictionary, found in [the source code here](https://github.com/newrelic/newrelic-dotnet-agent/blob/main/src/Agent/NewRelic.Api.Agent/NewRelic.cs)
- made all new headers uniquely hyperlink-able
- Exception is a class, so capitalized it's type. 
- Made indentation 4 spaces for consistency with other C# docs. 
- Changed _Syntax_ section to _Overloads_ to make it more like the .NET MSDocs 
- Added `;` to the Overloads. This is only to help the syntax highlighting on the docs page which comes out a little poor currently.

Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Comment by brnhensley** [comment]
@rhetoric101 so this is finished how I was intending it to look. Currently there is one thing I don't like about it I'm interested in changing but I don't know the best option.  Basically, in the table we now have this:
image

`IDictionary<TKey, TValue>`,  should be the Type of the parameter `$attributes`, but inside it there is `TKey` and `TValue` which need their own types defined seperately, which I did in the Description. This is becayse `TKey` can be string or object. I'm not sure the best way to write that, I could imagine two other options for how that's listed in the table, having both listed vertically:

```cs
IDictionary<string, string>
IDictionary<string, object>
```

Or having an _OR_ in the value:

```cs
IDictionary<string, string|object>
```

I honestly don't know what would be more helpful for an outside reader.

**Comment by brnhensley** [comment]
One other TSE said he preferred 
```cs
IDictionary<string, string|object>
```
to 
```cs
IDictionary<string, string>
IDictionary<string, object>
```
in the two area's that `IDictionary<TKey, TValue>` appear. For what that's worth.

**Comment by brnhensley** [comment]
For what it's worth about the IDictionary question @jaffinito said he preferred `IDictionary<string, object>` or `IDictionary<string, TValue>` and stating `TValue` can be a string or object in the description

**Comment by rhetoric101** [comment]
To ensure that we get this work done, it is now tied to a docs Jira: NR-22855.

**Review by rhetoric101 — APPROVED** [review]
@brnhensley, thanks for take a look at this!

**Pull request merged**
