### PR TITLE
updated infra agent zip install docs

### PR DESCRIPTION
**Pull request by cristianciutea**
This PR will update the documentation for infra agent zip package installer. If a custom installation location is used on windows, the customer needs to se the proper permissions to that location.

### CODE REVIEW

**Comment by rhetoric101** [comment]
@cristianciutea, I just made a few small changes to the first sentence. If this looks OK, I can publish this.

**Comment by cristianciutea** [comment]
> @cristianciutea, I just made a few small changes to the first sentence. If this looks OK, I can publish this.



> @cristianciutea, I just made a few small changes to the first sentence. If this looks OK, I can publish this.

Thank you! It can be published

**Comment by cristianciutea** [comment]
> @cristianciutea, I just made a few small changes to the first sentence. If this looks OK, I can publish this.

Thank you! It can be published @rhetoric101

**Review by rhetoric101 — APPROVED** [review]
Let's merge this!

**Pull request merged**
