### PR TITLE
notifications-update-jan-23

### PR DESCRIPTION
**Pull request by Dani-Relic**
This contains an update for the Applied-Intelligence 'Notifications' docs

### CODE REVIEW

**Comment by nbaenam** [comment]
Hi @Dani-Relic, thank you for your PR! We'd like to know when this PR must be merged because you opened it as a draft. Besides, you need to sign the CLA. We can't merge a PR without signing the CLA. Thanks!!

**Comment by Dani-Relic** [comment]
> Hi @Dani-Relic, thank you for your PR! We'd like to know when this PR must be merged because you opened it as a draft. Besides, you need to sign the CLA. We can't merge a PR without signing the CLA. Thanks!!

Thanks. Yeah I just want to see that it compiles without errors before I'll submit for review

**Comment by Dani-Relic** [comment]
Hi @nbaenam  I've signed and the PR is ready for review. Thanks!

**Comment by nbaenam** [comment]
Hi @Dani-Relic. Where can I take the new screenshot you've added? I'm trying one.newrelic.com and staging-one.newrelic.com and I'm not able to have a similar one.

**Review by nbaenam — APPROVED** [review]

**Comment by nbaenam** [comment]
The [build](https://www.gatsbyjs.com/dashboard/34e708d2-68a1-48ca-b66f-d2604890b061/sites/a0b77314-cdea-4790-8fde-7d3457d590ce/builds/b29be260-9b34-41c0-b749-c962fbe99e39/details) has been done manually.

**Comment by nbaenam** [comment]
I've merged it although the license/cla required check fails, the @Dani-Relic has assured me through Slack that he has already signed this PR. I added a message in the _doc_eng_help_ channel and I've learned that this kind of thing sometimes happens I can merge it if I'm sure the person has signed the CLA.

**Pull request merged**
