### PR TITLE
feat: Added new integration document for coreDNS (Kubernetes)

### PR DESCRIPTION
**Pull request by pkudikyala**
**Jira Ticket:** https://new-relic.atlassian.net/browse/NR-277321
**Description:** Added new integration document for coreDNS (Kubernetes)

Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Comment by nbaenam** [comment]
HI @pkudikyala, we already have a page on our docs site for coreDNS: https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/integrations-list/core-dns-integration/. Do you want to move it inside the Kubernetes section? If that's the case, could I ask you why and who asked you this? Thanks a bunch!

**Comment by pkudikyala** [comment]
> HI @pkudikyala, we already have a page on our docs site for coreDNS: https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/integrations-list/core-dns-integration/. Do you want to move it inside the Kubernetes section, add more content or modify anything? If you want to move it to other section, could I ask you why and who asked you this? Thanks a bunch!

Hi @nbaenam, yes, we already have CoreDNS documentation. However, CoreDNS can be integrated in two ways:

**CoreDNS (Kubernetes):**
The CoreDNS (Kubernetes) integration is completely new, which is why I raised a new integration document PR.

**CoreDNS (Prometheus):**
The CoreDNS (Prometheus) integration is an existing one, and we need to update its documentation in the next sprint. Previously, users had to install the Prometheus Remote Write agent and Prometheus Agent Mode agents. To simplify the integration steps for users, we can now utilize nri-Prometheus.

tagging @seemantk

**Comment by nbaenam** [comment]
Thanks for the clarification, @pkudikyala. I'll check in with @mangulonr on this. @mangulonr, should I add this new doc to the on-host integration list?

**Comment by mangulonr** [comment]
Hi @pkudikyala 

Thanks for providing more context.

The existing CoreDNS integration needs the [Prometheus Agent](https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/install-configure-prometheus-agent/install-prometheus-agent/#install-agent) (or you can forward the Prometheus metrics by your own to NR)  which is automatically installed as part of the K8s instrumentation [nri-bundle chart](https://github.com/newrelic/helm-charts/blob/master/charts/nri-bundle/README.md).

In your document, you're asking first to install the infrastructure agent, then the K8s integration. Why?
I didn't see any mention of nri-prometheus (which is the legacy Prom. instrumentation [now replaced by the Prom. agent](https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/install-configure-prometheus-agent/migration-guide/)).

Why do we need 2 different integrations?

**Comment by pkudikyala** [comment]
> Hi @pkudikyala
> 
> Thanks for providing more context.
> 
> The existing CoreDNS integration needs the [Prometheus Agent](https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/install-configure-prometheus-agent/install-prometheus-agent/#install-agent) (or you can forward the Prometheus metrics by your own to NR) which is automatically installed as part of the K8s instrumentation [nri-bundle chart](https://github.com/newrelic/helm-charts/blob/master/charts/nri-bundle/README.md).
> 
> In your document, you're asking first to install the infrastructure agent, then the K8s integration. Why? I didn't see any mention of nri-prometheus (which is the legacy Prom. instrumentation [now replaced by the Prom. agent](https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/install-configure-prometheus-agent/migration-guide/)).
> 
> Why do we need 2 different integrations?

Hi @mangulonr ,

Thanks for bringing this up. 

First of all, the existing integration steps are quite difficult to follow. By using nri-prometheus, we can easily gather these metrics. Additionally, the customer requested the ability to filter the entire dashboard based on the cluster. After doing some research, we found that we have not configured coredns to collect cluster-specific metrics, even though we are using Kubernetes.

Can I modify the [coredns integration](https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/integrations-list/core-dns-integration/) documentation, add two new sections:

**Using nri-prometheus:** This section will cover how to use nri-prometheus to meet the requirements outlined in the previous documentation.

**Using Kubernetes:** This section will detail how to use Kubernetes for metrics collection, including cluster-wide metrics.

**Comment by pkudikyala** [comment]
As per the @mangulonr suggestion, I'm closing this PR and updating the dashboard with the facet `cluster_name`.
Slack thread: https://newrelic.slack.com/archives/C070ZCB390D/p1718199664385259

**Pull request closed without merging**
