### PR TITLE
feat: OpenLIT Integration Documentation

### PR DESCRIPTION
**Pull request by amanagarwal042**
Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
   - This PR adds documentation on how users can use OpenLT for complete LLM Stack Observability (LLMs, VectorDBs, GPUs) and send the OTel native metrics and traces to New Relic. 
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
  - This doc is similar to the one added for Traceloop. For reference, OpenLIT is also referenced in the official OTel Blog on LLM Observability ([here](https://opentelemetry.io/blog/2024/llm-observability/))
* If your issue relates to an existing GitHub issue, please link to it.
  - No open issue
  
Question:
I have linked a pre-built dashboard too in the doc but wondering if the dashboard JSON needs to be added to this repo or not.

### CODE REVIEW

**Comment by nbaenam** [comment]
Hey @ally-sassman, this PR is related to OTEL, so I think you prefer to review it. Let me know if you don't do OTEL docs anymore. I just got back from vacation.

**Comment by nbaenam** [comment]
Hey @ally-sassman, I just realized that you're on vacation until the 20th, so I'll check it.

**Comment by nbaenam** [comment]
Hey @patcher9, do you work for NR?

**Review by nbaenam — APPROVED** [review]
Hi @patcher9, thanks for adding this! I've added some TW edits

**Comment by nbaenam** [comment]
Hey @patcher9, do you work for NR?

**Comment by nbaenam** [comment]
Hi @patcher9, I'll merge it when the eng team tests this new update.

**Comment by nbaenam** [comment]
This is the Eng ticket: NR-304719

**Comment by nbaenam** [comment]
Hey @patcher9, our engineers are reviewing it. I'll merge it when I have their approval ;-)

**Comment by shwartzm-NR** [comment]
Hi @patcher9,
Can we connect regarding adding in-platform integration with OpenLIT?

**Comment by konda-lavanya** [comment]
Hello 

We have Created a simple application using the code provided in the **[docs]( https://deploy-preview-18332--docs-website-netlify.netlify.app/docs/opentelemetry/get-started/openlit-llm-observability/openlit-llm-observability-intro/)**  And created a Dashboard using the example dashboard provided in **[this docs](https://docs.openlit.io/latest/connections/new-relic#dashboard)**. 

However, We see so much data missing when used this dashboard provided in docs, We did modify some queries to minimise the missing parts. Still, some parts as shown in pictures below are missing. 

**[Links](https://jsoneditoronline.org/#left=cloud.a6d4d836b8f14b648b65dce12afbdafc&right=cloud.86c5e13db7074951ab0404cb1c51d34d)** to comparing dashboard example provided in openlit and updated ones

We wanted to bring this to your notice and know if this is  the expected behaviour. 
Screenshot 2024-09-26 at 8 02 13 PM
Screenshot 2024-09-26 at 8 02 20 PM
Screenshot 2024-09-26 at 8 02 28 PM

**Comment by konda-lavanya** [comment]
Hello @patcher9, Looks like the dashboard is not updated in https://docs.openlit.io/latest/connections/new-relic#dashboard as a lot of data is missing. Please refer to images uploaded. 
Screenshot 2024-10-01 at 12 30 43 PM
Screenshot 2024-10-01 at 12 30 51 PM

Screenshot 2024-10-01 at 12 30 57 PM
Screenshot 2024-10-01 at 12 31 03 PM

**Comment by konda-lavanya** [comment]
Hey @patcher9 , I have re-tested with the updated query and there is only a minor thing missing, Some columns are missing in GenAI Requests table as shown in table. I've added the query change too, Please check. 


**Query provided in dashboard**

`SELECT timestamp, trace.id, gen_ai.operation.name AS 'Category', gen_ai.environment AS 'Environment', gen_ai.application_name AS 'Application', gen_ai.request.model AS 'Model', gen_ai.usage.cost AS 'Usage Cost', duration.ms AS 'Duration' FROM Span WHERE gen_ai.operation.name != 'vectordb' And gen_ai.operation.name != 'framework'`


**Updated Query**

`SELECT timestamp, trace.id, gen_ai.operation.name AS 'Category', gen_ai.environment AS 'Environment', gen_ai.application_name AS 'Application', gen_ai.request.model AS 'Model', gen_ai.usage.cost AS 'Usage Cost', duration.ms AS 'Duration' FROM Span WHERE gen_ai.operation.name != 'vectordb' And gen_ai.operation.name != 'framework' And `telemetry.sdk.name` = 'openlit'`


Screenshot 2024-10-07 at 6 13 47 PM

**Comment by konda-lavanya** [comment]
Adding screenshots of dashboard created for record:
Screenshot 2024-10-07 at 6 14 14 PM
Screenshot 2024-10-07 at 6 14 20 PM
Screenshot 2024-10-07 at 6 14 29 PM
Screenshot 2024-10-07 at 6 14 35 PM
Screenshot 2024-10-07 at 6 14 45 PM

**Comment by ally-sassman** [comment]
@nbaenam Checking in on this - is this ready to be merged?

**Comment by konda-lavanya** [comment]
This looks good to go. Thank you @patcher9 for all the updates.

**Comment by nbaenam** [comment]
Hey @patcher9, the PR is ready to merge now, but could you sign the CLA again, even if you have signed it in the past? We can't merge it without signing the CLA. Thanks!

**Comment by nbaenam** [comment]
No, I don't mind, @patcher9

**Pull request closed without merging**
