### PR TITLE
Update node compatibility

### PR DESCRIPTION
**Pull request by LizBaker**
original PR: https://github.com/newrelic/docs-website/pull/16605

### CODE REVIEW

**Comment by svetlanabrennan** [comment]
netlify build

**Comment by svetlanabrennan** [comment]
Before: https://docs.newrelic.com/docs/apm/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent/

After (preview): https://deploy-preview-16628--docs-website-netlify.netlify.app/docs/apm/agents/nodejs-agent/getting-started/compatibility-requirements-nodejs-agent/

Fixes issue https://github.com/newrelic/node-newrelic/issues/2082

**Review by jsumners-nr — APPROVED** [review]
Looks good to me.

**Review by mrickard — APPROVED** [review]

**Comment by svetlanabrennan** [comment]
@LizBaker We have two approvals from my team on this PR. Please let me know when you can have this merged. Thanks so much!

**Review by homelessbirds — APPROVED** [review]

**Pull request merged**
