### PR TITLE
feat(Browser): Session traces

### PR DESCRIPTION
**Pull request by barbnewrelic**
For NR-23767. WIP

Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Comment by CherylFrankenfield** [comment]
@barbnewrelic Thank you! 

1.The bottlenecks part is a bit vague, looks like that's how it was before. I wonder whether we can be more specific here and/or just take it out?

LCP
_Core Web Vitals: The time from when the request began to when the page content finished loading._

2.LCP is the render time of the largest content element visible in the viewport.
Here’s the data dictionary link: https://docs.newrelic.com/attribute-dictionary/?event=PageViewTiming&attribute=largestContentfulPaint

3.Since we introduced a new attribute to this UI, sessionTraceId, can we add a line or two about that? 
https://docs.newrelic.com/attribute-dictionary/?event=AjaxRequest&attribute=sessionTraceId

Thanks!

**Review by akristen — DISMISSED** [review]
Clear language, love how it's organized on the page! I have no questions and think the doc is good 2 go! :)

**Comment by barbnewrelic** [comment]
License checks are stuck across the board, so I'm closing then reopening this PR to see if that helps.

**Comment by barbnewrelic** [comment]
License check is stuck again and Gatsby appears to be spinning for no reason. Will try closing and reopening this PR. Again.

**Comment by barbnewrelic** [comment]
License.

**Review by akristen — APPROVED** [review]

**Comment by barbnewrelic** [comment]
Got the ok from peer editor and docs engineering to merge.

**Pull request merged**
