### PR TITLE
fix(discovery): fix docs related to discovery

### PR DESCRIPTION
**Pull request by paologallinaharbur**
The docs related to autodiscovery had some issues:
 - the syntax was wrong: ${'${discovery.ip}'}
 - the integration example was a mix of Config format v3 and V4 (`command:` and name of integration not matching binary)

### CODE REVIEW

**Comment by akristen** [comment]
Hi @paologallinaharbur ! Please reach out to the docs hero when this PR is ready for a review and merge. Thanks!

**Comment by paologallinaharbur** [comment]
@sigilioso Can you take a look as well?

**Review by nbaenam — APPROVED** [review]
Hi @paologallinaharbur, thank you for adding these fixes! LGTM!

**Review by sigilioso — APPROVED** [review]
LGTM

**Pull request merged**
