### PR TITLE
Add FedRAMP pdf

### PR DESCRIPTION
**Pull request by LizBaker**
### Give us some context

This adds a PDF we need to link to from a doc. We're still figuring out how we want to deal with adding PDFs but for now it's going in the repo (https://github.com/newrelic/docs-website/issues/2063)
By adding the file to the directory that the doc is in we can simply link to it with `[link](filename.pdf)` in that doc, so in this case `[FedRAMP PDF](New-Relic-FedRAMP-Customer-Responsibility-Matrix.pdf)` from within regulatory-audits-new-relic-services.mdx

### CODE REVIEW

**Comment by mmfred** [comment]
@barbnewrelic - I believe you're working on this. I'm going to leave this for you to address.

**Comment by LizBaker** [comment]
also @barbnewrelic feel free to use this same branch to add the link where you need it. There is one caveat and it's that when you run it locally you'll get a 404 upon clicking the link. if you refresh that 404 page it will then load the pdf. 

this _wont_ happen once its live (and the PR preview will work correctly as well), it's just something that doesn't quite load with a local build

**Review by nr-kkenney — APPROVED** [review]
lgtm

**Comment by jpvajda** [comment]
Confirming with the Docs Team this is OK to merge.

**Pull request merged**
