### PR TITLE
chore: update ruby agent configuration documentation for 8.0 release

### PR DESCRIPTION
**Pull request by kaylareopelle**
### Give us some context

* What problems does this PR solve?
The configuration documentation needed further updates for the Ruby Agent's 8.0 release. 

* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.

* If your issue relates to an existing GitHub issue, please link to it.
Relates to the recently merged PR: https://github.com/newrelic/docs-website/pull/4019 

### Are you making a change to site code?
No.

If you're changing site code (rather than the content of a doc), please follow
[conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

### CODE REVIEW

**Comment by kaylareopelle** [comment]
we just noticed an issue during our internal review. standby!

**Comment by kaylareopelle** [comment]
Fix has been made and pushed! Maybe the build will work this time 🤞

**Comment by barbnewrelic** [comment]
@kaylareopelle  Can you please take a look at line 1205? It was originally enclosed in a single backtick and I thought that might be the problem, so I changed it to three backticks. But that didn't work either. Asked a couple of folks on my team and they think that entire block of text enclosed in backtick might be too much for a row in a table to handle. Maybe you could edit it down into something meaningful to readers but not so long? Thanks!

**Review by barbnewrelic — APPROVED** [review]
Thanks so much for tracking down the blocker!

**Comment by kaylareopelle** [comment]
Thanks for your patience, persistence and support! 

Your hunch was right -- that long line had some issues. It used the triple backticks for a code block instead of the one-liner code snippet syntax. That didn't play well with the `<td>`.

**Pull request merged**
