### PR TITLE
EP-1704 Improve definition for update tags:

### PR DESCRIPTION
**Pull request by vetusbs**
### Tell us why
We had a complain about the documentation, since it was suggesting that one single tag could be added. Now the documentation is clearer, so you cannot just update a tag. When you update tags, you update the whole set.

### CODE REVIEW

**Comment by jerelmiller** [comment]
Thanks for submitting this PR @vetusbs! I'm labeling this PR as on hold so that we don't merge it before our final migration, otherwise these changes will get lost.

**Comment by vetusbs** [comment]
> Thanks for submitting this PR @vetusbs! I'm labeling this PR as on hold so that we don't merge it before our final migration, otherwise these changes will get lost.

Do we have an estimated time for this PR to be merged? 
Don't know why the licence still apears as not signed... I did it. any hint?

**Comment by jerelmiller** [comment]
I'd like to get a review from the docs team (cc @austin-schaefer, @mmfred) on this. We just did our final migration today and we launch March 1st. At the very latest, early next week.

Seems the CLA has been having weird troubles lately. Another contributor ran into the same issue. I've got a thread open with our open source team about this. For now, don't worry about it.

**Review by mmfred — APPROVED** [review]
I made a small edit. Otherwise, looks good.

**Comment by jerelmiller** [comment]
Thanks @mmfred! I see no reason to wait on this change, so I'll go ahead and merge

**Pull request merged**
