### PR TITLE
chore: add syntax highlighting

### PR DESCRIPTION
**Pull request by brnhensley**
Basically adds syntax highlighting to the PHP docs. No content changes other than that ans some typos

`.htaccess` files use some proprietary syntax that github and my code editor recognize with the `apache` identifier. I'm not sure if docs.newrelic.com will understand of it that needs to be added 

`nginx` is the same situation

Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Comment by brnhensley** [comment]
`apache` syntax does not work, but it's marked in a couple files now, it would be good if we could add that to our accepted languages

**Comment by brnhensley** [comment]
PR to add apache to languages we can add syntax highlighting for: https://github.com/newrelic/gatsby-theme-newrelic/pull/931

**Review by bradleycamacho — DISMISSED** [review]

**Comment by brnhensley** [comment]
Hey @bradleycamacho it looks like you approved my edits, but maybe it needs another approval since you merged in develop

**Review by jeff-colucci — APPROVED** [review]
Looks good, thanks for this!

**Pull request merged**
