### PR TITLE
feat(whats-new): post for new io partners

### PR DESCRIPTION
**Pull request by louisleungk**
What's new post for I/O partners who have contributed quickstarts between Oct and Dec 2021

Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Comment by rhetoric101** [comment]
@louisleungk, thanks for contributing this "What's new" post! Could you tell us when this should be published (date and rough time)?

**Comment by louisleungk** [comment]
@rhetoric101 - Could you publish it as soon as possible? Thank you!

**Review by daynaslord — APPROVED** [review]

**Comment by rhetoric101** [comment]
@louisleungk, have you seen the PMM editing suggestions? Can you make those changes? If you need any help, let me know.

**Review by paperclypse — APPROVED** [review]
Looked good to me in the Gatsby preview

**Pull request merged**
