### PR TITLE
Sort order: Metric API first in list of MELT APIs

### PR DESCRIPTION
**Pull request by austin-schaefer**
Tiny pedantic fix

### CODE REVIEW

**Review by paperclypse — APPROVED** [review]
Looks good!

**Comment by zuluecho9** [comment]
@austin-schaefer note that the probable reason that was in that order was because there were other Metric API docs towards the bottom of that category underneath.

**Comment by austin-schaefer** [comment]
@zuluecho9 Oops! Should we un-do it? To me it still seems weird to have it in ELTM order. 

Perhaps we should make Metric into a category?

**Comment by zuluecho9** [comment]
i think the deeper issue is how all those things are thrown in one category. Let's ignore it for now, prob fine.

**Pull request merged**
