### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by kairostcheck**
feat(whats-new): bulk eol

Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

7-15 bulk eol announcement supported by [this Explorers Hub post](url)https://discuss.newrelic.com/t/july-2022-end-of-life-announcements/188318

### CODE REVIEW

**Review by bradleycamacho — APPROVED** [review]

**Comment by bradleycamacho** [comment]
@jkinmonth @john-withers @aalfano7 can I get an approval to merge this in?

**Comment by bradleycamacho** [comment]
@jkinmonth @john-withers @aalfano7 reminder that I can't merge this in until I get approval :)

**Review by aalfano7 — CHANGES_REQUESTED** [review]
We need to change the bit about adding a comment, because you cannot add comments in What's New. This must have just been copied over from the Explorers Hub post. I suggest updating this sentence to:

If you have questions or concerns, please comment on the [Explorers Hub post linked here](https://discuss.newrelic.com/t/july-2022-end-of-life-announcements/188318), or reach out to your account management team.

**Comment by kairostcheck** [comment]
Bradley, can you help me understand why I got this run failed notice?

Thanks in advance,

Kai

---------- Forwarded message ---------
From: kairostcheck ***@***.***>
Date: Fri, Jul 29, 2022 at 8:18 AM
Subject: [kairostcheck/docs-website] Run failed: Check status of
translation jobs - develop (bf2e030)
To: kairostcheck/docs-website ***@***.***>
CC: Ci activity ***@***.***>



[image: GitHub] [kairostcheck/docs-website] Check status of translation
jobs workflow run

  Check status of translation jobs: All jobs have failed

View workflow run
<https://github.com/kairostcheck/docs-website/actions/runs/2760555388>

[image: Fetch translated content]

*Check status of translation jobs* / Fetch translated content
Failed in 2 minutes and 9 seconds
[image: annotations for Check status of translation jobs / Fetch translated
content] 1
<https://github.com/kairostcheck/docs-website/actions/runs/2760555388>
[image: Fetch machine translated content]

*Check status of translation jobs* / Fetch machine translated content
Failed in 1 minute and 55 seconds
[image: annotations for Check status of translation jobs / Fetch machine
translated content] 1
<https://github.com/kairostcheck/docs-website/actions/runs/2760555388>



—
You are receiving this because this workflow ran on your branch.
Manage your GitHub Actions notifications
<https://github.com/settings/notifications>


GitHub, Inc. ・88 Colin P Kelly Jr Street
<https://www.google.com/maps/search/88+Colin+P+Kelly+Jr+Street++San+Francisco,+CA+94107?entry=gmail&source=g>
・San Francisco, CA 94107
<https://www.google.com/maps/search/88+Colin+P+Kelly+Jr+Street++San+Francisco,+CA+94107?entry=gmail&source=g>

**Comment by bradleycamacho** [comment]
Hey @kairostcheck that's just one of our translation checks. That is safe to ignore, no worries!

**Pull request merged**
