### PR TITLE
Jhagan pre sko data gov improvements

### PR DESCRIPTION
**Pull request by Rilsta**
Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
Fix broken links and add clarity
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Review by bradleycamacho — DISMISSED** [review]

**Comment by JimHagan** [comment]
@Rilsta glad you found all of those links.  That's more than I had.  I didn't know if the standard was to use absolute path on the docs site.

**Comment by JimHagan** [comment]
@bradleycamacho So for clarification relative links is the standard?

**Review by JimHagan — APPROVED** [review]

**Review by JimHagan — APPROVED** [review]

**Review by JimHagan — APPROVED** [review]
Everything looks good now after Bradley's adjustment to the links to be relative.

**Comment by bradleycamacho** [comment]
@JimHagan no worries, we use relative links whenever we link within the docs site. You can find more info in our style guide: https://docs.newrelic.com/docs/style-guide/formatting/hyperlinks

**Pull request merged**
