### PR TITLE
Added a section on how to test webhooks without writing code

### PR DESCRIPTION
**Pull request by ankitjaininfo**
## Give us some context

* _What problems does this PR solve?_ :  
  * Improved the purpose of webhooks
  * Improved the webhook notifier section, so that devs can quickly try out webhook payloads. Many developers (like me) do not understand how to start development against a webhook. This improvement shall help them. 
  * Fixed typos.
* _Add any context that will help us review your changes such as testing notes, links to related docs, screenshots, etc.:_ Not needed
* _If your issue relates to an existing GitHub issue, please link to it._ : N/A

### CODE REVIEW

**Comment by zuluecho9** [comment]
@ankitjaininfo Sorry, Ankit: are you a New Relic employee? I couldn't find out whether that was the case. Either way, thank you.

**Comment by ankitjaininfo** [comment]
@zuluecho9 - I have signed CLA

**Comment by zuluecho9** [comment]
thanks a lot @ankitjaininfo !

**Comment by ankitjaininfo** [comment]
You are welcome @zuluecho9. Thank you for correcting some typos and narration.

**Pull request merged**
