### PR TITLE
fix: update incorrect Android API name

### PR DESCRIPTION
**Pull request by cthomas-newrelic**
`withBuildVersion` does not exist in the Android SDK. The correct method name is `withApplicationBuild`.

Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
A customer reported tis inconsistence through a support call. Misnamed API method. Verified this does not occur with iOS agent docs.

* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.

* If your issue relates to an existing GitHub issue, please link to it.

sidekick @ndesai-newrelic

### CODE REVIEW

**Review by ndesai-newrelic — APPROVED** [review]

**Review by jeff-colucci — DISMISSED** [review]

**Review by jeff-colucci — APPROVED** [review]

**Comment by cthomas-newrelic** [comment]
@jeff-colucci I wonder if you could look at another formatting issue? It seems the markdown anchor does not need the "#" label. For example, I see `Kotlin [#kotlin]` for the Kotlin example.  The same applies to other sections.

**Comment by jeff-colucci** [comment]
@cthomas-newrelic Which areas are you seeing this in? I checked the build preview file and I didn't see anything, but it's completely possible I'm looking in the wrong place

**Comment by cthomas-newrelic** [comment]
@jeff-colucci ok, that's weird. I don't see it now. operator error perhaps. It was in https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile/mobile-sdk/set-application-build-number/

**Review by jeff-colucci — APPROVED** [review]

**Comment by jeff-colucci** [comment]
@cthomas-newrelic No problem, sometimes the preview builds are like that. I've re-reviewed and everything looks good so I'm going to go ahead and publish!

**Pull request merged**
