### PR TITLE
Fix image sizing on ALL images site-wide

### LINKED ISSUE #728: Fix the OVERWHELMING docker image + consider transparent background images for these pages
### Description

On a couple of pages, the icons have gone a little haywire in migration. Specifically, the docker icon is huge compared to the others, and then I'm also unsure if the plan is for the icons and labels to be in one big list. 

as a bonus if we can also use transparent background images here, that would be ideal, preferably svgs. 

### Steps to reproduce

1. Go to https://docs-preview.newrelic.com/docs/logs/enable-log-management-new-relic/enable-log-monitoring-new-relic/forward-your-logs-using-infrastructure-agent#install 
2. OR https://docs-preview.newrelic.com/docs/infrastructure/install-infrastructure-agent/linux-installation/install-infrastructure-agent-linux#install-agent
3. See error and compare to this nice layout: https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/linux-installation/install-infrastructure-monitoring-agent-linux#install-agent

Screen Shot 2021-02-02 at 5 41 27 PM

### PR DESCRIPTION
**Pull request by jerelmiller**
Closes #728 

# Description

Fixes image sizing on ALL images site-wide. This PR specifically:

* Maintains custom image sizes during the migration by wrapping markdown images with a new `ImageSizing` component
* Detects whether the image is an inline or block image. If it is an inline image, it applies the proper spacing/styling to accomodate
* Handles images that are passed as JSX to props other than children. Previously these images were dropped
* Adds imports for images used as JSX props
* Ensures images used for collapser titles are downloaded

## Screenshots

**Before**

Screen Shot 2021-02-10 at 5 24 01 PM

Screen Shot 2021-02-10 at 5 24 37 PM

Screen Shot 2021-02-10 at 5 25 21 PM

Screen Shot 2021-02-10 at 5 25 49 PM

**After**

Screen Shot 2021-02-10 at 5 24 19 PM

Screen Shot 2021-02-10 at 5 24 46 PM

Screen Shot 2021-02-10 at 5 25 29 PM

Screen Shot 2021-02-10 at 5 24 16 PM

### CODE REVIEW

**Comment by roadlittledawn** [comment]
This is looking perdy good to me! Nothing askew jumping out at me. One question: when using an image in a collapser title, the image must be imported in the .mdx file and it uses the `` tag in the `title` prop right?

**Review by roadlittledawn — APPROVED** [review]
:shipit:

**Comment by jerelmiller** [comment]
@roadlittledawn to answer your question, yes! Unfortunately markdown is not parsed when used as a prop, so we have to use the actual `` tag like you said. It seems this is not used all that often, so I felt it was a good trade off.

**Comment by jerelmiller** [comment]
Closing, then reopening to try and trigger the build validation

**Review by zstix — APPROVED** [review]

**Pull request merged**
