### PR TITLE
Screenshot info can be added - Update use-rabbitmq-or-jms-message-que…

### PR DESCRIPTION
**Pull request by LakshmisNR**
Suggest to add screenshot and what need to be expected 

In which cases the Out of box feature is not supported like for console app  it is not supported, And when it is supported like  Servlet-based, built on top of SpringBoot. Web based is supported 

What to expect is not clear as a part of this feature coverage

### CODE REVIEW

**Comment by nbaenam** [comment]
Hi @LakshmisNR, could I know the instance where you took the screenshot? Thanks!

**Comment by LakshmisNR** [comment]
The impersonation link is mentioned in the Slack thread I shared with
you. I took screenshot from that environment
Regards
Lakshmi S,
Global Technical Hub
***@***.*** | +91-8050474052

**Comment by nbaenam** [comment]
> 

Hi, I can't see a message for me in Slack. Can you check it, please?

**Comment by LakshmisNR** [comment]
[image: image.png]
Regards
Lakshmi S,
Global Technical Hub
***@***.*** | +91-8050474052

**Review by nbaenam — APPROVED** [review]
Thank you for the update! I've added a minor modifications

**Comment by nbaenam** [comment]
HI @LakshmisNR, could you please sign the license agreement (CLA) on GitHub?

**Pull request merged**
