### PR TITLE
July 28: What's new: Add files via upload

### PR DESCRIPTION
**Pull request by ymirelesNewRelic**
From @zuluecho9: I reviewed this and made some edits, should be good to go morning of July 28. 

EOL(whats-new): TLS 1.2 requirement

Specify the date and the time window when it should be published: morning, July 28th 2022.

## Give us some context
Transport Layer Security (TLS) New Relic will be updating the TLS requirements for all endpoints to a minimum of version TLS 1.2 or above effective October 24, 2022.

### CODE REVIEW

**Review by ymirelesNewRelic — COMMENTED** [review]
ok with the changes

**Review by ymirelesNewRelic — COMMENTED** [review]
Made a mistake on the " releaseDate: '2022-07-14' " the correct date is 2022-07-28

**Comment by aalfano7** [comment]
All good from the PMM review side!

**Review by aalfano7 — APPROVED** [review]
I would maybe change "we'll update our Transport Layer Security..." to "we're updating our Transport Layer Security.." just so the verb matches the title, but other than that I think it's fine.

**Review by barbnewrelic — APPROVED** [review]
This has been approved by the PMMs so OK to merge this PR on 07-28-2022.

**Pull request merged**
