### PR TITLE
fix mobile SDK examples, syntax and Description

### PR DESCRIPTION
**Pull request by ndesai-newrelic**
Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Comment by ally-sassman** [comment]
@ndesai-newrelic Let me know when this is ready for my review

**Comment by ndesai-newrelic** [comment]
@ally-sassman it is already done

**Review by ghost — APPROVED** [review]

**Comment by ally-sassman** [comment]
@ndesai-newrelic Can you sign the CLA with your other Github account (Nisarg Desai)?

**Comment by ally-sassman** [comment]
Duplicate here to address CLA issues: https://github.com/newrelic/docs-website/pull/14378/files

**Comment by akristen** [comment]
Archiving this PR since other PR is merged + this one is closed

**Pull request closed without merging**
