### PR TITLE
feat(Pixie): Add Upgrade instructions.

### PR DESCRIPTION
**Pull request by htroisi**

### CODE REVIEW

**Comment by htroisi** [comment]
Could whomever triages this PR, add @nserrino as a blocking reviewer? Thanks!

**Comment by barbnewrelic** [comment]
@htroisi  We do not have @nserrino listed in our GitHub reviewers. Could you please confirm with that person what is their correct spelling? Then we'll add them to the required reviewers. Thanks!

**Comment by htroisi** [comment]
Hi @barbnewrelic - @nserrino isn't an official reviewer, but I'd like her to take a look at this PR before it gets merged (since she requested these changes).

**Review by nserrino — APPROVED** [review]
lgtm

**Pull request merged**
