### PR TITLE
Whats new 03 22 popular prebuilt dashboards section

### PR DESCRIPTION
**Pull request by JasonNg22**
Hello! Requesting to please have this published on the morning of 3/22 (Wednesday)

### CODE REVIEW

**Review by kupsand — COMMENTED** [review]
Your images need proper formatting. Example:

Choose a specific data source to drill down into what's contributing the most to your data ingest consumption.

**Comment by JasonNg22** [comment]
I've edited the markdown file to correct the image formatting errors. Please let me know if there are still any issues regarding them, thank you!

**Review by kupsand — DISMISSED** [review]
Looks excellent - approved.

Kevin Downs, New Relic PMM

**Comment by rhetoric101** [comment]
I am temporarily closing this PR to kick off another build when I reopen it.

**Review by aalfano7 — DISMISSED** [review]

**Comment by aalfano7** [comment]
Hi @rhetoric101, thank you for fixing the date! Should I submit another approval, or are we all set here?

**Comment by rhetoric101** [comment]
@aalfano7 I think we're ok with the date. I just made some additional changes, but I'm having some trouble getting the first image to appear in my local instance. I'll keep troubleshooting.

**Review by rhetoric101 — APPROVED** [review]
@JasonNg22 thanks for adding this post! I removed the spaces in the images to get them to appear and also made a few other small changes based on our style guide.

**Comment by JasonNg22** [comment]
Thank you @rhetoric101 !

**Pull request merged**
