### PR TITLE
Second kafka pr for issue 1123

### LINKED ISSUE #1123: Kafka monitoring pages did not migrate correctly
(rewritten by Austin)

This doc was in the manual-edits folder, which has caused the migration script to behave a bit weirdly. Two clamshells ("JMX connection errors" and "Kerberos authentication failing") went missing. Compare:

* Actual: https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/kafka-monitoring-integration
* Expected version (on old Drupal site): https://docs-dev.newrelic.com/docs/integrations/host-integrations/host-integrations-list/kafka-monitoring-integration

This doc was also in the manual edits folder, and may have issues too

* https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/enable-serverless-monitoring-aws-lambda-legacy/

## Action items

1. Compare the docs.newrelic.com and docs-dev.newrelic.com versions of:
    * https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/enable-serverless-monitoring-aws-lambda-legacy/
    * https://docs-dev.newrelic.com/docs/integrations/host-integrations/host-integrations-list/kafka-monitoring-integration
2. Look for any issues or missing content
3. If you find any, manually fix the docs

### PR DESCRIPTION
**Pull request by rhetoric101**
### Tell us why

The migration from Drupal had dropped several changes in the Kafka doc. In a previous [PR] (https://github.com/newrelic/docs-website/pull/1388), I had restored the missing "preparation" section that was missing, but I overlooked two troubleshooting sections further down in the document. 

This PR is to restore those two troubleshooting sections:
* JMX connection errors
* Kerberos authentication failing

Closes #1123

### CODE REVIEW

**Comment by rhetoric101** [comment]
@gsanchezgavier, could you confirm that I added all the remaining sections to this Kafka doc?

**Comment by gsanchezgavier** [comment]
sorry for the delay , yes this is it thanks!

**Comment by rhetoric101** [comment]
REVIEWER: You can compare these restored sections with the Drupal site.

**Comment by urbiz-nr** [comment]
I've compared the Drupal version (dev) and this new one and they're the same now, good job! You may merge @rhetoric101 !

**Pull request merged**
