### PR TITLE
Create a new alerts doc for OpenTelemetry best practices

### PR DESCRIPTION
**Pull request by rhetoric101**
We need a new doc in OpenTelemetry best practices that does the following:

* Explains how to create an alert.
* Explains how to find a list of current alerts.

To facilitate this work, we need to split up the best practices guide into individual docs and create a new taxonomy level.

### CODE REVIEW

**Comment by rhetoric101** [comment]
@paperclypse, I thought I'd request a review via CodeStream. Let me know if you have time to check this out. Here's what I did in this, but I'm mostly interested in your feedback on the new alerts doc for OpenTelemetry.


* Divided the best practices guide into individual docs.
* Added a new alerts doc just for OpenTelemetry.

**Review by paperclypse — APPROVED** [review]
I left a bunch of comments on CodeStream. Looks good enough to publish! Many of my comments could be a fast follow, I think.

**Review by paperclypse — APPROVED** [review]
Looks good! I think it's time to roll this out :)

**Review by barbnewrelic — DISMISSED** [review]
@rhetoric101  I added a few questions and comments via CodeStream, but TBH, I think this is good to go. What a comprehensive and digestible collection of reference material this is! Congrats!

**Pull request merged**
