### PR TITLE
Update hipaa-readiness-new-relic.mdx

### PR DESCRIPTION
**Pull request by jjang-nr**
Making slight tweaks to clarify data localization restrictions .

### Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### Are you making a change to site code?

If you're changing site code (rather than the content of a doc), please follow
[conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

### CODE REVIEW

**Comment by rhetoric101** [comment]
@jjang-nr, I'll take a look at this PR. In the meantime, have you signed our contributors license agreement?

**Comment by jjang-nr** [comment]
Hi Rob, I work for New Relic as an employee. Do I still need to sign the
CLA if I, in my capacity as a New Relic employee, am acting on New Relic's
behalf anyways?

Joseph

--
Joseph Jang
Senior Legal Counsel, Product and Privacy


*Confidentiality Notice:*  This e-mail, including all attachments, is
confidential information of New Relic, Inc. and may constitute
attorney-client privileged communication. If the reader of this e-mail is
not the intended recipient or its authorized agent, the reader is hereby
notified that any dissemination, distribution or copying of this e-mail is
prohibited without the express consent of New Relic. If you have received
this e-mail in error, please notify the sender by replying to this message
and delete this e-mail immediately.

**Review by rhetoric101 — APPROVED** [review]
@jjang-nr, these changes look good! Thanks for keeping this up to date!

**Comment by rhetoric101** [comment]
@jjang-nr, yes, I'm afraid everyone who contributes, inside or outside the company, needs to sign the agreement.

**Comment by jjang-nr** [comment]
Signed. Thank you!

--
Joseph Jang
Senior Legal Counsel, Product and Privacy


*Confidentiality Notice:*  This e-mail, including all attachments, is
confidential information of New Relic, Inc. and may constitute
attorney-client privileged communication. If the reader of this e-mail is
not the intended recipient or its authorized agent, the reader is hereby
notified that any dissemination, distribution or copying of this e-mail is
prohibited without the express consent of New Relic. If you have received
this e-mail in error, please notify the sender by replying to this message
and delete this e-mail immediately.

**Comment by rhetoric101** [comment]
@jjang-nr, I'm afraid that GitHub is balking about the contributors license. Could you try submitting that signature again to help me see if that's where the problem is?

**Review by rhetoric101 — APPROVED** [review]
@jjang-nr, these changes look good, and I think we're past the contributor license issue now!

**Comment by zuluecho9** [comment]
@rhetoric101 do you see any problem with just force-merging this and then asking deven about what the problem is? Just to get it out for now?

**Comment by rhetoric101** [comment]
@jjang-nr, I wonder if you signed the CLA using your GitHub Enterprise account instead of your personal, public GitHub account. That might be the issue.

In any case, it looks like I can override this and publish it.

**Comment by zuluecho9** [comment]
I'm just going to revert this and add the edited page back in on my own.

**Pull request merged**
