### PR TITLE
Rename "By condition and entity" to "By condition and signal"

### PR DESCRIPTION
**Pull request by jcowan-at-newrelic**
**_Work in Progress_**

### Tell us why

> Per PM, we are renaming "By condition and entity" to "By condition and signal" to better identify the true behavior of this feature. Each violation is identified by a unique "signal" that is made up of elements such as the account, policy, condition, entity itself and associated facets.

### Anything else you'd like to share?

> UI changes in progress

### Are you making a change to site code?

> no

### CODE REVIEW

**Comment by mmfred** [comment]
hi @jcowan-at-newrelic - Thanks for the changes. It looks like some of the wording on the image in that section should be updated as well. Instead of "Incident Preference by Condition and Target," should it say "Incident Preference by Condition and Signal"?

**Comment by jcowan-at-newrelic** [comment]
@mmfred Good catch! I checked out my fork and am finding other changes as well I will add to this PR. Will let you know

**Comment by jcowan-at-newrelic** [comment]
@mmfred I believe this is ready for review now

**Comment by mmfred** [comment]
Thanks for letting me know - someone from the docs team will review it asap.

**Comment by mmfred** [comment]
Looks great @jcowan-at-newrelic!  - apologies for the delay.

**Pull request merged**
