### PR TITLE
12/6 Afternoon - Android release notes and EOL updates for v6.9.1

### PR DESCRIPTION
**Pull request by ywang-nr**
* What problems does this PR solve? - Release notes and EOL updates for android agent v6.9.1

### CODE REVIEW

**Comment by ywang-nr** [comment]
@cthomas-newrelic @ndesai-newrelic for review

**Review by cthomas-newrelic — APPROVED** [review]

**Comment by ywang-nr** [comment]
@Doc Team, this PR is ready for your review. Our target release date is 11/14.

**Review by x8a — DISMISSED** [review]
Ready to go on Nov 14! 🚀

**Comment by ywang-nr** [comment]
@Doc team, please don't merge, I will let you know when we're ready again. Thank you.

**Comment by austin-schaefer** [comment]
@ywang-nr Moving to draft, let us know in #help-documentation if/when this should get moved back into the publication queue.

**Comment by rhetoric101** [comment]
This PR seems to be stuck, so I am temporarily closing it to trigger a new build.

**Review by rhetoric101 — APPROVED** [review]
@ywang-nr these changes look good. I am going to merge this now, and it will be published sometime after the noon hour today.

**Pull request merged**
