### PR TITLE
Add release notes for the .Net agent v10.2.0 .

### PR DESCRIPTION
**Pull request by vuqtran88**
Add release notes for the .Net agent v10.2.0 .

### CODE REVIEW

**Review by jaffinito — DISMISSED** [review]

**Comment by bradleycamacho** [comment]
Hi @vuqtran88 , could you sign the CLA by clicking the yellow button a few comments above this one? I can merge it in as soon as you do!

**Comment by vuqtran88** [comment]
> Hi @vuqtran88 , could you sign the CLA by clicking the yellow button a few comments above this one? I can merge it in as soon as you do!

I just did.

**Comment by vuqtran88** [comment]
Hi @bradleycamacho 
Could you merge the PR ?

**Review by rhetoric101 — APPROVED** [review]
@vuqtran88 sorry for the delay in publishing these release notes! They look good!

**Pull request merged**
