### PR TITLE
Remove auto index pages, most landing pages

### PR DESCRIPTION
**Pull request by roadlittledawn**
## Description

Removes auto index pages (and related code), and most landing pages. The landing page template is kept for now for some "overview" pages for time being (they will eventually turn into intro docs that use `docPage` template).

Updates nav YAML to not use `path` value, except for top level path AND leaf paths. Keeping the top level paths helps the `gatsby-source-nav` plugin determine what the nav menu should be for a MDX file page that's referenced in more than one nav YAML file.

Applies same file moves/deletions to `i18n`. Removed rogue directory in `i18n`.

Keeps script around for now that updated nav YAML and removed irreelvant paths.

Keeps shadowed `NavItem` component from theme for now due to fact that we had to keep top level paths around.

## Related issues / PRs
Closes https://github.com/newrelic/docs-website/issues/4226

### CODE REVIEW

**Comment by paperclypse** [comment]
Congrats @roadlittledawn! It built :)

**Comment by roadlittledawn** [comment]
@paperclypse heck yeah! and a cold build of 26min. decent improvement from 35-40 minutes. 

going to hold on this for the hoidays i think. a couple remaining outstanding things to look at. but we're close

**Comment by paperclypse** [comment]
@roadlittledawn Sounds good to me!

**Review by paperclypse — APPROVED** [review]
It looks good to me. Not sure who else needs to do a PR review on this? @roadlittledawn @zuluecho9?

**Comment by roadlittledawn** [comment]
i'll ask a Dev En eng to give it a review as well

**Comment by roadlittledawn** [comment]
funny enough i still see auto index pages, but i assume this is related to the Gatsby Cloud cache issue where old routes are not deleted. we may want to trigger a cache clean and rebuild once this is deployed.

example: https://build-d745b33f-46da-4c80-ae14-540b2fa2ea62.gtsb.io/docs/apm/new-relic-apm/getting-started/

**Comment by nr-kkenney** [comment]
latest build looks good: https://build-34078bc7-38fe-4b66-aeac-701ca2296c26.gtsb.io/docs/apm/new-relic-apm/getting-started

**Review by nr-kkenney — APPROVED** [review]

**Pull request merged**
