### PR TITLE
Create new-relic-ios-6084.mdx

### PR DESCRIPTION
**Pull request by NPunit**
https://source.datanerd.us/mobile-apps/rpm_ios/releases/tag/6.8.4

https://newrelic.slack.com/archives/C0MPP9KD2/p1733312778082909

Create release notes for app update 6.8.4

### CODE REVIEW

**Review by akashreddy-nr — APPROVED** [review]
Reran the Netlify Jobs, Approving the PR

**Comment by akashreddy-nr** [comment]
Netlify Preview -> https://deploy-preview-19489--docs-website-netlify.netlify.app/

**Review by sujitnewrelic — APPROVED** [review]
lgtm

**Comment by NPunit** [comment]
Could this be merged

**Pull request merged**
