### PR TITLE
Remove internal links - DOC-6637

### PR DESCRIPTION
**Pull request by urbiz-nr**
Work in progress

### CODE REVIEW

**Comment by urbiz-nr** [comment]
This is for DOC-6637.

**Comment by austin-schaefer** [comment]
Hey @urbiz-nr is this ready for review? Looks like there are a few merge conflicts and also saw a note that this is "Work in progress" in the PR description.

**Comment by urbiz-nr** [comment]
Can anyone have a quick look at this? Thanks!

**Comment by rhetoric101** [comment]
@urbiz-nr and @bradleycamacho, it looks like @austin-schaefer, had removed one of these files (edit-images.mdx), so we may want to just create a new branch from this one, and remove the edit-images.mdx that was added back in by this PR.

**Comment by rhetoric101** [comment]
@urbiz-nr, these changes looked good! I only had one question: Was src/content/docs/instrument-segments-c-sdk.mdx deleted?

**Comment by urbiz-nr** [comment]
@rhetoric101 - yes, src/content/docs/instrument-segments-c-sdk.mdx was deleted. I spoke to stakeholders and it wasn't relevant any more.

**Pull request merged**
