### PR TITLE
Highlight Infinite Tracing

### PR DESCRIPTION
**Pull request by rhetoric101**
We want to highlight Infinite Tracing as a recommended feature.

### CODE REVIEW

**Comment by beatface** [comment]
👍 thumbs up from me @rhetoric101

**Comment by barbnewrelic** [comment]
@rhetoric101  I know you didn't touch this part of the browser doc with your update, but this image looks a bit odd in Gatsby preview. Maybe because of the recent addition of a lightbox for images? https://docswebsitedevelop-rhspitchinfinitetracing1.gtsb.io/docs/browser/new-relic-browser/browser-pro-features/browser-data-distributed-tracing/#find-data

**Comment by barbnewrelic** [comment]
@rhetoric101  In the Language agents doc https://docswebsitedevelop-rhspitchinfinitetracing1.gtsb.io/docs/distributed-tracing/enable-configure/language-agents-enable-distributed-tracing/ , up at the top it no longer lists C SDK, but in other parts of the doc, C is still there. Intentional? Also, I'm wondering about the use of H4 but trust your judgment.

**Comment by barbnewrelic** [comment]
@rhetoric101  This image in the Android doc also is placed oddly. https://docswebsitedevelop-rhspitchinfinitetracing1.gtsb.io/docs/mobile-monitoring/new-relic-mobile-android/get-started/new-relic-android-and-dt/

**Review by barbnewrelic — DISMISSED** [review]
I wanted to make a cheeky comment that you should have a doc called "Distributed vs. Infinite Tracing, heads or tails!" But I shall refrain. :-) I put some comments on this PR's Conversation tab, but otherwise I think this is all fine and can merge whenever you and your SMEs are ready.

**Review by barbnewrelic — APPROVED** [review]
Everything looks great! CONGRATS!

**Pull request merged**
