### PR TITLE
Whats New Post for OTel K8s and Prom hosts

### PR DESCRIPTION
**Pull request by ancantele**
Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Whats New post for launch of OTel instrumented K8s and Prometheus instrumented hosts. 
Thanks Anitah

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Comment by ancantele** [comment]
Please let me know if you need anything. This Whats New post is for 07.23. Thanks Anitah

**Review by nbaenam — COMMENTED** [review]
Hey @ancantele, thank you for the update!! As I sent you in a DM, the screenshot included in this PR is missing and the license agreement (CLA) on GitHub needs to be signed. We can't merge this PR without signing the CLA. Thanks!

**Review by ancantele — COMMENTED** [review]
Hi there the title should be "Native support for open standards: OpenTelemetry instrumented Kubernetes and Prometheus instrumented hosts" 

This looks like it is missing some of the docs links.

**Comment by nbaenam** [comment]
Closing this PR because is duplicated: https://github.com/newrelic/docs-website/pull/18119

**Pull request closed without merging**
