### PR TITLE
feat(whats-new): Create AWS EKS Add-on post (Publish date tbd)

### PR DESCRIPTION
**Pull request by john-withers**
Warning: Actual publish date is TBD (tentatively 3/10), pending confirmation from AWS. Confirm with Sarah Leslie before publishing.

Additionally, please add forthcoming NerdBytes video into the post. Brad Schmitt will record this and provide to Kyle Jones.

### CODE REVIEW

**Comment by barbnewrelic** [comment]
@B1XR11L729w583adTl5899556EJ5322a This exact same Kubernetes post is in PR6144, which is scheduled to be released on Wed. March 2. Please confirm: Keep or delete the .md file in 6144? Thanks!

**Comment by rhetoric101** [comment]
I completed a basic edit, but we still need that NerdBytes video.

**Comment by barbnewrelic** [comment]
Update 03-09-22: SMEs requested to keep this post on hold for the time being. Video is ETA end of March but they will verify when all is good to go.

**Comment by rhetoric101** [comment]
@john-withers I am closing this because you want to make substantive revisions for a future PR.

**Pull request closed without merging**
