### PR TITLE
[Mobile-7472] Include AGP 7 updates

### PR DESCRIPTION
**Pull request by ywang-nr**
* What problems does this PR solve? - update document to include AGP 7 updates

### CODE REVIEW

**Comment by ywang-nr** [comment]
@cthomas-newrelic for review

**Comment by ywang-nr** [comment]
@homelessbirds for review

**Comment by ywang-nr** [comment]
Ready for review and go live for the doc team

**Review by paperclypse — APPROVED** [review]
Looks good to me, @ywang-nr!

**Pull request merged**
