### PR TITLE
Tweaking O4G Program Benefits section content and layout for clarity

### PR DESCRIPTION
**Pull request by nr-mschutt**
Tweaking content and layout for the O4G (nonprofit program) page for clarity

Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Comment by homelessbirds** [comment]
@nr-mschutt looks good! Please sign the CLA so I can get this merged in. Thanks!

**Comment by homelessbirds** [comment]
@nr-mschutt looks good! Please sign the CLA so I can get this merged in. Thanks!

**Comment by homelessbirds** [comment]
@nr-mschutt looks good! Please sign the CLA so I can get this merged in. Thanks!

**Comment by homelessbirds** [comment]
@nr-mschutt looks good! Please sign the CLA so I can get this merged in. Thanks!

**Review by x8a — APPROVED** [review]
Thanks for adding this info!

**Pull request merged**
