### PR TITLE
6/16 Whats new IBM MQ public preview integration

### PR DESCRIPTION
**Pull request by kupsand**
This is Kevin Downs - New Relic infrastructure PMM.

- Please post this What's New item on 6/16/2022

Thank you
Kevin Downs
kdowns@newrelic.com

### CODE REVIEW

**Comment by jkinmonth** [comment]
Reviewing now

**Review by jkinmonth — COMMENTED** [review]
Reviewed and made some edits for clarity.

**Review by jkinmonth — APPROVED** [review]
Approved with changes that I merged to this branch.

**Review by barbnewrelic — APPROVED** [review]
This will go live with morning merge today.

**Pull request merged**
