### PR TITLE
Lambda function not instrumented

### PR DESCRIPTION
**Pull request by keegoid-nr**
- Add troubleshooting steps for common issue due to two integrations.
- Include query we use to determine if a Lambda function is instrumented.
- Include links to relevant docs and resources.

### CODE REVIEW

**Comment by keegoid-nr** [comment]
I'd like to add @mrickard as a reviewer here.

**Review by mrickard — DISMISSED** [review]

**Comment by rhetoric101** [comment]
@keegoid-nr do we still need a review from mrickard?

**Comment by keegoid-nr** [comment]
> @keegoid-nr do we still need a review from mrickard?

@rhetoric101, @mrickard already approved this PR prior to the minor edits. It looks ready to go.

**Review by rhetoric101 — APPROVED** [review]
@keegoid-nr thanks for making this helpful contribution!

**Pull request merged**
