### PR TITLE
Update php-agent-compatibility-requirements.mdx for Yii2

### PR DESCRIPTION
**Pull request by razvanphp**
This is related to and should be merged after this MR: https://github.com/newrelic/newrelic-php-agent/pull/823

### CODE REVIEW

**Comment by rhetoric101** [comment]
Here's an update from the PHP team: "This is a community member that offered his help in adding support for Yii2 framework to PHP Agent. They submitted PR with code changes. However, it’ll take some time before their work can be accepted."

The PHP team will keep track of the two related PRs and let the docs team know when it's time for a review.

**Comment by razvanphp** [comment]
Hey, this should be merged now, as the functionality was released withing the PHP agent. Thanks!

**Comment by akristen** [comment]
I'm closing this PR, as the branch has been out of sync for several months. If these changes still need to be merged, please file a new PR and I'll add this work to our workflow

**Comment by razvanphp** [comment]
Seems this was handled in: https://github.com/newrelic/docs-website/commit/f126cc0983d4c881bd4ae6b866030f8acd1ad922

But I've submitted another MR for completion.

**Pull request closed without merging**
