### PR TITLE
(Publish with first build on 04/20/2023) Whats new mobile dashboard template variables

### PR DESCRIPTION
**Pull request by mvenkat5**
Publish 04/20 morning

I'm a PMM, this doesn't need PMM review. Thanks!

### CODE REVIEW

**Comment by nbaenam** [comment]
Hi @mvenkat5, the build has failed. The error is in the `learnMoreLink`. When I click the youtube link, it doesn't load and this is the message I get: `Video unavailable. This video is private`. Can you check it out, please? Thanks!

**Comment by mvenkat5** [comment]
@nbaenam oh no, thanks for flagging! working with the video team to fix that. will update you as soon as its fixed. thanks!

**Comment by mvenkat5** [comment]
@nbaenam the link has been fixed, can you try again please? thank you!

**Comment by nbaenam** [comment]
Hi @mvenkat5! yes! I'll try again when the build finishes. Thanks for the update!

**Review by rhetoric101 — APPROVED** [review]
@mvenkat5 thanks for adding this PR. We'll get it published on the 20th.

**Review by nbaenam — APPROVED** [review]

**Pull request merged**
