### PR TITLE
chore: wrap attributes in backticks

### PR DESCRIPTION
**Pull request by brnhensley**
Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Comment by brnhensley** [comment]
Adding one more commit to fix an italics issue on the live site.  The UI is showing `_Func<IReadOnlyDictionary<string,object>,string>_` instead of _Func<IReadOnlyDictionary<string,object>,string>_

image

making this a draft to see if my fix works

**Comment by brnhensley** [comment]
ok, that change worked, good to go

**Comment by rhetoric101** [comment]
@brnhensley, could you re-sign our CLA. Our legal team has made some changes that requires your signature again.

**Review by rhetoric101 — APPROVED** [review]
@brnhensley thanks for catching these issues and making some updates!

**Pull request merged**
