### PR TITLE
DOC-6656 guided install infrastructure

### PR DESCRIPTION
**Pull request by paperclypse**
This work is intended to make the guided install option a little more visible to readers.

### CODE REVIEW

**Comment by urbiz-nr** [comment]
Looking good so far!

**Comment by barbnewrelic** [comment]
The text looks ok from my localhost but the image doesn't display. See screenshot.

image

**Comment by barbnewrelic** [comment]
image

**Comment by paperclypse** [comment]
@barbnewrelic I fixed the image issue. Mind double-checking my work here? Thanks!

**Pull request merged**
