### PR TITLE
Update winservices-config.yml to match Github

### PR DESCRIPTION
**Pull request by tr002**
Current winservices-config.yml in docs page is outdated, mixes standard formatting  with legacy integration name. This edit updates the winservices-config.yml file content from the NR Winservices Github page.

Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Comment by rhetoric101** [comment]
@tr002, it looks like you need to sign the CLA in order for us to publish your changes. Also, are you employed by New Relic?That would help us label this PR.

**Comment by tr002** [comment]
Yes, work at New Relic, but haven’t found out how to sign the CLA.

**Comment by tr002** [comment]
Just signed CLA

**Review by rhetoric101 — APPROVED** [review]
@tr002, thanks for updating this YML example!

**Comment by rhetoric101** [comment]
I am temporarily closing this so I can reopen it to restart the linter check.

**Pull request merged**
