### PR TITLE
bump `@newrelic/gatsby-theme-newrelic` to 9.4.0

### PR DESCRIPTION
**Pull request by sunnyzanchi**

### CODE REVIEW

**Review by clarkmcadoo — APPROVED** [review]

**Comment by clarkmcadoo** [comment]
Mobile needs some attention:
Screenshot 2024-03-19 at 5 09 18 PM

**Comment by sunnyzanchi** [comment]
netlify build

**Comment by clarkmcadoo** [comment]
netlify build

**Review by LizBaker — DISMISSED** [review]

**Comment by clarkmcadoo** [comment]
netlify-build

**Comment by clarkmcadoo** [comment]
netlify build

**Comment by clarkmcadoo** [comment]
netlify build

**Review by LizBaker — APPROVED** [review]

**Review by clarkmcadoo — APPROVED** [review]

**Pull request merged**
