### PR TITLE
Update Gatsby theme

### LINKED ISSUE #964: Japanese header Free account button should send to Japanese Sign-up page
### Description

The Free account button on the Japanese header sends the reader to the English sign-up page and not the Japanese one.

### Steps to reproduce

1. Go to Japanese Docs home page
2. Click on Free account button
3. Link lands you on newrelic.com/signup

### Expected behavior

Link from Japanese header lands you on [https://newrelic.com/jp/signup](url)

### Screenshots

N/A

### Additional context

N/A

### Environment

N/A

### LINKED ISSUE #965: All Japanese sign-up/free account links throughout the Docs site need to send to Japanese sign-up page
### Description

All the links within the Japanese Docs site are currently sending the user to the US sign-up page instead of sending the user to the Japanese sign-up page page.

### Steps to reproduce

1. Go to /docs/telemetry-data-platform/ingest-manage-data/get-started/get-know-telemetry-data-platform
2. Toggle to Japanese
3. Click on [Sign-up] ([サインアップ]) in the Tip box.

### Expected behavior

The link on the Japanese docs site should send the user to: https://newrelic.com/jp/signup
This behavior should happen throughout the site. The translation process does not edit URL so if this could be done programmatically that would be best.

### Screenshots

N/A

### Additional context

N/A

### Environment

N/A

### LINKED ISSUE #1012: Link to language specific sites from the Japanese site in the global header and footer
### Description

Certain links across the docs site send the user to English properties while there are Japanese properties: newrelic.com, integrations page, etc.

### Steps to reproduce

1. clicking on the New Relic icon in the header leads to newrelic.com

### Expected behavior

Link sends user from Japanese doc site to Japanese doc site.

### Screenshots

N/A

### Additional context

It would be great to programmatically build re-directs so that if a Japanase property exist, we can automatically send the use to that property.

### Environment

N/A

### PR DESCRIPTION
**Pull request by jerelmiller**
### Tell us why

Update Gatsby theme to the latest to fix several issues addressed from the theme.
closes #1012 
closes #965
closes #964

### CODE REVIEW

**Comment by jmiraNR** [comment]
Hi @jerelmiller the footer Docs icon still sends to US site not the Japanese docs site.

**Comment by caylahamann** [comment]
hey @jmiraNR I'm the one who made those changes, let me see why that's happening!

**Comment by caylahamann** [comment]
found the reason, put up a PR in the gatsby-theme @jmiraNR

**Comment by jmiraNR** [comment]
Thank you @caylahamann.

**Pull request merged**
