### PR TITLE
What's new navigation

### LINKED ISSUE #287: [Docs Site UX] What's New navigation
## Description
We would like to add a link to the top-level navigation that takes the user to a page containing a list of all the What's New posts (#288 ).

When browsing the top-level What's New page, or any What's New post, the sidebar should contain links to all of the posts in a nested structure (like the rest of the site). The navigation content should contain the 10 most recent posts, and then "buckets" of expandable sections based on the distance from the current date:

```
Most recent post
2nd most recent post
3rd
4th
5th
6th
7th
8th
9th
10th
This Month <-- expandable
  post a
  post b
  ..
Last Month <-- expandable
  post c
  post d
  ..
Older <-- expandable
  post g
  post h
  ..
```

**TBD** on the exact breakpoints for what falls into each bucket.

This will be run by a `.yml` configuration file that will be automatically generated via a GH Action.

## Acceptance Criteria
* [ ] Top-level navigation updated to add a link for the new What's New page
* [ ] Function to generate a `src/nav/whats-new.yml` based on the posts and current date
* [ ] Ability to trigger the function on a regular interval to keep the sidenav up to date (GH Action)

## Screenshot(s)
Image from iOS

### PR DESCRIPTION
**Pull request by jerelmiller**
Closes #287 

## Description

Adds the navigation for the "What's new" pages. Also refactors the existing way we determine what nav to show into a GraphQL query by path. This will allow us to more easily create custom navs for other pages in the future.

## Screenshots

localhost_8000_whats-new (1)

### CODE REVIEW

**Comment by caylahamann** [comment]
@jerelmiller build failed 🤔

**Review by zstix — APPROVED** [review]
This is an awesome refactor 🎉

**Review by zstix — APPROVED** [review]
Not sure why Amplify isn't reporting this check as passing, but it works: https://pr-368.d1vx4w5vgyla4s.amplifyapp.com/whats-new

With only 9 posts, we don't get to see the other buckets, but this is looking 🔥 either way

**Comment by jerelmiller** [comment]
> With only 9 posts, we don't get to see the other buckets

That will be updated with #360!

**Pull request merged**
