### PR TITLE
[Product Partnerships] Amazon Elemental MediaConvert

### PR DESCRIPTION
**Pull request by rahul188**
Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Comment by homelessbirds** [comment]
Hi @rahul188 Thank you for submitting this! It looks like there were a lot of changes made to this doc. I'm curious about what motivated these changes? Has this integration fundamentally changed or were the instructions wrong to begin with?

**Comment by rahul188** [comment]
@homelessbirds, I have updated the docs based on current standards, requirements & updated metrics.
AWS Docs - https://docs.aws.amazon.com/mediaconvert/latest/ug/metrics.html

**Comment by homelessbirds** [comment]
@rahul188 but there are a lot of other changes beyond the metrics-- it looks like titles and headings have changed. Where can I find the current standards? Thank you!

**Comment by rahul188** [comment]
@homelessbirds, please find below URLS - 

- https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/amazon-inspector-monitoring-integration/
- https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/amazon-simpleworkflow-monitoring-integration/
- https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/amazon-timestream-monitoring-integration/
- https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/amazon-workspaces-monitoring-integration/

**Comment by rahul188** [comment]
@homelessbirds, I'm closing the PR, As we have reverted the entity.
PR - https://github.com/newrelic/entity-definitions/pull/1208

**Pull request closed without merging**
