### PR TITLE
DOC-6131: Lower-case "browser" everywhere it makes sense

### PR DESCRIPTION
**Pull request by austin-schaefer**
### Give us some context

Since the new pricing model launched, we no longer capitalize New Relic Browser as a product. Instead, it's a capability ("New Relic's browser monitoring" or "browser monitoring" or "browser agent" or similar).

We have a related jira in DOC-6131

### To-dos

- [x] Sweep for New Relic Browser
- [x] Sweep for just Browser in uppercase and change where appropriate
   * Note to future archaeologists: Changed lots of instances, but many instances are just atribute/event names.
- [x] Look for references to old Pro+SPA SKU
    * Ended up spinning this into a standalone jira DOC-7085
- [x] Check for links to https://newrelic.com/products
    * Done in #2926 
- [x] Consider sweeping for references to "enabling" rather than "installing" browser agent
- [x] Look for stray `''` in metaDescriptions
    * Turned out not to matter! See #2936 if you want more info

### Notes

- Did not update "original pricing/billing" docs
- Did not update docs for deprecated features like https://docs.newrelic.com/docs/browser/new-relic-browser/installation/monitor-amp-pages-new-relic-browser/
- Did not update any doc in the legal/licenses category

### Examples of pricing stuff

```Your New Relic Browser [subscription level](http://newrelic.com/browser-monitoring/pricing) and your [time picker](/docs/data-analysis/user-interface-functions/time-picker-setting-time-periods-view-data) settings determine what data you can view:```

### CODE REVIEW

**Comment by austin-schaefer** [comment]
Editing work is done, waiting for local/gatsby build to validate.

**Comment by austin-schaefer** [comment]
Local build is fine (minus some console noise) but Gatsby build failed. Pinging dev hero to see if I can get access to logs to figure out what's wrong.

**Comment by austin-schaefer** [comment]
@LizBaker set me straight on the thing causing gatsby build to fail!

**Comment by austin-schaefer** [comment]
Local build works, still waiting on gatsby/amplify

**Review by barbnewrelic — APPROVED** [review]
These all look fine. Thanks for the comprehensive sweep! I do worry about a PR that has 200+ files in it. Hope it merges successfully!

**Comment by austin-schaefer** [comment]
Fixed a merge conflict, waiting for it to rebuild

**Pull request merged**
