### PR TITLE
fix(Log management): LOGGING-6833: Grok types

### PR DESCRIPTION
**Pull request by bmcfeely**
We support typed attributes being extracted using Grok, but documentation does not make that clear

### CODE REVIEW

**Review by urbiz-nr — APPROVED** [review]
Thanks for adding this section, @bmcfeely!

**Review by urbiz-nr — APPROVED** [review]

**Comment by aswanson-nr** [comment]
Hey @bmcfeely! I dug a bit deeper into why this is failing to build and it has something to do with the `<code>` elements within the table. If you swap those out for backticks, you'll get the same behavior as you should with a `<code>` element.

**Comment by urbiz-nr** [comment]
Tried locally, works.

**Review by urbiz-nr — APPROVED** [review]

**Comment by bmcfeely** [comment]
@urbiz-nr Thank you so much! Sorry for not replying earlier.

**Pull request merged**
