### PR TITLE
fix(php_agent): Improve guidelines for per-directory INI config

### PR DESCRIPTION
**Pull request by mfulb**
Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?

The APM PHP agent team would like to refine the guidelines for using the newrelic_set_appname() API call, including removing a previous tip which is not recommended now.

### CODE REVIEW

**Review by paperclypse — APPROVED** [review]
Thanks for the PR, @mfulb! I rewrote your content slightly for clarity and moved that "another option" section a bit farther down the page where it seemed to make more sense to me.

**Comment by mfulb** [comment]
Thanks @paperclypse I will review the changes when the preview is available.

**Comment by paperclypse** [comment]
Here you go, @mfulb :) https://docswebsitedevelop-mfulbdocswebsitephpperiniupdat.gtsb.io/docs/apm/agents/php-agent/configuration/php-directory-ini-settings/

**Comment by mfulb** [comment]
Thanks that looks great.

**Pull request merged**
