### PR TITLE
Create insights-ios-1134.mdx

### PR DESCRIPTION
**Pull request by jvanmetre**
Updated end of life date to align with the new EOL of insights web.

### CODE REVIEW

**Comment by barbnewrelic** [comment]
It is possible this date may change again. I'd recommend holding off on publishing this revision for a few days while the Insights EOL team finalizes the date. We also have a pending PR to update all the Insights docs with the new date. Thanks for understanding!

**Review by dbarnesbrownNR — APPROVED** [review]
Looks good, thank you!

**Review by barbnewrelic — CHANGES_REQUESTED** [review]
@jvanmetre  I heard from Insights team earlier this morning that the date is now April 12. OK for me to just edit your PR and publish? Thanks for confirming!

**Comment by jvanmetre** [comment]
Hi @barbnewrelic, the iOS Insights version was released with an EOL date of the 11th, and we won't be changing that, so you can go ahead and publish this doc as is... thanks!

**Pull request merged**
