### PR TITLE
UI path consistency and fixes

### PR DESCRIPTION
**Pull request by austin-schaefer**
Changes a huge number of UI paths across the site. The goal is to create greater consistency and simplify our pathing sweep.

Key changes:

- Always puts bold outside the link element instead of inside
- Use `https` instead of `http` for all links into one.newrelic.com
- Removes all ` "Link opens in a new window."` attributes for more consistency across links
- Removes trailing slashes from links to one.newrelic.com
- Removes various duplicative asterisks
- Fixes various buggy or oddly formatted paths

Notes to reviewer:

- I've already spot-checked 1/3 (~120) of these files and I'm pretty confident I've caught any meaningful bugaboos
- For review, if you can just spot check 30–40 files that would be great

### CODE REVIEW

**Comment by Sporn** [comment]
> Changes a huge number of UI paths across the site for consistency to simplify our pathing sweep:
> 
> * Use `https` instead of `http`
> * Always puts bold outside the link element instead of inside
> * Removes various duplicative asterisks

**Comment by austin-schaefer** [comment]
Removing PMM request for review since WN doc changes are invisible to end user

**Review by paperclypse — APPROVED** [review]
what a doozy of a PR! Reviewed + Approved!

**Comment by paperclypse** [comment]
I got it building locally, so I expect that Gatsby Build Service check to go through.

**Pull request merged**
