### PR TITLE
chore: changes triage logic

### PR DESCRIPTION
**Pull request by jpvajda**
This PR changes the logic to move ALL issues and PRS to the content project board per @austin-schaefer request.

### CODE REVIEW

**Comment by austin-schaefer** [comment]
Looks good to me @jpvajda !

**Review by austin-schaefer — APPROVED** [review]

**Comment by austin-schaefer** [comment]
@jpvajda Not sure if this is fixed by this PR, but looks like the auto-triage job is still failing. https://github.com/newrelic/docs-website/pull/1238

**Comment by jpvajda** [comment]
@austin-schaefer  #1238 seems to failing on the github token which we did fix recently, so it's a different issue, I'm not sure why that is failing...

 also I wanted to check with a dev on this change to ensure it looks good from a GH action perspective.

**Comment by jpvajda** [comment]
@jerelmiller / @zstix

**Pull request merged**
