### PR TITLE
feat: create tabbed view on homepage

### PR DESCRIPTION
**Pull request by tabathadelane**
- add quicklaunchSlug to graphql query so MDX containers knowns which i18n body to render
- create ToggleSelector, ToggleView and Tooltip component
- toggle checks if user is logged in, if not their view is defaulted to the newUserView
- if the user has previously selected a preferred view, that setting is saved in the local storage and overrides the loggedin check

Testing behavior on staging: https://docs-dev.newrelic.com/

### CODE REVIEW

**Review by sunnyzanchi — APPROVED** [review]

**Comment by clarkmcadoo** [comment]
Screen Shot 2023-02-06 at 3 15 19 PM

getting this in incognito/safari/firefox, i was assuming it would go to the new mdx page?

**Comment by tabathadelane** [comment]
@clarkmcadoo Have you tried opening a new tab since this is session storage?

**Comment by clarkmcadoo** [comment]
> @clarkmcadoo Have you tried opening a new tab since this is session storage?

I have, multiple browsers and tabs.  Are you able to repro or is it something weird on my side maybe?

**Comment by tabathadelane** [comment]
Yeah, this is no longer working for me either

**Review by clarkmcadoo — APPROVED** [review]

**Review by sunnyzanchi — APPROVED** [review]

**Pull request merged**
