### PR TITLE
feat(php): dt by default

### PR DESCRIPTION
**Pull request by ZNeumann**
Adjust documentation to reflect that DT will be on by default.
Add additional clarity for troubleshooting.

### CODE REVIEW

**Comment by ZNeumann** [comment]
Hi, is there a change I need to make to get the build working?

**Comment by barbnewrelic** [comment]
The build timed out so I'm going to close and reopen this PR to see if that works.

**Comment by barbnewrelic** [comment]
The license check failed but that's not required so I'm going to go ahead and merge this PR.

**Review by barbnewrelic — APPROVED** [review]
Thanks for updating the docs!

**Pull request merged**
