### PR TITLE
added   hostNetwork: false

### PR DESCRIPTION
**Pull request by greenszpila**
Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Comment by akristen** [comment]
Hi @greenszpila. Can you sign the CLA so we can get this merged (once we fix the build)?

**Comment by greenszpila** [comment]
> 

signed

**Review by sigilioso — APPROVED** [review]
I think it makes sense to include that field value and comment

**Review by akristen — APPROVED** [review]
Thanks for updating and signing our CLA! :)

**Pull request merged**
