### PR TITLE
Add images codemod

### LINKED ISSUE #119: Download images and store them locally
## Description

In order to migrate images, we'll need to download them from the docs site and store them locally. Once the images are downloaded, we will need to update the image path in the markdown files to the relative path on the file system.

Some considerations on approaches:

1. * Do we want to store all images in the `src/images` folder? This means very-nested pages will require a pretty hefty import path (e.g. `../../../../../src/images/path/to/image.jpg`)
2. * Should we store the images in the same directory as the page? This makes relative imports easier, but may clutter content directories
3. * Should we create a subfolder in directories for images? (i.e. `src/content/whats-new/images/image.jpg` where a page in `whats-new` would reference `./images/image.jpg`)

## Acceptance criteria

* [ ] Download images locally
* [ ] Update the markdown path to reference the local path to the image

### PR DESCRIPTION
**Pull request by roadlittledawn**
Closes #119 

This codemod:
* gets all markdown image types
* adjusts the url if it's not absolute (eventually may want to enforce one domain)
* creates an `image` subdirectory in the directory of the file that references the image at hand
* downloads and saves the image in the `image` subdirectory
* modifies the markdown img url to use that new url
* prevents the migrate script from creating an auto index for `image` subdirectories

## Notes
* We're using an alpha release of MDX v2 and that version [breaks images w/ `gatsby-remark-images`](https://github.com/gatsbyjs/gatsby/issues/26662)

### CODE REVIEW

**Review by zstix — COMMENTED** [review]
Out of curiosity, why are we bringing in 50+ images but only 1 `.mdx` file is updated? Shouldn't more of the pages include the new images we're pulling in?

**Comment by jerelmiller** [comment]
Oops, we forgot to commit the `.mdx` files 😄

**Comment by roadlittledawn** [comment]
Yep, what Jerel said. I can push those now

**Comment by roadlittledawn** [comment]
@zstix .mdx files should now reflect in the changed files. thanks for catching that

**Comment by jerelmiller** [comment]
Weird, now the builds are failing. Let's see if we can fix that before merging this.

**Comment by roadlittledawn** [comment]
yeah i just noticed that we/i blew away the gatsby icon in src/images. i just re-added it

**Review by jerelmiller — APPROVED** [review]

**Pull request merged**
