### PR TITLE
Link to blog post from banner, update end date

### LINKED ISSUE #1134: The banner doesn't link to my very cool blog post
We have a banner, but it doesn't link to my blog post!

### PR DESCRIPTION
**Pull request by austin-schaefer**
Links to https://blog.newrelic.com/engineering/new-relic-docs-the-open-source-way/ from the announcement banner

Closes #1134

### CODE REVIEW

**Comment by austin-schaefer** [comment]
#1134

**Comment by austin-schaefer** [comment]
Closes #1134

**Comment by jerelmiller** [comment]
@austin-schaefer I think the auto linking to the issue has to be done by adding the `Closes #` in the PR description FYI

**Comment by austin-schaefer** [comment]
Thanks @jerelmiller , you are ridiculously fast. :D

**Pull request merged**
