### PR TITLE
ON HOLD FOR NOW: whats-new Skykit integration

### PR DESCRIPTION
**Pull request by marty733**
Notes from @zuluecho9 Nov 7: we are waiting to hear if we should publish this. Some internal discussion about whether it makes sense or not. 

From original creator: Please publish Mid-day 11-07-2022

### CODE REVIEW

**Comment by zuluecho9** [comment]
@marty733 Hi Marty. Just a note that you need to sign the CLA, which you should see a prompt for on this PR page.

**Review by aalfano7 — CHANGES_REQUESTED** [review]
My suggestions:
- Update title: "Share your New Relic dashboards with Skykit"
- Update summary: "Our new partner integration with Skykit lets you easily share your New Relic dashboards on TVs and other large format screens"
- Combine these sentences: "Our integration allows you to remotely push your dashboard to digital signage without the need for USB drives, individual computers connected to screens or other manual inputs. And, our user interface is extremely easy to use - you can successfully add a dashboard and display it instantly."  to: "Our user-friendly user interface makes it easy to add and push a dashboard to digital signage instantly, without the need for USB drives, individual computers connected to screens or other manual inputs."
- Update "perfect for" to "made for" in this sentence: "We’re not talking about a “screenshot” shared every few seconds - we mean real-time data visualization, made for teams who want to monitor their tools’ performance in real time."
- Capitalize "you've": "You've got the data, ..."
- Change "Increase" to "Promote": "Promote data-driven decisions:"
- Make comma a semicolon and hyphenate "decision making": "...company-wide; driving smart decision-making across your organization."
- Combine these sentences: "We are able to connect your New Relic dashboards securely through a variety of different login authentication approaches. And we save your team time by eliminating the need to login to individual screens throughout the day." to: "Connect your New Relic dashboards securely through a variety of different login authentication approaches, and save time by eliminating the need to login to individual screens throughout the day."

**Comment by zuluecho9** [comment]
@marty733 another question (besides request to sign the CLA): as far as I know we don't have a doc for this integration. near the end, where it mentions a 'doc', where would you like that to point?

**Comment by marty733** [comment]
Apologies just saw these comments. I signed the CLA. 

Will update the content from the comments above.

**Comment by zuluecho9** [comment]
@marty733 just a heads up: I reviewed those comments already and made changes. there is some internal discussion about whether this should even be published. If you're talking to a New Relic person, it might make sense to have them contact the docs team about this.

**Comment by marty733** [comment]
@zuluecho9 got it, thank you! Yes, we have communicated with @jcountsNR about this post.

**Comment by austin-schaefer** [comment]
@marty733 Moving to draft, let us know in #help-documentation if/when this should get moved back into the publication queue.

**Comment by zuluecho9** [comment]
Closing this, but we can of course always reopen it if needed.

**Pull request closed without merging**
