### PR TITLE
Updated Node.js env vars

### PR DESCRIPTION
**Pull request by bizob2828**
Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?

The Node.js agent didn't have feature parity between configuration values and env vars for those configuration values. We now do.  I also added some explanation around complex data types as env vars.

* If your issue relates to an existing GitHub issue, please link to it.

[Agent PR](https://github.com/newrelic/node-newrelic/pull/1399)

### CODE REVIEW

**Comment by bradleycamacho** [comment]
Hi @bizob2828, thanks for the edits! Tagging @rhetoric101 as a reviewer as he's the liaison for this area.

**Comment by bizob2828** [comment]
@bradleycamacho are you waiting for @rhetoric101 to chime in before approving this?

**Comment by bradleycamacho** [comment]
Hi @bizob2828, yes I'll go ahead and ping him directly to give this a review and merge

**Review by rhetoric101 — APPROVED** [review]
@bizob2828 thanks for making these changes! I loved the error message example: No soup for you!

**Pull request merged**
