### PR TITLE
PHP agent: Remove the doc about using a PHP script to record deployments

### PR DESCRIPTION
**Pull request by rhetoric101**
We are removing a low-traffic document. Our PHP team agreed.

### CODE REVIEW

**Review by paperclypse — COMMENTED** [review]
@rhetoric101 Is there anything we should redirect this to?

**Review by austin-schaefer — DISMISSED** [review]
@rhetoric101 Thanks, LGTM! But agree with Shawn, we should redirect this (and its redirects) to the deployments docs

**Review by austin-schaefer — APPROVED** [review]

**Review by paperclypse — APPROVED** [review]
looks good

**Review by paperclypse — APPROVED** [review]
Approved (again) :)

**Pull request merged**
