### PR TITLE
feat/npm new vpc install docs

### PR DESCRIPTION
**Pull request by thezackm**
adding beta docs for a new NPM functionality; AWS VPC Flow Logs support

cc @x8a for review please

### CODE REVIEW

**Comment by barbnewrelic** [comment]
From documentation slack channel: Request to hold for publication until 11-29-2021. Request for @x8a to review. I've moved this to draft state so it won't be published accidentally before then. Please re-confirm when you are ready to publish. Thanks!

**Review by x8a — APPROVED** [review]
Thanks for the new doc, @thezackm! 👏🏻👏🏻👏🏻

**Review by thezackm — COMMENTED** [review]
looks awesome @x8a ; thanks for the edits!

**Comment by thezackm** [comment]
@x8a - added a small addition to explain variable sample rates from the lambda

**Review by x8a — APPROVED** [review]

**Pull request merged**
