### PR TITLE
Updating Kubernetes CPM Configuration Options Displayed

### PR DESCRIPTION
**Pull request by irishgordo**
Hi there,

Really enjoy reading through these docs!
Stumbled on the synthetics-minion helm chart [here](https://github.com/newrelic/helm-charts/tree/master/charts/synthetics-minion) and saw that there seems to be a lot more options listed for configuration of the containerized private minion than what is currently displayed via the docs so I figured I'd whip up a small PR to create more parity between the two.

But!  I may be totally off, and perhaps some things aren't shouldn't be carried over into the docs :sweat_smile: 
Super willing to iterate, adjust, or even close this PR if these items aren't needed!

Big kudos to everyone that has spent so much time making these docs as awesome as they are!

### CODE REVIEW

**Comment by urbiz-nr** [comment]
Thanks so much for the update, @irishgordo! We're glad you enjoy our docs, and we really appreciate you helping them get better! I'll run this with the team and will come back to you if we have any questions before we merge this PR.

**Comment by austin-schaefer** [comment]
Hi @irishgordo , I'm the manager of our docs team, and just wanted to say we really appreciate your PR! I shared this with our social media team and they said they'd love to get you some New Relic swag—just send [@newrelic](https://twitter.com/newrelic) a Twitter DM if you're interested!

**Review by urbiz-nr — APPROVED** [review]
Thanks for all these updates, @irishgordo - the team says they're great! I've made some minor edits, and we're good to go!

**Comment by irishgordo** [comment]
Awesome!  Thanks @urbiz-nr & @austin-schaefer!  Glad I could help!!

**Pull request merged**
