### PR TITLE
Browser Agent v1.229.0 Release Notes

### PR DESCRIPTION
**Pull request by newrelic-browser-agent-team**
Browser Agent v1.229.0 Release Notes

### CODE REVIEW

**Comment by rhetoric101** [comment]
I am temporarily closing and re-opening this PR to trigger a new build.

**Comment by patrickhousley** [comment]
@rhetoric101 is the month and day required to be two digits?

**Review by rhetoric101 — APPROVED** [review]
@newrelic-browser-agent-team thanks for adding these release notes.

**Comment by rhetoric101** [comment]
@patrickhousley after I changed the day to two digits, the build completed. This appears to be a requirement.

**Pull request merged**
