### PR TITLE
Whats New For EKS Addon

### PR DESCRIPTION
**Pull request by rahul188**
Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Review by aalfano7 — CHANGES_REQUESTED** [review]
I suggest the following changes:

Monitor your AWS EKS Clusters with [New Relic EKS integration](https://aws.amazon.com/marketplace/pp/prodview-gcywa6keq2ajy), available on AWS EKS Marketplace. New Relic offers end-to-end visualization on cluster metrics and events, and our new add-on eliminates the time consuming process of installing the helm charts manually.

Installation of the New Relic EKS integration offers the following advantages:
* **Check health of your nodes in your cluster:**  Monitor the status of each node and the resources available to them, such as CPU and memory usage.
* **Customizable CRDs:** Create Custom Resource Definitions (CRDs) to enable/disable various pods as per the monitoring requirements.
* **Detailed events:** View detailed Kubernetes events to monitor health of the cluster.

**Next steps**

* Check out our documentation for the [EKS add-on from AWS marketplace](https://docs.newrelic.com/docs/infrastructure/amazon-integrations/connect/eks-add-on/)

**Comment by austin-schaefer** [comment]
Relates to #15639

**Comment by rahul188** [comment]
@austin-schaefer I made suggested changes.

**Review by akristen — APPROVED** [review]
it worked! Merging now

**Pull request merged**
