### PR TITLE
DOC-6245 style guide edits

### PR DESCRIPTION
**Pull request by zuluecho9**
Edits to API guideline docs for site migration.

### CODE REVIEW

**Comment by jpvajda** [comment]
Is this still a valid PR?

**Comment by jpvajda** [comment]
@zuluecho9 can you confirm if this is still a valid PR?

**Comment by zuluecho9** [comment]
> @zuluecho9 can you confirm if this is still a valid PR?

Yes, as far as I know.

**Comment by mmfred** [comment]
@zuluecho9 Please merge this PR as well. Thanks.

**Comment by austin-schaefer** [comment]
Pretty sure the directory/nav on this will need changing— @paperclypse will know more, but I think the `new-relic-only` directory is going away.

**Pull request merged**
