### PR TITLE
C++ Otel Example

### PR DESCRIPTION
**Pull request by zsistla**
From @zuluecho9: Related to DOC-7958. This is a WIP by their team. They'll let us know when they're ready for us to review. Leaving this in hero triage column for that reason. 

Original description: With the upcoming EOL of the c-sdk provides a clear example to steer users to c++ otel.

### CODE REVIEW

**Comment by zsistla** [comment]
Draft version.  Please do not merge as my team reviews.

**Comment by barbnewrelic** [comment]
Moving this to draft column so it doesn't accidentally get reviewed and published before the team is ready.

**Comment by barbnewrelic** [comment]
@zsistla  Thanks for letting me know! As soon as the build finishes rebuilding, I will review one last time.

**Comment by barbnewrelic** [comment]
@zsistla  I'm going to take the liberty of moving your suggested alternative into the C SDK EOL callout in src/content/docs/apm/agents/c-sdk/get-started/introduction-c-sdk.mdx rather than spinning them off to the Explorers Hub post and then back over to your new doc. I'm also going to add your new doc to our nav file and make a few minor style guide edits to it. This will have to build again once I'm done, but I'll keep you posted.

**Review by barbnewrelic — APPROVED** [review]
Made some minor copyedits and verified with SME. Good to go, thanks for all your hard work on this!

**Pull request merged**
