### PR TITLE
fix(Logs): Move agent API to logs in context

### PR DESCRIPTION
**Pull request by barbnewrelic**
The agent API doc was buried under 4 (!!) taxonomy levels, so I moved it into the logs in context taxonomy in preparation for that entire taxonomy shift.

### CODE REVIEW

**Review by dbarnesbrownNR — APPROVED** [review]
Links all appear to be working fine, no additional comments. Thanks!

**Comment by barbnewrelic** [comment]
paperclip said turn this into a draft to see if the gatsby build service will kick in

**Review by barbnewrelic — COMMENTED** [review]
THIS IS FINE, IT JUST WON'T BUILD

**Comment by dbarnesbrownNR** [comment]
@barbnewrelic looks like there is a merge conflict here, so you will want to investigate that. But the content I looked at here still looks good!

**Comment by barbnewrelic** [comment]
I got tired of waiting for the gatsby build to work, so I slipped this new doc into another branch that DID work. Thanks @dbarnesbrownNR  for reminding me that this was still lurking out there! Closing this pr.

**Pull request closed without merging**
