### PR TITLE
(Release 12/12 @ 3pm) feat(PHP agent): Add custom event section

### PR DESCRIPTION
**Pull request by mfulb**
The PHP team will be adding the `newrelic.custom_events.max_samples_stored` INI variable in an upcoming release and this PR adds content to the PHP configuration page regarding the custom event variables.

Please review but do not merge until we have given the OK as the release date is not determined at this time.

### CODE REVIEW

**Review by jeff-colucci — DISMISSED** [review]
I just made one small styling change, if it doesn't work please let me know. Other than that, looks good!

**Comment by jeff-colucci** [comment]
I've gone ahead and changed the title and will put this ticket into the future work column on our board. When you're ready for it to go out please reach out to me and I will get it merged and re-reviewed if necessary!

**Comment by mfulb** [comment]
Ah yes I like your change - thank you!

**Comment by mfulb** [comment]
I added a small section on code level metrics as we are adding an option to enable it.

**Review by a-sassman — APPROVED** [review]

**Comment by ZNeumann** [comment]
We have released and are ready for this to merge. Thanks!

**Pull request merged**
