### PR TITLE
(Target publication date: 10/25/2023) Log chart markers

### PR DESCRIPTION
**Pull request by eknuth**

### CODE REVIEW

**Comment by rhetoric101** [comment]
@eknuth I made a few minor edits. Can you take a look?

**Review by rhetoric101 — APPROVED** [review]
@eknuth I made a few minor edits.

**Comment by PrashRelic** [comment]
I've reviewed it, and looks good. A typo in docs is being fixed.

**Comment by eknuth** [comment]
Thanks, everyone! 🚀

**Review by homelessbirds — APPROVED** [review]

**Pull request merged**
