### PR TITLE
Patch 69

### PR DESCRIPTION
**Pull request by brnhensley**
At the request of Jacob Affinito on the .NET I added In-process hosting to the App/Web server section. This was in response to a support ticket asking about In-process hosting, as that does not use Kestrel.
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/in-process-hosting?view=aspnetcore-6.0

Jacob asked me to keep it vague and send it to him to look at after I committed. 

This also includes minor stylist improvements and a typo fix.

Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Comment by rhetoric101** [comment]
@brnhensley it looks like the Tech Pubs team should wait on this until you get a technical review, right?

**Comment by brnhensley** [comment]
Yep @rhetoric101 the .NET hero wanted to review this one.

**Review by jaffinito — DISMISSED** [review]
This looks great!

**Comment by brnhensley** [comment]
Ok, should be good not @rhetoric101

**Review by x8a — APPROVED** [review]
Thanks!

**Comment by x8a** [comment]
No worries, @brnhensley! When you push a new commit, GitHub removes the approval to make sure someone looks at it again before merging.

It looks great, so let's merge it! Thanks a bunch!

**Pull request merged**
