### PR TITLE
Adding Release Note for React native Agents

### PR DESCRIPTION
**Pull request by ndesai-newrelic**
Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
Adding missed Release Notes for React Native Agent
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
Check React Native Symbol on Release Notes Tile
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Comment by barbnewrelic** [comment]
@ndesai-newrelic  I consulted with our docs-engineers about why your PR has failed not once but twice. They suspect it's because your fork is severely out of date and so it can't find the RN logo that was recently added. Would you like to try creating a new fork and just copying all of this over to it? Or would you prefer that one of our tech writers to get this new release notes category into the site for you? Thanks for letting us know how you would like to proceed!

**Comment by barbnewrelic** [comment]
@homelessbirds  cc-ing you because I think you know much more about the new React Native launch than I do. :-)

**Comment by ndesai-newrelic** [comment]
@barbnewrelic I am okay with your team adding these release notes on the site. I also updated my branch.

**Review by homelessbirds — APPROVED** [review]

**Comment by x8a** [comment]
Merged as per @ndesai-newrelic request.

**Pull request merged**
