### PR TITLE
Release Notes JSON Description Field

### PR DESCRIPTION
**Pull request by cade-conklin**
### Give us some context
[The current release notes JSON](https://docs.newrelic.com/api/agent-release-notes.json) return a JSON with fields: agent, version, and release date.  One of our services relies on this JSON but needs a _description_ field so that it can parse the release notes to determine the supportability for various agents.  The change was very minor and involved adding an _excerpt_ field to the GraphQL call.  The length of each excerpt was arbitrarily set at 5000 assuming most release notes won't exceed that length.  When running locally, this is what the new JSON will look like 
Screen Shot 2021-09-08 at 1 54 51 PM

Here is a link to the [issue](https://github.com/newrelic/docs-website/issues/1370) that was opened a while ago.  The reason this was just now completed was that our team just now raised visibility on it again.

### Are you making a change to site code?

Yes.  This is a very small change!

If you're changing site code (rather than the content of a doc), please follow
[conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

### CODE REVIEW

**Comment by x8a** [comment]
Hey, @jpvajda! Could you have a look at this? Thanks!

**Comment by jpvajda** [comment]
I'm going to see if @roadlittledawn can review as well. It looks good to me, but he did some work on this part of the site so wanted another set of 👀  on it. Thanks for the contribution @x8a  and @cade-conklin

**Review by aswanson-nr — APPROVED** [review]
Looks good to me!

**Review by zstix — APPROVED** [review]
The first time I ran this my environment crashed, but every other time this has worked well, so I'm chalking it up to something on my end 🎉

**Pull request merged**
