### PR TITLE
Add missing path to create index page for "Observe Everything"

### PR DESCRIPTION
**Pull request by zstix**
## Description
Does what it says on the tin.

Of note, we previously had documentation for this stuff but it was [recently removed](https://github.com/newrelic/docs-website/pull/3670).

## Screenshot(s)
Screen Shot 2021-08-30 at 10 46 16

### CODE REVIEW

**Comment by zuluecho9** [comment]
@zstix that internal how to doc wasn't removed; we just created a new longer doc for it fyi.

**Comment by mmfred** [comment]
@zuluecho9 - are you saying this PR is not needed? Unsure what to do with this.

**Comment by zstix** [comment]
@zuluecho9 I hate to disagree, but the content that was in that document does _not_ exist in the repository anymore. For example, we used to have a section called "Add a new top-level nav" that no longer exists: https://github.com/newrelic/docs-website/search?q=Add+a+new+top-level+nav

Same with [Use nav `YAML` to populate page menus](https://github.com/newrelic/docs-website/search?q=Use+nav+%60YAML%60+to+populate+page+menus), [Nav Requirements](https://github.com/newrelic/docs-website/search?q=%22Nav+requirements%22), etc.

**Comment by zuluecho9** [comment]
@zstix Yes, it was dramatically restructured, mainly because the team was having trouble with it so we wanted to make it more usable for everyone. So that now that content lives in a new section here: https://docs.newrelic.com/docs/style-guide/processes-procedures/understand-edit-docs-site-structure/#add-nav-section 

I"m curious, too: what was your goal in wanting the category view for 'Observe everything'? Was it just to make it parallel with other categories? Or was there a problem/use case you were seeing for wanting that?

**Comment by zstix** [comment]
@zuluecho9 At the moment, the page blank: https://docs.newrelic.com/docs/full-stack-observability/observe-everything/

I figured that we would prefer to have some links generated to align it with how the rest of the site handles it. If this isn't desired, feel free to close out the PR!

**Comment by zuluecho9** [comment]
no that makes sense @zstix. Gonna approve it now. I was just curious if it was just something you noticed or if it was from a complaint or what. Thanks.

**Comment by zstix** [comment]
@zuluecho9 Yeah, I noticed the issue.

I _do_ want to point out (and I apologize for being a stickler about this) that the reason this page is blank is because of a requirement that we had previously had documented that is no longer in the consolidated style guide:

> When creating the page we look through each nav `YAML` file for a reference to the path to know which nav data to use for the left nav and the auto index page content.

**Comment by zuluecho9** [comment]
@zstix Some of the 'how it works' was moved up into the more conceptual/philosophical section at top: https://docs.newrelic.com/docs/style-guide/processes-procedures/understand-edit-docs-site-structure/#doc-sidebar. I'll add a link or two from the 'create nav file' section to that 'how it works' section though.

**Pull request merged**
