### PR TITLE
PUBLISH: 5/30 Security Lake Doc feedback from AWS

### PR DESCRIPTION
**Pull request by anshrma**
Details emailed to Kiran

### CODE REVIEW

**Comment by akristen** [comment]
Hi @anshrma. Made some structural edits and added some markdown so the doc builds + follows our style guide. If you can look over my edits and make sure nothing has been lost, that'd be wonderful.

I'm not sure when you wanted this doc out, but I marked it as 'In progress'. When you're ready for a merge, go ahead and ping the hero in our docs help channel!

**Comment by anshrma** [comment]
> Hi @anshrma. Made some structural edits and added some markdown so the doc builds + follows our style guide. If you can look over my edits and make sure nothing has been lost, that'd be wonderful.
> 
> I'm not sure when you wanted this doc out, but I marked it as 'In progress'. When you're ready for a merge, go ahead and ping the hero in our docs help channel!

hi @akristen - Thanks for the edits. Pushed few changes which otherwise were modifying the intent/ resulting alternate actions. I would defer to @kiranhew to confirm when can this be merged.

**Comment by akristen** [comment]
Content and copy edits have been done, have not done troubleshooting on build errors.

**Comment by zuluecho9** [comment]
closing this because we have same work in this pr https://github.com/newrelic/docs-website/pull/13075

**Pull request closed without merging**
