### PR TITLE
PHP 9.18.0 release notes

### PR DESCRIPTION
**Pull request by Fahmy-Mohammed**
This includes the release notes for PHP agent `9.18.0`. The release is targeted for `8/18/21`.

### CODE REVIEW

**Comment by Fahmy-Mohammed** [comment]
Please hold off on releasing this until 4/18/21 12PST. That is when the agent is released to the public

**Review by urbiz-nr — APPROVED** [review]

**Comment by urbiz-nr** [comment]
Thanks for the RN, @Fahmy-Mohammed! I'll get in touch with the PDX hero to merge this PR at the right time.

**Comment by urbiz-nr** [comment]
@Fahmy-Mohammed - to clarify, this needs to go live today at 12pm PST, not on 4/18/21, right?

**Comment by Fahmy-Mohammed** [comment]
> @Fahmy-Mohammed - to clarify, this needs to go live today at 12pm PST, not on 4/18/21, right?

Yes, you're absolutely right! Today at 12 🙂

**Comment by mikefulb** [comment]
We have found an issue and are going to rollback this release - can you revert this PR please?

**Comment by urbiz-nr** [comment]
Reverted in #3551.

**Comment by mfulb** [comment]
Thank you.

**Pull request merged**
