### PR TITLE
Trying to figure out how to get the style guide to show up on the site

### PR DESCRIPTION
**Pull request by paperclypse**
Created a style guide yml file and moved the style guide docs over.

It's not working. Think I'll need some other eyes on this.

### Tell us why

We're trying to get our style guide content onto the site. This is a PR for that work.

### Anything else you'd like to share?

So far, I'm not having much luck.

### CODE REVIEW

**Comment by jerelmiller** [comment]
I'm testing this out locally

**Comment by paperclypse** [comment]
Thanks @jerelmiller!

**Comment by paperclypse** [comment]
It was a yarn issue. Once I restarted yarn, it worked just fine.

**Comment by jerelmiller** [comment]
Oh cool! Glad thats all it was 😄 . Was just about to say I was also able to see it locally. Feel free to merge when you get the right approvals and feel good about this!

**Comment by bradleycamacho** [comment]
@paperclypse Looks good to me! Approved :)

**Comment by paperclypse** [comment]
Woohoo! Thanks guys!

**Pull request merged**
