### PR TITLE
Adds cosmosdb support 

### PR DESCRIPTION
**Pull request by vuqtran88**
Update .NET agent compatibility matrix to include cosmosdb client library support.

### CODE REVIEW

**Comment by dbarnesbrownNR** [comment]
Hi @vuqtran88, I'm wondering if the info you are adding to the doc also exists in the Microsoft Azure docs themselves? If so, I'd suggest linking directly to those docs rather than listing out a long block of text within a table. Do you think this might work?

**Comment by vuqtran88** [comment]
> Hi @vuqtran88, I'm wondering if the info you are adding to the doc also exists in the Microsoft Azure docs themselves? If so, I'd suggest linking directly to those docs rather than listing out a long block of text within a table. Do you think this might work?

Hi @dbarnesbrownNR , thanks for reviewing. Microsoft Azure does have the docs about their apis; but their docs is huge. I purposely listed out a set of api method calls, because they are methods called that we have tested. I thought this might give the customers better idea what they are expecting from this feature.

**Comment by dbarnesbrownNR** [comment]
Taking my name off this one as I will not be available after Nov 19, but it will be picked up by another member of our team soon, @vuqtran88. Thanks for providing that clarity!

**Review by rhetoric101 — APPROVED** [review]
@vuqtran88, thanks for this Cosmos  DB update! We're having docs build issues, but when we get that fixed, we'll publish you changes.

**Pull request merged**
