### PR TITLE
Update the python opentelemetry example to use current environment variable values

### PR DESCRIPTION
**Pull request by Tasty213**
The environment variables for the metrics exporter as defined [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk_exporters/otlp.md#opentelemetry-metrics-exporter---otlp) now use new values for temporality preference and histogram aggregation. This PR updates the Python OpenTelemetry tutorial to use the new values but keep the intended behaviour.

### CODE REVIEW

**Comment by rhetoric101** [comment]
@Tasty213 could you sign our CLA so we can publish your suggestions? Also, are you an employee of New Relic or are you a user?

**Comment by Tasty213** [comment]
Ok signed the CLA and I'm a user

**Comment by reese-lee** [comment]
Looks good to me

**Review by rhetoric101 — APPROVED** [review]
@Tasty213 thanks for your suggestions!

**Pull request merged**
