### PR TITLE
[Snyk] Upgrade @splitsoftware/splitio-react from 1.2.0 to 1.2.4

### PR DESCRIPTION
**Pull request by nr-security-github**
<h3>Snyk has created this PR to upgrade @splitsoftware/splitio-react from 1.2.0 to 1.2.4.</h3>

merge advice
:information_source: Keep your dependencies up-to-date. This makes it easier to fix existing vulnerabilities and to more quickly identify and fix newly disclosed vulnerabilities when they affect your project.
<hr/>

- The recommended version is **14 versions** ahead of your current version.
- The recommended version was released **a month ago**, on 2021-02-11.

<hr/>

**Note:** *You are seeing this because you or someone else with access to this repository has authorized Snyk to open upgrade PRs.*

For more information:  

🧐 [View latest project report](https://app.snyk.io/org/github-newrelic/project/fda73ff4-b333-4cdc-97a2-86e67b2e5089?utm_source&#x3D;github&amp;utm_medium&#x3D;upgrade-pr)

🛠 [Adjust upgrade PR settings](https://app.snyk.io/org/github-newrelic/project/fda73ff4-b333-4cdc-97a2-86e67b2e5089/settings/integration?utm_source&#x3D;github&amp;utm_medium&#x3D;upgrade-pr)

🔕 [Ignore this dependency or unsubscribe from future upgrade PRs](https://app.snyk.io/org/github-newrelic/project/fda73ff4-b333-4cdc-97a2-86e67b2e5089/settings/integration?pkg&#x3D;@splitsoftware/splitio-react&amp;utm_source&#x3D;github&amp;utm_medium&#x3D;upgrade-pr#auto-dep-upgrades)

### CODE REVIEW

**Review by jpvajda — APPROVED** [review]

**Comment by jpvajda** [comment]
This is creating a yarn.lock conflict that looks a little suspect so I'm going hold off on merging and have one of the engs take a look.

```
<<<<<<< snyk-upgrade-d3500795bab9afb3f38d142a9506937e
=======
"@types/node@^13.9.1":
  version "13.13.17"
  resolved "https://registry.yarnpkg.com/@types/node/-/node-13.13.17.tgz#fba8bdd9be9a61adbceac654450673c2f520b0f0"
  integrity sha512-rGZftvdDpsYtG/rOlDOwny1f6Aq4FHJdGSVfPg5vC2DaR9Rt4W2OpsOF5GTU2bSqZmwTkfnsvJhhzpMWYxxlEA==

"@types/node@^14.14.10":
  version "14.14.33"
  resolved "https://registry.yarnpkg.com/@types/node/-/node-14.14.33.tgz#9e4f8c64345522e4e8ce77b334a8aaa64e2b6c78"
  integrity sha512-oJqcTrgPUF29oUP8AsUqbXGJNuPutsetaa9kTQAQce5Lx5dTYWV02ScBiT/k1BX/Z7pKeqedmvp39Wu4zR7N7g==

>>>>>>> develop
"@types/node@^8.5.7":
  version "8.10.62"
  resolved "https://registry.yarnpkg.com/@types/node/-/node-8.10.62.tgz#8d0d0db44a46ae7679d92e2e36d41bf1c3625d6a"
  integrity sha512-76fupxOYVxk36kb7O/6KtrAPZ9jnSK3+qisAX4tQMEuGNdlvl7ycwatlHqjoE6jHfVtXFM3pCrCixZOidc5cuw==
```

**Review by jpvajda — CHANGES_REQUESTED** [review]
resolve conflicts before merge

**Review by zstix — APPROVED** [review]
@jpvajda Looking at the diff, I'm not seeing that merge conflict. I wonder if that's something you're seeing on your machine due to some work you had (via another branch).

When I ran this locally, I didn't run into any issues.

**Comment by zstix** [comment]
@jpvajda I should have read your comment more carefully before approving. I've update the PR to be in sync with `develop` and I've resolved that merge conflict.

**Comment by jpvajda** [comment]
@zstix oh possibly! I've been Snykin' a lot these days.. so perhaps I don't have the most recent changes locally pull down on the Docs Site. let me do that and check.

**Comment by zstix** [comment]
I _think_ I've wrapped up bringing this up to date with `develop`. We had a bit of a traffic jam with all the Snyk PRs, but the should all be merged in.

**Pull request merged**
