### PR TITLE
golang logs in context (ETA 06-29-22)

### PR DESCRIPTION
**Pull request by iamemilio**
Docs hero: @barbnewrelic will take care of this one when ready to release!

feat: logs in context for golang

this adds documentation for logs in context for the go agent. Please merge this in synchronization with the go team's release of the [logs in context feature](https://github.com/newrelic/go-agent/pull/507/files#diff-53f120c6a2a5ba988e3e06e60026b8a2e8c67884654d88e9f10e10da2c4ba72f) 

For additional context about the zerolog plugin, see the readme here: https://github.com/newrelic/go-agent/blob/2e6700e93818bef216c81635ffc4a0d0d801242f/v3/integrations/logcontext-v2/nrzerolog/Readme.md

### CODE REVIEW

**Comment by barbnewrelic** [comment]
@iamemilio  Thanks for letting us know! Do you have an ETA for when Go will release automatic logs in context or what release version that will be available? Please @ mention me (I'm currently logs docs liaison) whenever your team is ready, and I will sync together these doc releases. No rush!

**Comment by iamemilio** [comment]
@barbnewrelic we are targeting the end of June for a full release, but that release date is currently at risk until I clear up some issues in the code. I will coordinate with you as soon as we are confident about a release date, and follow up the week of the release so there are no surprises.

**Comment by iamemilio** [comment]
@barbnewrelic We are aiming to release next Monday!

**Review by barbnewrelic — APPROVED** [review]
Thanks for preparing these docs for launch!

**Pull request merged**
