### PR TITLE
Adds docs for managing live chart URLs via NG API

### PR DESCRIPTION
**Pull request by sinan-ku**
### Give us some context

* Adds documentation on how to list & revoke public live chart URLs

### CODE REVIEW

**Comment by urbiz-nr** [comment]
Thanks for the doc, @sinan-ku! Let me have a look at it and I'll get back to you if I have any questions. In the meantime, could you sign the CLA? You only need to do this once to collaborate on our site :)

**Review by urbiz-nr — DISMISSED** [review]
Thanks for the tutorial @sinan-ku, looks good!

**Comment by sinan-ku** [comment]
Hello,  I've signed the CLA - thank you!

**Review by urbiz-nr — APPROVED** [review]

**Comment by urbiz-nr** [comment]
Closed via #3598.

**Pull request closed without merging**
