### PR TITLE
fix: update broken links

### PR DESCRIPTION
**Pull request by brnhensley**
this link also looks dead, it redirects to the link before it, but I don't know what the correct one might be:

```md
To customize your query, use any of the available [`NrAuditEvent` attributes](/docs/insights/insights-data-sources/default-data/nrauditevent-default-attributes-examples)
```

Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Comment by clarkmcadoo** [comment]
netlify build

**Comment by homelessbirds** [comment]
netlify build

**Comment by homelessbirds** [comment]
netlify build

**Comment by LizBaker** [comment]
making a new PR because netlify has forsaken this one

**Pull request closed without merging**
