### PR TITLE
ON HOLD: whats-new - Amazon Linux 2022 support

### PR DESCRIPTION
**Pull request by kupsand**
Hello, docs team -

This is Kevin Downs, New Relic infrastructure PMM - kdowns@newrelic.com and does not need to be reviewed by other PMMs.

This What's New post should be published mid-day on Nov 9th - not before.

Thank you - I can be reached on Slack is needed.

### CODE REVIEW

**Review by zuluecho9 — APPROVED** [review]

**Comment by akristen** [comment]
Whoever merges, please confirm that the video is embedded in the post!

**Comment by a-sassman** [comment]
For the Nov 8 hero: @kupsand Informed me that this will NOT be going out November 8, as AWS moved the GA date again.

**Comment by austin-schaefer** [comment]
@kupsand Moving to draft, let us know in #help-documentation if/when this should get moved back into the publication queue.

**Comment by austin-schaefer** [comment]
Closing out all open 2022 PRs, feel free to re-open if there's active work here or this becomes active again!

**Pull request closed without merging**
