### PR TITLE
Ruby Agent 7.2.0 release

### PR DESCRIPTION
**Pull request by amhuntsman**
* Added configuration options for expected errors
* updated existing links from Ruby API to error collector config section

### Give us some context

Update docs for Ruby Agent 7.2.0 release.

Adds configuration options for expected errors which are introduced in this release. Updates links to general information on expected errors - previously the Ruby link pointed to the API docs for expected errors.

Also did some clean up on deprecated options - removed duplicate "deprecate"s adjacent to each other.

### Are you making a change to site code?

No.

**NOTE:** Please do not merge until Ruby Agent 7.2.0 is released (which should be soon this week).

### CODE REVIEW

**Review by paperclypse — DISMISSED** [review]
I made some minor edits. Otherwise, looks good! (We may need to update the release date to match reality.)

Hold for release.

**Comment by amhuntsman** [comment]
I went ahead and changed the remaining "cannot"s to "can't"s, and removed some duplicate cautions.

**Review by paperclypse — APPROVED** [review]
Looks good! Is this ready to be published @amhuntsman?

**Comment by tannalynn** [comment]
hello @paperclypse, aaron is on FTO today, but we are ready for this to be published now! thank you!

**Pull request merged**
