### PR TITLE
chore: upgrade gatsby to 3.10.1

### PR DESCRIPTION
**Pull request by rudouglas**

### CODE REVIEW

**Review by aswanson-nr — COMMENTED** [review]
I'm still seeing the redirect behavior where it removes the anchor parameter. I don't think that needs to hold up this PR, since it's still worth upgrading. But I do not think it closes out https://github.com/newrelic/docs-website/issues/2139

**Comment by aswanson-nr** [comment]
> I'm still seeing the redirect behavior where it removes the anchor parameter. I don't think that needs to hold up this PR, since it's still worth upgrading. But I do not think it closes out #2139

Now that I think more about it, this could be because the theme has not been updated to the new version of Gatsby as well.

**Comment by rudouglas** [comment]
omg the first time i tried this it didn't work and then I went back and tried it multiple times and it was working, and now it no no work 🤦

**Comment by rudouglas** [comment]
I tried several things to try to fix this:
 - Removing `forceTrailingSlashes` from the config
 - Remove `appendTrailingSlash` from the `createRedirect` function in gatsy-node
But this still seems to force a trailing slash and remove the parameter so there must be something i'm missing in the cde that's doing this

**Pull request closed without merging**
