### PR TITLE
Fix typo and broken link for MLOps documentation

### PR DESCRIPTION
**Pull request by RichVanderwal**
## Give us some context

* I just read through one page of the MLOps docs and saw a typo and a broken "getting started" link.

### CODE REVIEW

**Comment by rhetoric101** [comment]
@RichVanderwal it looks like you'll need to sign our license agreement (CLA) again in GitHub.

**Comment by rhetoric101** [comment]
I am temporarily closing so that when I reopen it, the CLA job will start.

**Comment by LizBaker** [comment]
trying to get cla assistant to snap out of it

**Comment by rhetoric101** [comment]
This PR seems to have a CLA job that won't complete, despite a lot of troubleshooting. I will close this on Tuesday (tomorrow), and re-create this in a fresh PR and see if we can get past this.

**Comment by rhetoric101** [comment]
@RichVanderwal the CLA job on this PR is broken, so I just created this PR to do the same work: https://github.com/newrelic/docs-website/pull/12340

**Pull request closed without merging**
