### PR TITLE
Update polling-intervals-aws-integrations.mdx

### PR DESCRIPTION
**Pull request by vinrelic**
Changed VPC polling period from 15 mins to 5 mins

Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Comment by vinrelic** [comment]
Correcting the polling interval for VPC

**Comment by rhetoric101** [comment]
@vinrelic thanks for your creating this PR! Could you clarify why this timeout value is changing? For example, did AWS recently change this or has this always been incorrect in our docs?

I'm not seeing your name in the New Relic organization in GitHub. Could you join the organization and send me a DM to confirm it?

**Comment by rhetoric101** [comment]
@vinrelic thanks for your creating this PR! Could you clarify why this timeout value is changing? For example, did AWS recently change this or has this always been incorrect in our docs?

I'm not seeing your name in the New Relic organization in GitHub. Could you join the organization and send me a DM to confirm it?

**Comment by rhetoric101** [comment]
@vinrelic I don't think I heard back from you about this, so I'm going to close this for now. If you still think this is an important change, you can reopen it.

**Pull request closed without merging**
