### PR TITLE
feat: Add documentation/context on cascading and locking for APM log forwarding

### PR DESCRIPTION
**Pull request by cdanielsen**
**Meta**
Associated Ticket: https://issues.newrelic.com/browse/NR-32429

**Summary**
This PR updates the docs around managing configuration of automatic APM log forwarding to align with changes being released in [NR-24500](https://issues.newrelic.com/browse/NR-24500) and changes that were already released in [NR-3556](https://issues.newrelic.com/browse/NR-3556):
- Parent account enable/disable changes "cascade" to child accounts by default unless a child has applied their own non-default update
- Parent accounts can force child accounts to inherit their enabled/disabled setting via the "lock" setting (or allow children to configure their own settings again by "unlocking"
- Generally updates verbiage from an emphasis on "disabling" to "managing" as parent accounts now have the controls to put their accounts in any of four states:
```
Enabled / Locked
Enabled / Unlocked
Disabled / Locked
Disabled / Unlocked
```

### CODE REVIEW

**Comment by cdanielsen** [comment]
I've signed the CLA but it seems to still be showing up as pending / the recheck link does not work... also not sure how to resolve the build failure

**Comment by cdanielsen** [comment]
@bradleycamacho Any help on the above two build issues would be appreciated. Also confirmed with PM this is ready for a review from a technical writer, minus a a couple of outstanding issues:
- As we are generally proposing changing the verbiage from "disable" => "manage", it would make sense to change the page route/title to something like `manage-automatic-logging.mdx`. I didn't make that change yet because it would make it harder to evaluate changes since the diff would be a new file
- It looks like there are internationalized versions of this page (Korean and Japanese). I'm not sure what the process is for making sure those are up to date as well?

**Comment by bradleycamacho** [comment]
@cdanielsen sorry for the delay!

```
Christian Danielsen seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
```

Our CLA is a bit funky at times. Can you ensure you have the correct e-mail address associated with your Github account? Happy to hop on a call later and get this figured out.

I'm taking a look at the build issues now

**Comment by bradleycamacho** [comment]
> it would make sense to change the page route/title to something like manage-automatic-logging.mdx

I would actually just forget about this for now in that case! Once we're ready to merge in, I can commit the change myself before merging. 

> It looks like there are internationalized versions of this page (Korean and Japanese). I'm not sure what the process is for making sure those are up to date as well?

Our translations are part of an automated process. Basically, don't worry about them! They'll soon be updated to the most recent version of the english doc.

Taking a look at the doc for copyedits and figuring out why the build failed.

**Comment by cdanielsen** [comment]
> Our CLA is a bit funky at times. Can you ensure you have the correct e-mail address associated with your Github account? Happy to hop on a call later and get this figured out.

Ah, that was it thank you (commit had my newrelic.com address associated with it). I rebased and fixed it, so hopefully that should resolve that issue at least.

**Comment by cdanielsen** [comment]
Just curious, can you explain why f29f136 was needed?

**Comment by cdanielsen** [comment]
Thanks for the build help @bradleycamacho 🙌 .  What's the next step to get it reviewed?

**Review by bradleycamacho — APPROVED** [review]

**Pull request merged**
