### PR TITLE
Redirected broken mobile toc link

### PR DESCRIPTION
**Pull request by urbiz-nr**
The mobile TOC link is broken (as reported in #3706), so I'm adding the redirect in the landing page.

### CODE REVIEW

**Comment by urbiz-nr** [comment]
Works locally.

**Comment by zuluecho9** [comment]
Just a heads up that this seems to have an edit to the yarn lock doc, which i'm not sure if that's purposeful or not. I'm not sure what that file is.

**Comment by urbiz-nr** [comment]
A random file was added to the PR, closing this and starting over.

**Comment by urbiz-nr** [comment]
Removed offending file and merged.

**Pull request merged**
