### PR TITLE
[Product-Partnerships] Create aws-lex-monitoring-integration.mdx

### PR DESCRIPTION
**Pull request by aj-NR**
Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Review by x8a — APPROVED** [review]
Thanks for adding the doc!

**Review by x8a — APPROVED** [review]

**Comment by x8a** [comment]
Waiting for @aj-NR's green light to merge.

**Comment by x8a** [comment]
We're waiting on AWS. As @aj-NR has told me, we've raised a business support case.

**Comment by x8a** [comment]
@aj-NR confirmed that they're about to be ready for release. We'll may be able to release next week.

**Review by x8a — DISMISSED** [review]
Looking forward to releasing this soon! 🙌🏻

**Comment by aj-NR** [comment]
This PR can be taken up for review and merge now

**Review by nbaenam — APPROVED** [review]
Thank you for the update!! I’ve moved the page in the navigation to have it alphabetically ordered. Other than that, it's perfect!

**Pull request merged**
