### PR TITLE
Mobile app license cleanup

### PR DESCRIPTION
**Pull request by jvanmetre**
### Give us some context

* The Insights iOS and Android app are end of life on Sunday April 11th. 
* This PR remove the license files that are particular to those two sets of apps (iOS and Android)
* This PR also moves the tvOS licenses into their own license file

### CODE REVIEW

**Comment by jvanmetre** [comment]
Maybe switch to what the iOS version did? ```[contact@christopherdehaan.me](contact@christopherdehaan.me)```

**Comment by jvanmetre** [comment]
Or this ```<contact@christopherdehaan.me>``` needs to be ```&lt;contact@christopherdehaan.me&gt;``` because it's confused with the @ inside the html tag <

**Comment by paperclypse** [comment]
Thanks, @jvanmetre! We've tried both of those things. There's something funny going on with the cache and the Gatsby build check.

**Comment by paperclypse** [comment]
Putting the email address in code comments seems to have done the trick. I'm going to merge this so it'll get into tomorrow's merge into main.

**Pull request merged**
