### PR TITLE
Add description of logging max_samples_stored

### PR DESCRIPTION
**Pull request by rhetoric101**
We need a description of the logging configuration parameter `max_samples_stored` in each agent. This is an initial exploration of wording for the Java agent that may be able to be used across agents.

### CODE REVIEW

**Review by fallwith — DISMISSED** [review]
The Ruby agent changes look great!

**Comment by iamemilio** [comment]
The Go agent changes lgtm!

**Comment by nr-swilloughby** [comment]
The Go language looks ok and I agree with standardizing on the term "transaction" as discussed offline. (Er, online but a different "online". Whatever.)

**Review by paperclypse — APPROVED** [review]
Looks good!

**Pull request merged**
