### PR TITLE
feat(vuln-mgmt): Added FOSSA integration doc under vuln mgmt (Publish TBA)

### PR DESCRIPTION
**Pull request by nr-aayare**
Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

A new doc under vulnerability management that introduces customers to the new FOSSA integration and explains how best to set up and configure it.

### CODE REVIEW

**Comment by nr-aayare** [comment]
netlify build

**Comment by jeff-colucci** [comment]
@nr-aayare Sorry for the delay, I did some major style edits and mdx cleanup. Let me know what you think!

**Comment by nr-aayare** [comment]
Hey @jeff-colucci the changes look great. Thanks for doing this. 
We are facing a few blockers and it will take a week or so to make the integration live. In the meantime I'll add a few screenshots in the same PR. 
I'll update you once we're ready, then we can deploy the page.

**Comment by jeff-colucci** [comment]
@nr-aayare That works, I'll move this into the scheduled work column, just let me know when we're good to push the button on it!

**Comment by nr-aayare** [comment]
Hi @jeff-colucci , I have taken the benefits section at the top. Changed a few things based on the feedback received from Emily Weeks (product and privacy counsel). Let me know if this looks good.

**Review by cbehera-newrelic — APPROVED** [review]
Since it's been already reviewed and approved.

**Pull request merged**
