### PR TITLE
"What's new" Infra EC2 Lower Costs

### PR DESCRIPTION
**Pull request by kupsand**
Hello there - Kevin Downs (kdonws@newrelic.com) here. I am requesting that this What's New post be published on December 15th, 2021 between 12 AM EST and 9 AM EST.

Thank you

### CODE REVIEW

**Comment by barbnewrelic** [comment]
@daynaslord  @jkinmonth  I see that you are auto-assigned as reviewers. Can you please review this post? He is asking for a non-standard release time, so I want to make sure it is ready to go before tomorrow. Thanks!

**Comment by barbnewrelic** [comment]
@kupsand  Congrats on your first post! I do have a question: The Explorers Hub post in the "Learn More" link indicates it is private. Will that be enabled publicly before your What's New post is live, or is that intentional? Thanks for confirming!

**Review by barbnewrelic — APPROVED** [review]
@daynaslord @jkinmonth  I see that @kupsand  requested this post to be released on Eastern time, and he also requested you to review this PR. Also, as of 12-14-21 the link to Explorers Hub does not work. I will go ahead and publish this What's New to meet the requested deadline, but please follow up and make any necessary updates after it is live. Thanks! cc @rhetoric101

**Comment by kupsand** [comment]
Yes, the post will be live tonight eastern. 

Kevin Downs

**Comment by kupsand** [comment]
The Explorer’s Hub post is now live.

https://discuss.newrelic.com/t/infra-monitoring-with-amazon-ec2-to-see-lower-tdp-costs/170743

Thank you all.

Kevin Downs
***@***.*** & ***@***.***
(407) 474-4455

**Pull request merged**
