### PR TITLE
Improve index page sort order

### LINKED ISSUE #566: [Umbrella Issue] auto generated index pages for URLs match navigation structure
## Overview

This ☂️  accounts for several different issues that all relate back to the same problem the UX challenges we have from implementing a decoupled nav to URL approach.  That approach was sound and the right decision, but we are seeing some UX issues that should be addressed to help the expeirence of viewing and navigating documentation.

`TL:DR`  sort navigation hierarchy and auto generated page hierarchy in the same order

## Example Problems 

1. Original pricing/user mgmt stuff: https://docs.newrelic.com/docs/accounts/original-accounts-billing/. As you can see, that is a very messed up view of that section. Ideally we'd be able to link to a category to say stuff like 'For information on original pricing and user management, see ..." but we can't do that. We do actually link to these views in the docs so that is a broken experience currently.

2. AWS integrations category: https://docs.newrelic.com/docs/integrations/amazon-integrations/. As you can see, the order is messed up in there. Ideally we'd like to be able to link to this entire category, to say things like 'For information on AWS integrations, see ...."

3. NerdGraph category: https://docs.newrelic.com/docs/apis/nerdgraph/.

4. Open source telemetry integration list: https://docs.newrelic.com/docs/integrations/open-source-telemetry-integrations/. The 'Get started' is second in list.

5. The [dynamic menu for Key transactions](https://docs-preview.newrelic.com/docs/apm/transactions/key-transactions) does not show the same wording of items nor are they in the same sequence as they are on the [page's left nav](https://docs-preview.newrelic.com/docs/apm/transactions/key-transactions/introduction-key-transactions).
This makes navigation quite confusing.

Screen Shot 2021-01-14 at 12 56 54 PM

## Related issues Acceptance Criteria

`NOTE` Some of the below issues may be resolved when finish this work, so we can test these bugs out and closed that are fixed.

* #1572 (more context on why this creates problems for user journeys)
* #1584 (capitalization inconsistencies)
* #1585 (auto-generated navs having no sidebar)
* #1571 ? (Japanese auto-generated navs don't link to Japanese docs)
* #801 ? (missing words)

## Acceptance Criteria 

- [ ] All index pages will be ordered by section and by navigation order.
- [ ] If an page exists outside the navigation we'd sort that at the bottom of the section alphabetically.
- [ ] For index pages that have no navigation, like [AWS integration](https://docs.newrelic.com/docs/integrations/amazon-integrations/) sort in alphabetical order.
- [ ] Document how this works in the Style Guide - hand off to @austin-schaefer / @paperclypse on updating the Style Guide.

### PR DESCRIPTION
**Pull request by zstix**
## Description
Improves the sort order of our automatically generated index pages by applying the following updates (in order):

1. Sort the sections alphabetically (by section title)
2. Sort the links within the section alphabetically (by title)
3. Sort the sections by their relative position in the site navigation
4. Sort the links within the section by their relative position in the navigation

For steps 3 and 4, we're using the first navigation file that the script finds that includes the link (in the event that there are multiple nav configuration files).

## Reviewer Notes
I'm creating a draft PR in case I'm unable to wrap up the work. I've taken a TDD approach to solving the issue, since there are multiple edge cases that I wanted to ensure we caught. Here is my current progress:

* [x] Sort links alphabetically
* [x] Sort links by nav
* [ ] ~~Sort sections alphabetically~~
* [ ] ~~Sort sections by nav~~

## Related Issue(s)
* Closes #566

## Screenshot(s)
**Before**
Screen Shot 2021-04-26 at 11 12 13 AM

**After**
Screen Shot 2021-04-26 at 11 11 22 AM

### CODE REVIEW

**Comment by zstix** [comment]
Rather than sinking more time into getting the entire solution working, I'm going to mark this as ready for review with _just_ the list sorting. This should solve the issue referenced in the ticket, but this does _not_ include sorting the higher-level sections alphabetically and by the navigation. cc: @jpvajda 

Screen Shot 2021-04-26 at 10 47 45 AM

**Comment by jpvajda** [comment]
@zstix so it sounds like we can create a follow up ticket to eventually solve the following?

- Sort sections alphabetically
- Sort sections by nav  

or essentially the 4 cases you skipped in your tests.. 😎

**Comment by zstix** [comment]
@jpvajda Yes that's correct.

Technically, those tests pass if the commented code is brought back in. The problem is that it assumes a fixed level of nesting (only have 2 levels of nested sections). In reality, there are an arbitrary level of nested sections on these pages. We'd need to do a little more work (a few more hours) to account for this.

**Comment by zstix** [comment]
Here's another example of this PR resolving an issue:

Screen Shot 2021-04-26 at 11 58 00 AM

**Review by roadlittledawn — APPROVED** [review]
:shipit:

**Pull request merged**
