### PR TITLE
Fix double single quotes in metaDescription and wrap everything in double quotes

### PR DESCRIPTION
**Pull request by bradleycamacho**
This PR removes all double single quotes in `metaDescriptions`, and wraps all `metaDescriptions` in double quotes instead.

This built correctly, and I scanned a few dozen individual docs to ensure everything got replaced correctly. Please double check for me if you review this :)

Attaching the regEx I used as screenshots:
Screen Shot 2021-05-12 at 12 29 02 PM
Screen Shot 2021-05-12 at 12 22 54 PM

### CODE REVIEW

**Comment by bradleycamacho** [comment]
Original commit did not exclude Japanese docs. Reverted that commit and pushed two separate commits which exclude Japanese docs.

**Comment by austin-schaefer** [comment]
Building this locally now

**Comment by austin-schaefer** [comment]
Looks like there are still 13 files with double quotes in metaDescription:

image

**Review by austin-schaefer — CHANGES_REQUESTED** [review]
Hi @bradleycamacho , looks good but noticed a few docs where there are still some double-single-quotes in the metadescription. See screenshot. Thanks for doing this cleanup!

**Comment by austin-schaefer** [comment]
https://github.com/golang/go/issues/33006

**Comment by bradleycamacho** [comment]
No longer seems worth the effort.

If anyone ever reopens in the future, be sure to implement the fixes mentioned above and ensure merge conflicts are fixed.

**Pull request closed without merging**
