### PR TITLE
"What's new" Widget Packs 

### PR DESCRIPTION
**Pull request by f-akh23**
Please publish this on July 27 in the morning.
This post doesn't need a review by a PMM as it has already been reviewed and approved by PMM.

### CODE REVIEW

**Comment by f-akh23** [comment]
Embed link isn't working but correct link is inserted! Any help would be appreciated, thanks!

**Review by aalfano7 — APPROVED** [review]
Approved with proper formatting of embedded video

**Review by rhetoric101 — APPROVED** [review]
@f-akh23 thanks for adding this post! I just made a few minor changes.

**Comment by f-akh23** [comment]
@rhetoric101 thanks so much!

**Pull request merged**
