### PR TITLE
feat (what's new): Amazon Security Lake integration

### PR DESCRIPTION
**Pull request by kiranhew**
With this integration you can collect multi-region, multi-account security data from across your AWS microservices infrastructure and analyze that data in New Relic. This was launched today (5/30/2023) and the what's new post is ready to go live once reviewed by PMM

### CODE REVIEW

**Comment by rhetoric101** [comment]
I just updated from develop since we've had issues with an earlier version of develop today.

**Comment by rhetoric101** [comment]
This PR is failing on a bunch of images that have nothing to do with this "What's new" post. Our hero should look into this.

**Comment by nbaenam** [comment]
Triggered by a manual rebuild: https://build-7c374800-766a-49bd-908c-3b9ca929d77d.gatsbyjs.io/whats-new/2023/05/whats-new-05-30-amazon-security-lake/

**Review by nbaenam — APPROVED** [review]
Thank you for the update!! It looks good to me!

**Pull request merged**
