### PR TITLE
fix(docs): update browser api docs

### PR DESCRIPTION
**Pull request by ghost**
Need to update NPM install code examples.

Created from this issue Aron raised: https://github.com/newrelic/docs-website/issues/15015

The NPM instructions were added in this previous PR: https://github.com/newrelic/docs-website/pull/14808

### CODE REVIEW

**Comment by ally-sassman** [comment]
Hi Aron, I implemented these changes based on a request from @patrickhousley (https://github.com/newrelic/docs-website/pull/14808), but I think I missed a final review before merging to validate accuracy. Can you see my suggestions in the PR changed files and make suggestions there for what the browser api docs should say instead?

**Comment by ally-sassman** [comment]
@patrickhousley Can you please review the [browser API pages](https://docs.newrelic.com/docs/browser/new-relic-browser/browser-apis/addpageaction/), specifically the **Requirements** section for the npm installation instructions? I want to make sure they're all correct.

**Comment by patrickhousley** [comment]
@ally-sassman All the api pages are missing the features array in the example code.

Change

```
const options = {
  info: { ... },
  loader_config: { ... },
  init: {
    sessiontrace: { enabled: true }
  }
}
```

to this

```
const options = {
  info: { ... },
  loader_config: { ... },
  init: { ... },
  features: [
    SessionTrace
  ]
}

**Comment by ally-sassman** [comment]
Thanks @patrickhousley , I pushed a commit with your suggestion. Take a look and let me know if it's good to merge. Thanks!

**Review by paperclypse — DISMISSED** [review]
I can't tell if the code changes are correct, but I can tell that they're consistent.

**Comment by patrickhousley** [comment]
@ally-sassman All the docs look correct now, thanks for fixing that. The only thing I would callout is the indentation on the code snippets in the docs. It's pretty minor and just a visual annoyance but would be nice if it could be consistent. Otherwise, looks good to merge.

image

**Pull request merged**
