### PR TITLE
Update Issues-and-Incident-management-and-response.mdx

### PR DESCRIPTION
**Pull request by RoiBar1**
Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Comment by rhetoric101** [comment]
@RoiBar1 I pushed up a commit with some changes. I divided your new steps so they each have list of bullets. Could you take a look at these changes to see if they are accurate?

Also, could you sign our CLA again? It seems that we've lost all our CLA records.

**Comment by RoiBar1** [comment]
Thanks @rhetoric101 
Looks great 

Done :-)

**Comment by RoiBar1** [comment]
I sign CLA 
it is still in pending

**Comment by RoiBar1** [comment]
@rhetoric101

**Pull request merged**
