### PR TITLE
Updating FedRAMP Documents Page

### PR DESCRIPTION
**Pull request by jxainguyen**
Removing two listed out-of-scope services to better accurately reflect our environment.

Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Comment by jxainguyen** [comment]
Please hold off on merging until the build preview is complete - awaiting QA signoff from stakeholder. I'll comment back when it's g2g, thank you!!

**Comment by homelessbirds** [comment]
Sounds good! Thanks @jxainguyen !

**Comment by jxainguyen** [comment]
Thanks for the assist @homelessbirds . If the PDF looks good to you, my stakeholder signed-off on the rest of the content. 

Good to merge when you are.

**Review by zuluecho9 — APPROVED** [review]

**Comment by zuluecho9** [comment]
I'm going to merge this, and then see what happens, and then maybe try to follow up with a merge to fix the link if not working.

**Pull request merged**
