### PR TITLE
Update user-settings.mdx

### PR DESCRIPTION
**Pull request by RoiBar1**
Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Comment by x8a** [comment]
Hi, @homelessbirds! Could you make sure this one looks good? Thanks!

**Comment by homelessbirds** [comment]
@RoiBar1 it looks like you just need to sign the CLA and we can merge this in. Thanks!

**Comment by RoiBar1** [comment]
@homelessbirds 
How should I do it?

**Comment by austin-schaefer** [comment]
Hey @RoiBar1 , can you sign the CLA for this PR? I believe you can do it by clicking this yellow button:

image

**Review by homelessbirds — APPROVED** [review]

**Pull request merged**
