### PR TITLE
PUBLISH: 4/12: Agentless monitoring and standardized entity creation

### PR DESCRIPTION
**Pull request by vinrelic**
…re VMs, and GCP CE

This is going GA on Apr 11th 2024. It would be great if this release note got published on Apr 11th.

Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Review by akristen — APPROVED** [review]
Got this too build: https://app.netlify.com/sites/docs-website-netlify/deploys/6616ef08d990b6415eb937d4 Approving and will merge tomorrow AM!

**Comment by vinrelic** [comment]
@akristen Requesting the doc changes to get published on 12th Apr as the deployment is expected to take 24 hours. The team has started the deployment but we don't want the blog to go out before the deployment is complete. By EOD 11th Apr the deployment is expected to get over.

**Comment by akristen** [comment]
Sounds good @vinrelic

**Comment by vinrelic** [comment]
Team, we need to remove this release notes as there is an issue with capacity in Entity platform. Can someone help remove this release notes immediately? @akristen

**Comment by bradleycamacho** [comment]
Hi @vinrelic, I'm reverting those in this PR: https://github.com/newrelic/docs-website/pull/17010

**Pull request merged**
