### PR TITLE
docs: Updated infra agent support for amazon linux 2023

### PR DESCRIPTION
**Pull request by voorepreethi**
Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Review by nr-rkallempudi — APPROVED** [review]

**Review by jeff-colucci — DISMISSED** [review]

**Comment by jeff-colucci** [comment]
Hi @nr-rkallempudi , can you sign the CLA? It's required for us to merge any PRs into the docs. Please and thank you!

**Comment by jeff-colucci** [comment]
Hi @voorepreethi , could you sign the CLA for this PR? It's required before we can merge any PRs in!

@nr-rkallempudi Sorry for the unnecessary ping about signing the CLA earlier!

**Review by nr-rkallempudi — APPROVED** [review]

**Comment by voorepreethi** [comment]
@jeff-colucci  signed the CLA. Can you please verify the PR

**Review by hrai-nr — APPROVED** [review]

**Review by jeff-colucci — APPROVED** [review]

**Comment by jeff-colucci** [comment]
@voorepreethi Hi! For some reason the CLA is still showing as unsigned unfortunately. Can you check again to see if there are any issues on your end about it? If not we may need to resolve in Slack.

**Review by jeff-colucci — APPROVED** [review]

**Pull request closed without merging**
