### PR TITLE
fix: Corrects NRQL query and adds evaulation clarification

### PR DESCRIPTION
**Pull request by mfb2**
This PR updates the language of the usage alerting page:
* Removes invalid `SINCE` clause from NRQL example
* Clarifies time window language to outline relationship to hourly usage/consumption events

### CODE REVIEW

**Comment by mfb2** [comment]
@zuluecho9 I appreciate the speedy review and merge!!  However, this PR was genuinely still in draft 😬 

I opened this as a draft so that the Product Rating team could contribute updates/comments/etc.  I think what was merged should be fine, though we might revise/update as feedback rolls in.  Please let me know if you've got questions or need more info.  Thank you for your help!

**Comment by zuluecho9** [comment]
Oh I'm sorry. I thought it seemed like something that was currently true, based on my understanding. Sorry about that @mfb2. I will roll back.

**Comment by mfb2** [comment]
@zuluecho9 No worries!  The changes are an improvement over what had been there previously, so there's no downside to keeping them in place – it may just be subject to a bit more editing before we settle on a final version.

**Comment by zuluecho9** [comment]
Ah. I already reverted unfortunately; when you are able, could you create another PR based on your branch? I'm unsure how to do that and think you creating a new draft PR may be the best path forward. Sorry about the confusion, I should have asked and realized more changes might be coming.

**Comment by mfb2** [comment]
It's all good!  Easy to manage, no harm done 😄 

I'll be sure to open up a new PR once we've got updates.  Thanks so much for your help!!

**Pull request merged**
