### PR TITLE
docs: expermiment with razor/aspx lang identifiers

### PR DESCRIPTION
**Pull request by brnhensley**
I'm not sure this will work, these are not used often and my code editor doesn't recognize them. I also made some minor edits to page like capitalization and backticks.

Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Comment by brnhensley** [comment]
My goal here is to look at the preview build to see how this renders before attempting to merge a change

**Comment by paperclypse** [comment]
@brnhensley We don't currently support ASPX and Razor language identifiers. https://docs.newrelic.com/docs/style-guide/formatting/code-examples/#add-syntax-highlighting

We can try adding them to the `gatsby-config.js` file though. I'll try that now.

**Review by x8a — APPROVED** [review]
Thanks again!

**Comment by brnhensley** [comment]
Oh thanks, I had no idea that list was there. There are a couple I've used that work on our site that aren't on that list, like `bash`, `py`, and `cs`. But maybe the site is smart enough to redirect to the equivalent `shell`, `python` and `csharp`.

**Pull request merged**
