### PR TITLE
Node.js Agent v9.0.1 Release Notes

### PR DESCRIPTION
**Pull request by jordigh**
Node.js Agent v9.0.1 Release Notes

### CODE REVIEW

**Comment by bradleycamacho** [comment]
Hey @jordigh  thanks for the edit! Could you please sign the CLA above so I can merge this in? Thanks!

**Comment by jordigh** [comment]
Having some trouble with CLA assistant (and it's kind of silly to ask New Relic employees to tell New Relic that they have the right to give code to New Relic, surely that's already covered by my contract), but I think it's done now.

**Comment by jordigh** [comment]
Did I break the build? It doesn't seem like I can look at Gatsby. What's wrong?

**Comment by bradleycamacho** [comment]
Hey @jordigh looks like it's Gatsby acting up. I re-triggered the build and we can see what happens this time!

**Comment by bradleycamacho** [comment]
Hey @jordigh we triggered the build manually on Gatsby's side and it passed! It won't communicate back to GitHub so that's why it says it's failing still, but we're good to go! Merging in now. You should see these changes sometime around noon!

**Pull request merged**
