### PR TITLE
feat: Log Patterns updated from beta to GA

### PR DESCRIPTION
**Pull request by mculmone**
### Give us some context

* What problems does this PR solve?
Needed to update the log patterns beta docs for GA release today

* Add any context that will help us review your changes such as testing notes,
My yarn.lock file got updated locally somehow, and so I updated .gitignore to try and prevent it from committing. Unfortunately it committed both and I unwisely deleted them from my fork. Sorry.

Also: the URL of the patterns docs needs to change. Currently it is /docs/logs/log-management/ui-data/log-patterns-beta and needs to become /docs/logs/log-management/ui-data/log-patterns

Any main navigation should be changed to reflect this, and the redirects meta tag on the page should be updated.

* If your issue relates to an existing GitHub issue, please link to it.

### Are you making a change to site code?

If you're changing site code (rather than the content of a doc), please follow
[conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

### CODE REVIEW

**Comment by bradleycamacho** [comment]
@mculmone Thanks for the PR! I've pushed up some commits that fix the taxonomy and revert the commits to the yarn and git files. @barbnewrelic will take a look at this tomorrow and hopefully get it merged!

**Comment by mculmone** [comment]
Sorry about the yarn and . gitignore thing.

What's up with the taxonomy? What broke?

**Review by barbnewrelic — APPROVED** [review]
The Tech Docs team fixed the code issues. Let's go ahead and publish this as is, and I will do a copyedit as a separate PR. Overall your edits looked great!

**Comment by mculmone** [comment]
Are all the broken tests a blocker still or is this ok?

**Comment by bradleycamacho** [comment]
Hey @mculmone! We ran into quite a few issues with the status of this branch, and we somehow managed to push up thousands of cache files into it. We are going to close this specific PR and open a new one as #1767 restoring the content changes. Thanks!

**Pull request closed without merging**
