### PR TITLE
Update aws-lambda-sending-cloudwatch-logs.mdx to correct log forward configuration (env var)

### PR DESCRIPTION
**Pull request by umanorapracadadia**
Update Nov 23: Due to original handler leaving, we've moved this into general hero queue. Not time-sensitive. 

Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Comment by dbarnesbrownNR** [comment]
Hi @umanorapracadadia, thank you for your contribution! Would you please take a moment to sign the contributor license agreement by clicking the link in the CLAAssistant prompt above? Much appreciated!

**Review by MattWhelan — APPROVED** [review]
Sounds right. AWS re-designed the Lambda console some months ago.

**Review by rhetoric101 — APPROVED** [review]
@umanorapracadadia, thanks for suggesting this update! Sorry it took so long to get this approved!

**Comment by rhetoric101** [comment]
I am temporarily closing this so that when I re-open it, the build checks will restart.

**Comment by rhetoric101** [comment]
@umanorapracadadia, it looks like we need you to sign the CLA agreement before we're allowed to publish your contribution. Could you sign this so we can publish this? If you have any questions about how to do this, let me know.

**Comment by rhetoric101** [comment]
@umanorapracadadia, thanks again for this contribution! Since we haven't heard back from you about signing the CLA, we are closing this PR. 

We'll go ahead and create our own PR to correct this issue.

**Pull request closed without merging**
