### PR TITLE
Update newrelic_record_custom_event.mdx

### PR DESCRIPTION
**Pull request by neilpdx**
Confirmed with engineering that we should call out that custom events won't be reported when the transaction is being ignored.

Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Comment by nbaenam** [comment]
Hi @neilpdx, thank you for the update! A quick question, did you want to have the new content inside the tip note? The line is outside the note. Have you taken a look at [the build](https://build-e131af8f-2754-41b3-bee6-91108e32c071.gatsbyjs.io/docs/apm/agents/php-agent/php-agent-api/newrelic_record_custom_event/)? Confirm that this is the way you want to be in our docs, please. Thanks!

**Comment by nbaenam** [comment]
Hi @neilpdx! Any update on this? Can you have a look at [the build](https://build-e131af8f-2754-41b3-bee6-91108e32c071.gatsbyjs.io/docs/apm/agents/php-agent/php-agent-api/newrelic_record_custom_event/) and let me know if the new content must go inside the tip note or outside? Thanks!!!

**Comment by nbaenam** [comment]
Hi @neilpdx, any update on this?

**Comment by nbaenam** [comment]
Hi @neilpdx! any update on this?

**Comment by nbaenam** [comment]
Hi @neilpdx! any update on this?

**Comment by neilpdx** [comment]
Hey @nbaenam — sorry I missed this. I think the new content should go inside the Tip note with the rest of the tips.

**Comment by clarkmcadoo** [comment]
hung build, restarting

**Review by nbaenam — APPROVED** [review]
Thank you for the update!! It looks good to me!

**Pull request merged**
