### PR TITLE
First draft of the expanded anomaly detection doc

### PR DESCRIPTION
**Pull request by paperclypse**
I'm pushing this up so that I can get a Gatsby preview. Not ready for a PR review.

### CODE REVIEW

**Comment by paperclypse** [comment]
This one is ready for a peer edit/PR review. The AI team wants this published tomorrow.

**Comment by lthelen** [comment]
Looks like one.newrelic.com is a link in one place but not the other

**Comment by lthelen** [comment]
Something about this paragraph seems off -  maybe the "Instead" should be removed.

**See your anomalies in one place**
When you set up anomaly detection, New Relic started analyzing the golden signals of your entities and workloads. Instead, anomalies appear in your activity feeds throughout New Relic One and the Anomalies tab as soon as they’re detected.

**Review by dbarnesbrownNR — APPROVED** [review]
Looks amazing, I'm blown away by how quickly you pulled a whole page together!

**Pull request merged**
