### PR TITLE
fix(apm): add APM screenshot

### PR DESCRIPTION
**Pull request by bradleycamacho**
This adds an example APM screenshot to the APM intro doc.  It also moves the "Get started" section higher in the doc.

### CODE REVIEW

**Comment by bradleycamacho** [comment]
@barbnewrelic I struggled a bit with the placement and the caption text. Please let me know if you have any better ideas!

**Review by barbnewrelic — CHANGES_REQUESTED** [review]
I'm not seeing the screenshot in Gatsby preview https://docswebsitedevelop-apmss.gtsb.io/docs/apm/new-relic-apm/getting-started/introduction-apm/  . Pretty sure you need to include the /images path on line 19.

**Comment by bradleycamacho** [comment]
@barbnewrelic Good catch, it should work now!

**Review by barbnewrelic — APPROVED** [review]
Bonus points for noticing that partial sentence! Thanks for updating this doc!

**Pull request merged**
