### PR TITLE
docs: +lang identifiers

### PR DESCRIPTION
**Pull request by brnhensley**
I'm not sure if we recognize `.ini` file types in markdown, but I added them just in case

Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Comment by rhetoric101** [comment]
@brnhensley I just added the code fence for .ini files. Let's see how that looks in the preview.

**Comment by brnhensley** [comment]
Your `ini` addition looks good already in the preview. Thanks!
image (12)

I've added these in a couple other spots as well so that's cool.

**Comment by brnhensley** [comment]
thanks for adding `properties`, it looks nice

**Review by rhetoric101 — APPROVED** [review]
@brnhensley thanks for making these updates! The properties syntax looks good, too!

**Pull request merged**
