### PR TITLE
Add https://gov-bam.nr-data.net for FedRAMP

### PR DESCRIPTION
**Pull request by rajumkc**
Add https://gov-bam.nr-data.net for FedRAMP compliance

Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Comment by bradleycamacho** [comment]
Hey there @rajumkc, thanks for the edit! I'm having another Relic review this, but while we wait could you sign the CLA? It's the small yellow button in the comment below your PR description. Thanks!

**Comment by bradleycamacho** [comment]
Hey @rajumkc, just checking in on this again! As soon as you sign the CLA, I can get this merged :)

**Comment by rajumkc** [comment]
Hi @bradleycamacho - How do I sign the CLA?

**Comment by rajumkc** [comment]
> Hi @bradleycamacho - How do I sign the CLA?

All good now. Thanks!

**Comment by barbnewrelic** [comment]
@rajumkc  There have been already been several other updates to the FedRAMP doc which incorporate your suggestions, so I'm going to close this PR. Congrats on your first contributions to our docs site!

**Pull request closed without merging**
