### PR TITLE
docs(opentelemetry-go-runtime-page): Add new Go runtime documentation 

### PR DESCRIPTION
**Pull request by relicdl**
Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* This PR adds documentation that is the sister to a pre-existing doc page: https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/view-your-data/opentelemetry-jvms-page/ 
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Comment by rkbodenner** [comment]
@homelessbirds Please hold publication until the new UI the doc describes is released. @relicdl or I will give the 👍 here when that's ready. Thanks!

**Comment by homelessbirds** [comment]
Sounds good @rkbodenner!

**Comment by austin-schaefer** [comment]
@rhetoric101 : What's the status on this one? Should this go into the "drafts" column or is it ready to go out pending review?

**Comment by rkbodenner** [comment]
Still blocked on software release @rhetoric101 @austin-schaefer

**Comment by rkbodenner** [comment]
The feature is in production, so this is ready to ship!

**Comment by rhetoric101** [comment]
@rkbodenner I am closing this temporarily to trigger a new build so I can take another look at the preview that is currently broken.

**Review by rhetoric101 — APPROVED** [review]
@relicdl we had some build challenges, but we finally got them sorted out. We're going to get this published! Thanks for adding this information!

**Comment by relicdl** [comment]
Excellent, thank you so much!

**Pull request merged**
