### PR TITLE
chore: add synthetics url field description

### PR DESCRIPTION
**Pull request by mderemer-nr**
Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
   * Links to URL definition and specifies we only allow http and https schemes
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.
   * [It's better to describe what is supported url syntax by Synthetics monitor #3928 ](https://github.com/newrelic/docs-website/issues/3928)

### CODE REVIEW

**Comment by mderemer-nr** [comment]
Had to redo this in order to sign cla

**Comment by mderemer-nr** [comment]
@urbiz-nr This is a dup of the previous one i [closed](https://github.com/newrelic/docs-website/pull/4922). Had to switch users in order to accept cla.

**Comment by zuluecho9** [comment]
@mderemer-nr I made a light edit to it; didn't think we needed to link to definition of URL but curious if you disagree. Thank you!

**Comment by mderemer-nr** [comment]
@zuluecho9 Thats fine by me.

**Review by zuluecho9 — APPROVED** [review]

**Pull request merged**
