### PR TITLE
Fix link for OpenTelemetry JS OTLP gRPC exporter

### PR DESCRIPTION
**Pull request by svetlanabrennan**
Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Comment by dbarnesbrownNR** [comment]
Hi @svetlanabrennan, thanks for the fix! Before docs team can merge, we need a signed CLA (see the comment with link from CLAassistant in the conversation above). Change looks good so once that's signed we're good to go!

**Comment by svetlanabrennan** [comment]
I signed the CLA.

**Comment by svetlanabrennan** [comment]
Any updates on this pr?

**Comment by zuluecho9** [comment]
sorry about that @svetlanabrennan, slipped through cracks, merging now.

**Review by zuluecho9 — APPROVED** [review]

**Pull request merged**
