### PR TITLE
Document accountId() function

### PR DESCRIPTION
**Pull request by rbayersdorfer-newrelic**
## Document new accountId() function - **DO NOT MERGE YET**

### CODE REVIEW

**Comment by austin-schaefer** [comment]
Hi @rbayersdorfer-newrelic , looks like this PR is marked as a "draft." Is this still pending, or is it ready to be reviewed and merged?

**Comment by rbayersdorfer-newrelic** [comment]
This is still in draft phase, thanks for checking. We will let you know when it's ready to be merged when the function is GA'd

**Comment by urbiz-nr** [comment]
Hello @rbayersdorfer-newrelic - are there any updates on this draft? Thanks!

**Comment by bradleycamacho** [comment]
Hey @mlobiondo-newrelic @rbayersdorfer-newrelic , please let us know whenever this is ready for release!

**Comment by mlobiondo-newrelic** [comment]
> Hey @mlobiondo-newrelic @rbayersdorfer-newrelic , please let us know whenever this is ready for release!

@bradleycamacho We still don't have a date but it should be soon.  We'll let you know as soon as I know more.

**Comment by mlobiondo-newrelic** [comment]
@bradleycamacho Rebasing this got messy and it seemed easier to create a new PR.  It's here:  https://github.com/newrelic/docs-website/pull/6854.  This one can be closed.

**Pull request closed without merging**
