### PR TITLE
Create new-relic-android-4750.mdx

### PR DESCRIPTION
**Pull request by michael-bone**
## Give us some context

* Release notes for New Relic Android mobile app

### CODE REVIEW

**Review by rhetoric101 — APPROVED** [review]
@michael-bone thanks for adding these release notes!

**Comment by rhetoric101** [comment]
@michael-bone are you working at New Relic? I'm not recognizing your handle?

**Comment by michael-bone** [comment]
> @michael-bone are you working at New Relic? I'm not recognizing your handle?

Yep! I just chose Michael Bone since that's my first/last name on issues.newrelic.com

**Comment by rhetoric101** [comment]
Temporarily closing so I can kick off a new build when reopening.

**Pull request merged**
