### PR TITLE
fix(Pixie):Add Advanced Configuration section

### PR DESCRIPTION
**Pull request by htroisi**
This PR includes a minor navigation bar reorganization to create an "Advanced Configuration" section for Pixie.

### CODE REVIEW

**Comment by bradleycamacho** [comment]
@htroisi Just restarting the build! I'll review once it builds.

**Comment by htroisi** [comment]
@bradleycamacho - could you remove the 3 reviewers from this PR? They were accidentally added when I did a rebase.

**Comment by akristen** [comment]
> 

Removed!

**Review by akristen — APPROVED** [review]
They look great! Thanks for your work on the Pixie docs!

**Pull request merged**
