### PR TITLE
feat(php): 10.4 release notes

### PR DESCRIPTION
**Pull request by ZNeumann**
php agent v10.4.0.316 was released yesterday.

### CODE REVIEW

**Comment by nbaenam** [comment]
Hi @ZNeumann!! Thank you for updating our docs! Could you please sign the CLA? We can't merge it without doing it. Thanks!

**Comment by ZNeumann** [comment]
signed

**Review by jeff-colucci — APPROVED** [review]
Saw only one tiny thing but other than that it looked good.

**Comment by jeff-colucci** [comment]
Bypassing the license/cla check as proof of signing is reported in this ticket already.

**Pull request merged**
