### PR TITLE
Update k8s-agent-operator.mdx

### LINKED ISSUE #17930: k8s-agents-operator documentation has invalid nodejs docker reference
## Description

The k8s agent operator [documentation](newrelic/newrelic-nodejs-init:latest) references, in the CRD yaml, the docker image ```newrelic/newrelic-nodejs-init:latest```, which does not exist. However, ```newrelic/newrelic-node-init:latest``` does exist. I can't say if the documentation is incorrect or if the docker image was published with the wrong name, so starting here...

## Steps to reproduce

1. Follow instructions [here](https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/installation/k8s-agent-operator/#configuring-namespace)
2. Attempt to auto instrument a node js application
3. Observe that the docker image referenced in the documentation cannot be found.

### PR DESCRIPTION
**Pull request by jvice**
docs: correct reference to newrelic-node-init docker image

fixes #17930 

Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Comment by bradleycamacho** [comment]
Hi @jvice , thanks for the edit! Could you sign the CLA above by clicking the yellow button so I can get this merged in? Thank you!

**Comment by jvice** [comment]
> Hi @jvice , thanks for the edit! Could you sign the CLA above by clicking the yellow button so I can get this merged in? Thank you!

done

**Comment by nbaenam** [comment]
Hi @mangulonr, could you please review this one? Thanks!

**Review by mangulonr — APPROVED** [review]

**Comment by mangulonr** [comment]
> Hi @mangulonr, could you please review this one? Thanks!

LGTM! Thanks @nbaenam

**Review by nbaenam — APPROVED** [review]
Hi @jvice, thank you for the update!

**Pull request merged**
