### PR TITLE
fix(NRQL): fixed screenshots

### PR DESCRIPTION
**Pull request by jeff-colucci**
Marking work done from [this ticket](https://github.com/newrelic/docs-website/issues/10652)

### CODE REVIEW

**Review by thezackm — CHANGES_REQUESTED** [review]
@jeff-colucci - thanks so much! one quick note: 

above the clamp image there's pre-existing text:
```
The following chart shows the result of clamping both min and max to keep the value in the range 70-90.
```

The new query is this:
```sql
FROM SystemSample SELECT
average(cpuPercent) AS 'raw',
clamp_min(clamp_max(average(cpuPercent), 98), 96) AS 'clamped'
TIMESERIES
```

so the text should now read: 
```
The following chart shows the result of clamping both min and max to keep the value in the range 96-98.
```

---

I'd argue that we should also add a sample query there, but with the upcoming changes you've already planned it's low priority.

**Comment by jeff-colucci** [comment]
@thezackm Thanks for the suggestion and good eye! Is it as straightforward as adding the query you put in your comment to the documentation? I can make the change to say "the following query and chart" instead of just "the following chart" and then list the query as well.

**Comment by thezackm** [comment]
@jeff-colucci - yes I think so; just a code block for the NRQL - it's pretty generic and is a good example of how to nest the clamp functions together

**Comment by jeff-colucci** [comment]
@thezackm Very good, I've updated the doc to have the example in it and tweaked the wording around it as well. If you could take a look at it and let me know that it came out correctly I think I can get a TW review and merge it in today. As an aside, if you have any other ideas for examples of NRQL throughout the documentation, either new examples or refining some older ones we have in place, please reach out at any time and I will get them changed. NRQL examples are something I'm kind of constantly looking at so any help there would be very appreciated.

**Review by thezackm — APPROVED** [review]
🚀

**Comment by jeff-colucci** [comment]
Thanks @rhetoric101 and good call, I'll make a note and probably have a ticket to do that next sprint

**Pull request merged**
