### PR TITLE
[improvement] Add directions for instrumenting a mixed Windows/Linux Kubernetes cluster

### PR DESCRIPTION
**Pull request by maxlemieux**
* What problems does this PR solve?
We don't document Kubernetes integration installation for a mixed cluster today. 

* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.

This recipe has been tested on mixed clusters on AKS and is drawn from a combination of two public docs:

Preview Windows installation (Only describes `newrelic-infrastructure` v2 installation, does not address anything else in the bundle): https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/installation/kubernetes-integration-install-configure/#windows-install

Helm installation (Only addresses the bundle on Linux, does not address Windows): https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/installation/kubernetes-integration-install-configure/#man-helm

### CODE REVIEW

**Comment by maxlemieux** [comment]
Thanks for all the improvements. I fixed '2002' to '2022' with that last commit.

**Comment by maxlemieux** [comment]
@bpschmitt when you have time, could you please review this content from @inderjeet-sandy and me? Thanks.

**Review by nbaenam — APPROVED** [review]
Hi @maxlemieux. I've added a new commit with my changes. Let me know if you have questions.

**Comment by nbaenam** [comment]
Hi @bpschmitt, any update on this? Could we merge this PR? Thanks!

**Comment by bpschmitt** [comment]
@nbaenam go ahead and merge it.  I'll come back and open another PR with some minor updates later.

**Pull request merged**
