### PR TITLE
chore(usage dictionary): Clarify AWS product naming

### PR DESCRIPTION
**Pull request by austin-schaefer**
Opening a PR to try to clarify how to refer to AWS product names.

### CODE REVIEW

**Review by amyreinholds — COMMENTED** [review]
I'd recommend this:
    * Refer to `Amazon Web Services (AWS)` on first instance. Then you may use `AWS` thereafter.
    
Also, including links to those special product names would be helpful for context. Suggested rewrite:

    * Amazon has several products like [Amazon EC2](https://aws.amazon.com/documentation-overview/ec2/) and [Amazon S3](https://aws.amazon.com/documentation-overview/s3/) that are almost always referred to by their abbreviated name, rather than the full name.

**Review by rhetoric101 — DISMISSED** [review]
@austin-schaefer thanks for these updates. I just made a few minor tweaks.

**Review by amyreinholds — COMMENTED** [review]
Also, including links to those special product names would be helpful for context. Suggested rewrite:
* Amazon has several products like [Amazon EC2](https://aws.amazon.com/documentation-overview/ec2/) and [Amazon S3](https://aws.amazon.com/documentation-overview/s3/) that are almost always referred to by their abbreviated name, rather than the full name.

**Comment by austin-schaefer** [comment]
Thanks @amyreinholds @rhetoric101 ! Just incorporated Amy's feedback.

**Review by rhetoric101 — APPROVED** [review]

**Pull request merged**
