### PR TITLE
Add and update documentation for .NET Lambda Layers using the New Relic Lambda CLI tool.

### PR DESCRIPTION
**Pull request by jaffinito**
## Give us some context

* What problems does this PR solve?
  * Add and update documentation for .NET Lambda Layers using the New Relic Lambda CLI tool.
* If your issue relates to an existing GitHub issue, please link to it.
  * https://github.com/newrelic/newrelic-lambda-cli/pull/283

### CODE REVIEW

**Comment by bradleycamacho** [comment]
Hi @jaffinito, thanks for the PR! This one might take me a second to review. I can get it live by EoW, but just wanted to make sure there wasn't a pressing deadline!

**Comment by jaffinito** [comment]
EoW works great!

**Comment by jaffinito** [comment]
@bradleycamacho Can we hold off on publishing this till Friday afternoon?  The CLI tool this goes with has not released our changes yet.

**Comment by bradleycamacho** [comment]
@jaffinito absolutely. I'll try to get this reviewed and approved today. Just shoot me a slack tomorrow whenever it's ready to go live.

**Review by jeff-colucci — APPROVED** [review]
All the .NET stuff looks good to my eyes!

**Comment by jaffinito** [comment]
The new CLI version with the .NET changes has been released.  This is good to go when you can get to it!

**Review by homelessbirds — APPROVED** [review]

**Pull request merged**
