### PR TITLE
Title case -> sentence case

### PR DESCRIPTION
**Pull request by austin-schaefer**
### Give us some context

Minor casing fix

### Are you making a change to site code?

If you're changing site code (rather than the content of a doc), please follow
[conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

### CODE REVIEW

**Review by urbiz-nr — APPROVED** [review]
I'dd add the title anchors/links too

**Comment by austin-schaefer** [comment]
@urbiz-nr : Do we need titles/anchors for What's new posts?

**Comment by urbiz-nr** [comment]
Mmmm good question. Doesn't hurt though, does it?

**Review by barbnewrelic — COMMENTED** [review]
Team had discussed in April 21 team meeting that we leave marketing's title case as is

**Pull request closed without merging**
