### PR TITLE
(fix): Updated the temporal docs.

### PR DESCRIPTION
**Pull request by pkudikyala**
**Jira ticket:** https://new-relic.atlassian.net/browse/NR-283746
**Description:** Added the temporal logs integration steps in the documentation.

Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Review by rhetoric101 — DISMISSED** [review]
@pkudikyala sorry for the delay! I made a few changes. Can you review them to confirm the instructions are still correct?

**Comment by pkudikyala** [comment]
> @pkudikyala sorry for the delay! I made a few changes. Can you review them to confirm the instructions are still correct?

Hi @rhetoric101 ,
Your changes are all correct, but one adjustment is needed: please change the title of step 4 to **Configure NRI-Prometheus**.
For reference: https://deploy-preview-17750--docs-website-netlify.netlify.app/docs/infrastructure/host-integrations/host-integrations-list/sonarqube-monitoring-integration/#configure-nri-prometheus

Thanks...

**Comment by rhetoric101** [comment]
@pkudikyala sorry for the delay. Does this recent change look OK: https://deploy-preview-17750--docs-website-netlify.netlify.app/docs/infrastructure/host-integrations/host-integrations-list/temporal-monitoring-integration/

**Comment by pkudikyala** [comment]
> @pkudikyala sorry for the delay. Does this recent change look OK: https://deploy-preview-17750--docs-website-netlify.netlify.app/docs/infrastructure/host-integrations/host-integrations-list/temporal-monitoring-integration/

Hi @rhetoric101 ,
It's looking good to me. Could you please merge it?

**Review by rhetoric101 — APPROVED** [review]
@pkudikyala Thanks for adding this doc!

**Pull request merged**
