### PR TITLE
Bring in final style guide docs (I hope)

### PR DESCRIPTION
**Pull request by paperclypse**
### Tell us why

I'm not 100% sure, but I think this is the final batch of style guide docs we need to bring over.

### Anything else you'd like to share?

I definitely need a second pair of eyes on this, because it's a lot of changes: moving files around and a lot of updates to the navigation file.

### CODE REVIEW

**Comment by austin-schaefer** [comment]
@paperclypse : Not grabbing for a full review, but do we need redirects for the moved/removed files?

**Comment by bradleycamacho** [comment]
Looks good just scanning. Building locally now.

**Review by bradleycamacho — APPROVED** [review]
Looks good to me, good job @paperclypse! Let me know if you decide to add redirects as @austin-schaefer recommends above - I'll take another look if so,

**Comment by paperclypse** [comment]
@austin-schaefer We shouldn't need redirects... but I should probably add them, just to be on the safe side.

**Comment by bradleycamacho** [comment]
@paperclypse Seems like the redirects work for me! I think this is ready to merge.

**Pull request merged**
