### PR TITLE
Remove Agent SDK tile from release notes landing page

### LINKED ISSUE #902: Remove agent SDK from release notes tiles
### Description

The agent SDK has been EoLed. We should remove the tile from the release notes page. We can also do this from a content perspective post-launch. We can also just delete this tile.

### Steps to reproduce

1. Go to https://docs-preview.newrelic.com/docs/release-notes
2. Look at `Agent SDK` tile, click it, and see that it leads not to release notes but to a doc

### Expected behavior

Let's remove this entry entirely

### Screenshots

image

### PR DESCRIPTION
**Pull request by jerelmiller**
Closes #902

### Tell us why

The Agent SDK has been EOL'd. This PR removes the tile and applies the changes from the manual edits to the real landing page.

### CODE REVIEW

**Comment by roadlittledawn** [comment]
do we also have to remove from the left nav? @austin-schaefer 's screenshot seemed to imply that

**Comment by jerelmiller** [comment]
Ah good question! I guess I just looked at the text, but not the screenshot. @austin-schaefer to confirm, are you looking to remove it from the nav as well?

**Review by zstix — APPROVED** [review]

**Comment by austin-schaefer** [comment]
@jerelmiller Yes, good catch @roadlittledawn . We should remove from sidebar as well.

**Comment by jerelmiller** [comment]
Perfect! I'll update this PR to remove from the sidebar as well

**Comment by roadlittledawn** [comment]
as long as @austin-schaefer is fine with removing the 2 agent sdk release notes themselves as well, looks good to me!

**Comment by austin-schaefer** [comment]
Kill 'em with fire @roadlittledawn . 🔥

**Pull request merged**
