### PR TITLE
Update create-nrql-alert-conditions.mdx

### PR DESCRIPTION
**Pull request by barbnewrelic**
style(3 callouts): Drove me nuts
Callouts are great, unless there are 3 in a row. Added another h3 and turned them into paragraphs

Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Comment by barbnewrelic** [comment]
@austin-schaefer  I'm requesting you as reviewer because this is something I had noticed during bug bash recentlywe-love-tips

**Review by urbiz-nr — APPROVED** [review]
OMG great fix! I'd add the anchor to the title, but this is so much better!

**Comment by austin-schaefer** [comment]
I'm breathing easier just reading it!

**Review by austin-schaefer — APPROVED** [review]

**Comment by barbnewrelic** [comment]
@urbiz-nr  in my haste to get rid of the green I forgot to add the anchor. thanks for catching that! fixing now

**Pull request merged**
