### PR TITLE
Re-rank FSO nav more sensibly

### PR DESCRIPTION
**Pull request by austin-schaefer**
### Tell us why

Barb pointed out some sort order issues with the FSO nav.

### CODE REVIEW

**Comment by austin-schaefer** [comment]
@barbnewrelic : Did some re-ordering of the FSO nav (just the top-level categories). LMK your thoughts.

**Comment by austin-schaefer** [comment]
Here's a screengrab of the new order

**Comment by jpvajda** [comment]
Is this still a valid PR?

**Comment by jerelmiller** [comment]
Still valid. I think we're waiting on a review from @barbnewrelic

**Comment by austin-schaefer** [comment]
If it’s building right I’d say let’s merge. I can tweak ordering further if @barbnelic has peer edit suggestions.


________________________________

**Comment by jerelmiller** [comment]
Done

**Pull request merged**
