### PR TITLE
incorrect markdown caused p-tags (and expected style margins).. this removes it

### PR DESCRIPTION
**Pull request by AubreyHewes**
### Tell us why

Incorrect markdown in list caused a p tag, so also the p tag style (margin et al)

fixes https://github.com/newrelic/docs-website/issues/945 

[#gatsbyconf](https://github.com/newrelic/docs-website/issues?q=is%3Aissue+is%3Aopen+label%3A%23gatsbyconf)

### CODE REVIEW

**Review by jerelmiller — APPROVED** [review]
This is a really great solution to this problem! I'll make sure to communicate this with the teams that contribute content daily to make it easy to determine when best to apply the newline or not. Appreciate the contribution!

**Comment by AubreyHewes** [comment]
@jerelmiller Hm, actually I dont think this actually fixes the problem... I was to eager.. It will have to be a styling fix for p in lists.. 
As the spacing in the screenshot is the margin of the p from the parent list item; this removes the spacing from the child item and the image....

:sheep:

**Comment by jerelmiller** [comment]
Thats interesting! I actually tried this locally and it _seemed_ to do what I expected. Perhaps we should open up the other issue again?

That being said, I do see what you're saying and I think it might be good to try and remove that margin if the `p` tag is the "last child of type" so that nested lists don't end up with the gap as well.

Our global styles are controlled by [our theme](https://github.com/newrelic/gatsby-theme-newrelic/blob/develop/packages/gatsby-theme-newrelic) so that we can share it among all of our sites. Perhaps [this CSS rule](https://github.com/newrelic/gatsby-theme-newrelic/blob/develop/packages/gatsby-theme-newrelic/src/components/GlobalStyles/GlobalStyles.js#L55-L57) needs to handle `:last-of-type` as well 🤔 (which I believe might also solve this issue).

**Comment by AubreyHewes** [comment]
Yeah currently the theme uses p:last-child... last-of-type could be better

**Comment by AubreyHewes** [comment]
The theme has no source map so I cant say where... but if you inspect the "Using the filter bar at the top, narrow your searches" you will see it has a margin-bottom... if you inspect the first item (without a sub list) it has no margin bottom.

**Comment by jerelmiller** [comment]
That sounds accurate!

**Comment by jpvajda** [comment]
@AubreyHewes thanks so much for the contribution!! Do you mind completing this form so we can send you a gift from New Relic. 🎁  https://forms.gle/EQNmAV9X3UsMxHJy7

**Comment by AubreyHewes** [comment]
@jpvajda Yeah but the fix was not the fix... and should be reverted is still ongoing (@ theme)

**Comment by jpvajda** [comment]
@AubreyHewes sure thing. Just when the merge is approved in our theme and deploy just send us the info so we can get you the 🎁 .

**Comment by AubreyHewes** [comment]
@jpvajda form does not work for international postcodes ;-) (error: must be a number)

**Comment by jpvajda** [comment]
@AubreyHewes sorry about that. It's fixed now, will accept strings. 😄

**Comment by AubreyHewes** [comment]
@jpvajda while you are about it... :sheep: email is required twice (at the start and nearly the end) x

**Comment by jpvajda** [comment]
@AubreyHewes thanks for testing our form. I removed the duplicate field. 🎉

**Pull request merged**
