### PR TITLE
feat: Add in setup info for iOS widget configuration

### PR DESCRIPTION
**Pull request by jvanmetre**
## Give us some context

* Customer request for a feature that already exists so we are adding in a documentation page around the configuration
* View the page at /docs/mobile-apps/ios-app/ios-widgets
* [NR-1264](https://issues.newrelic.com/browse/NR-1264)

### CODE REVIEW

**Comment by rhetoric101** [comment]
I am closing this temporarily to see if I can trigger a successful re-check.

**Comment by jvanmetre** [comment]
looks good https://docswebsitedevelop-jvanmetredocswebsitedocsnr1264.gtsb.io/docs/mobile-apps/ios-app/ios-widgets 👍

**Comment by jvanmetre** [comment]
@rhetoric101 These resized images look blurry in the gatsby preview, was that intentional?

**Comment by jvanmetre** [comment]
This loos great 👍

**Pull request merged**
