### PR TITLE
fix: duplicate anchor link

### PR DESCRIPTION
**Pull request by achwie-bosch**
Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
  * Anchor link for Event Timer detail section doesn't work because it's the same as for Event Flow (probably copy&paste error) 
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Review by urbiz-nr — APPROVED** [review]
Thanks for fixing the link, @achwie-bosch!

**Comment by urbiz-nr** [comment]
@achwie-bosch, could you please sign the CLA so we can proceed with the changes? You'll only need to do this once!

**Comment by achwie-bosch** [comment]
Hey, sorry I'm afraid I can't sign the CLA without prior consultation of our legal department (which I don't want to do right now because I've got other things to do). So maybe it's easiest if you do the change yourself and delete my branch.

**Comment by urbiz-nr** [comment]
Fixed in #5053.

**Pull request closed without merging**
