### PR TITLE
Fix broken links

### PR DESCRIPTION
**Pull request by miguelsancheznewrelic**
Links were relative rather than absolute, forming an invalid URL like:
- https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/introduction-nrql-new-relics-query-language/docs/query-your-data/explore-query-data/dashboards/introduction-dashboards/
- https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/introduction-nrql-new-relics-query-language/docs/query-your-data/explore-query-data/query-builder/introduction-query-builder/

Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Review by jeff-colucci — APPROVED** [review]

**Comment by jeff-colucci** [comment]
Thanks for finding these!

**Comment by miguelsancheznewrelic** [comment]
Hi @jeff-colucci , @mlobiondo-newrelic created before me another one https://github.com/newrelic/docs-website/pull/10699
Please just use one and close the other.

**Comment by jeff-colucci** [comment]
> FYI @jeff-colucci , probably we should do an audit (search everywhere for `(docs`) to see if there are more broken links

Yes this is a good idea, I will make a note to do this at some point in the near future. Hopefully it was just an artifact from my first doc for the site.

**Comment by jeff-colucci** [comment]
I've got the one from @mlobiondo-newrelic done too! I'm just waiting for Gatsby to rebuild before I merge it. No worries.

**Pull request merged**
