### PR TITLE
chore: updating to latest grok pattern

### PR DESCRIPTION
**Pull request by thezackm**
updating grok pattern to match changes pushed to prod today

### CODE REVIEW

**Comment by zuluecho9** [comment]
thanks @thezackm!

**Comment by barbnewrelic** [comment]
@thezackm  Thanks for making this update! If you need to make any changes to the standalone parsing doc https://docs.newrelic.com/docs/logs/ui-data/parsing , would you mind just adding them to my PR https://github.com/newrelic/docs-website/pull/6059 ? That way I can bundle your edits into mine and hopefully avoid merge conflicts. (My PR should be going out on Monday.) If you need any edits on that doc to go out today, no worries, I'll just untangle on Monday. Thanks again for updating our docs!

**Comment by thezackm** [comment]
@barbnewrelic - thanks for the head's up - this is the only page I need to edit on this round 😄

**Comment by barbnewrelic** [comment]
@thezackm  yay, you!

**Pull request merged**
