### PR TITLE
release notes for CPM release 3.1.5

### PR DESCRIPTION
**Pull request by kaschaefer-nr**
Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve? Adds release notes for latest CPM release
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Comment by homelessbirds** [comment]
Hi @kaschaefer-nr-- would you mind signing the CLA? You might have signed it in the past, but it has been updated.

**Comment by kaschaefer-nr** [comment]
hey @homelessbirds  I went ahead and signed it! let me know if there's anything else you need from me :)

**Review by homelessbirds — APPROVED** [review]

**Comment by homelessbirds** [comment]
Hi @kaschaefer-nr it looks like @achow-nr needs to sing the CLA as well. I didn't notice that at first!

**Comment by kaschaefer-nr** [comment]
I think he already did but I'll ping him

**Comment by achow-nr** [comment]
Hi @homelessbirds, I have signed the CLA agreement now. Thank you!

**Comment by homelessbirds** [comment]
Thank you both!

**Pull request merged**
