### PR TITLE
chore: Remove muted status from documents

### PR DESCRIPTION
**Pull request by kaschaefer-nr**
Please follow [conventional commit standards](https://www.conventionalcommits.org/en/v1.0.0/)
in your commit messages and pull request title.

## Give us some context

* What problems does this PR solve?
It removes references to the MUTED monitor status which is scheduled for removal on February 29th. After the EOL is confirmed, we will upgrade this PR from draft to full PR.
* Add any context that will help us review your changes such as testing notes,
  links to related docs, screenshots, etc.
* If your issue relates to an existing GitHub issue, please link to it.

### CODE REVIEW

**Comment by akristen** [comment]
Hey @kaschaefer-nr! thanks for submitting the PR. Reach out to us in the docs channel when this is ready for a review + merge. In the meantime, I'm going to merge the most recent develop into this branch since we've switched to Netlify. (I'd recommend syncing your fork upstream if you haven't recently!)

**Comment by akristen** [comment]
Also! If you could resign our CLA. We had to update it when we migrated from Gatsby. Thanks again!

**Comment by kaschaefer-nr** [comment]
ok gc

**Comment by kaschaefer-nr** [comment]
Can I get someone's help understanding these netflify build failures?

**Review by ally-sassman — APPROVED** [review]

**Pull request merged**
