### PR TITLE
APM Java agent: Change "third-party-integrations" folder to "related-integrations"

### PR DESCRIPTION
**Pull request by rhetoric101**
This is a follow up on a previous PR where I renamed the Java navigation node to "Related integrations" but forgot to change the underlying folder name!

### CODE REVIEW

**Review by jeff-colucci — APPROVED** [review]
This SEEMS fine to me but there's a problem with unpaired translations?

**Review by cbehera-newrelic — DISMISSED** [review]
All files are renamed correctly and the Old URLs pointing to the corresponding updated URLs.

**Review by jeff-colucci — DISMISSED** [review]
Looks good to me.

**Comment by rhetoric101** [comment]
@jeff-colucci I'm afraid I missed the issue about the i18n orphaned files. I just removed those with the script!

**Review by ally-sassman — APPROVED** [review]

**Pull request merged**
